In [1]:
# ============================================================
# CHECKPOINT 1 — FRAMING THE PROBLEM
# ============================================================

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 100)

# Load dataset
df = pd.read_csv("house_sale.csv")

# ------------------------------------------------------------
# 1. Business Problem / Target Validation
# ------------------------------------------------------------

print("Shape:", df.shape)

print("\nCurrency distribution:")
print(df["currency_x"].value_counts(dropna=False))

print(
    "\nRaw price range (AZN):",
    df["price"].min(),
    "-",
    df["price"].max()
)

# Target checks
assert "price" in df.columns, "Target column 'price' not found"
assert pd.api.types.is_numeric_dtype(
    df["price"]
), "price is not numeric"
assert df["price"].isnull().sum() == 0, (
    "price has missing values"
)
assert (df["price"] > 0).all(), (
    "Found non-positive price values"
)

print("\nTarget column:", "price")
print("Rows:", len(df))
print(
    "Price range (AZN):",
    df["price"].min(),
    "-",
    df["price"].max()
)
print("All initial target checks passed.")


# ============================================================
# CHECKPOINT 2 — FULL EDA AND CLEANING
# ============================================================

# ------------------------------------------------------------
# 2.1 Initial Dataset Inspection
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.1 INITIAL DATASET INSPECTION")
print("=" * 70)

print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nExact duplicate rows:")
print(df.duplicated().sum())

print("\nFirst 5 rows:")
display(df.head())

print("\nNumerical summary:")
display(df.describe())


# ------------------------------------------------------------
# 2.2 Checking price and total_price
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.2 PRICE VS TOTAL_PRICE")
print("=" * 70)

price_equal_rate = (
    df["price"] == df["total_price"]
).mean()

print(
    "Percentage of rows where price == total_price:",
    price_equal_rate
)

print("\nDifference between price and total_price:")
display(
    (df["price"] - df["total_price"]).describe()
)


# ------------------------------------------------------------
# 2.3 Checking _x and _y Columns
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.3 _X / _Y COLUMN CHECK")
print("=" * 70)

pairs = [
    ("id_x", "id_y"),
    ("estate_rel_url_x", "estate_rel_url_y"),
    ("datetime_scrape_x", "datetime_scrape_y"),
    ("currency_x", "currency_y"),
    ("estate_details_id_x", "estate_details_id_y"),
    ("estate_rel_url_x", "estate_rel_url"),
]

for col1, col2 in pairs:
    same = (
        df[col1].fillna("__MISSING__")
        == df[col2].fillna("__MISSING__")
    ).mean()

    print(
        f"{col1} vs {col2}: {same:.2%} identical"
    )


# ------------------------------------------------------------
# 2.4 Investigating Extreme Price Values
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.4 EXTREME PRICE VALUES")
print("=" * 70)

print("Prices below 1,000 AZN:")
display(
    df[df["price"] < 1000][
        [
            "price",
            "location",
            "attributes",
            "Sahə",
            "Otaq sayı"
        ]
    ].head(20)
)

print("\nPrices above 10 million AZN:")
display(
    df[df["price"] > 10_000_000][
        [
            "price",
            "location",
            "attributes",
            "Sahə",
            "Otaq sayı"
        ]
    ].head(20)
)

print(
    "\nBelow 1,000 AZN:",
    (df["price"] < 1000).sum()
)

print(
    "Above 10 million AZN:",
    (df["price"] > 10_000_000).sum()
)


# ------------------------------------------------------------
# 2.5 Repeated Property Listings
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.5 REPEATED PROPERTY LISTINGS")
print("=" * 70)

print(
    "Duplicate estate IDs:",
    df["estate_id"].duplicated().sum()
)

print(
    "Duplicate property URLs:",
    df["estate_rel_url"].duplicated().sum()
)

url = (
    df["estate_rel_url"]
    .value_counts()
    .idxmax()
)

print("\nMost repeated property URL:")
print(url)

display(
    df[df["estate_rel_url"] == url][
        [
            "estate_rel_url",
            "estate_id",
            "price",
            "Sahə",
            "Otaq sayı",
            "location"
        ]
    ]
)

print("\nScraping dates for repeated property:")
display(
    df[df["estate_rel_url"] == url][
        [
            "estate_rel_url",
            "estate_id",
            "price",
            "datetime_scrape_x",
            "datetime_scrape_y"
        ]
    ]
)

url_counts = df["estate_rel_url"].value_counts()

print(
    "\nProperties appearing more than once:",
    (url_counts > 1).sum()
)

print(
    "Maximum appearances of one property:",
    url_counts.max()
)

price_changes = (
    df.groupby("estate_rel_url")["price"]
    .nunique()
)

print(
    "\nProperties with different prices:",
    (price_changes > 1).sum()
)

print(
    "Properties with the same price:",
    (price_changes == 1).sum()
)

repeated_rows = (
    df["estate_rel_url"]
    .duplicated(keep=False)
    .sum()
)

print(
    "\nRows belonging to repeated properties:",
    repeated_rows
)

print(
    "Unique properties:",
    df["estate_rel_url"].nunique()
)

print(
    "Rows if one row per property were kept:",
    df.drop_duplicates("estate_rel_url").shape[0]
)


# ------------------------------------------------------------
# 2.6 Checking unit_price
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.6 UNIT_PRICE")
print("=" * 70)

print(
    df["unit_price"]
    .dropna()
    .head(20)
    .tolist()
)

print("\nRandom examples:")
print(
    df["unit_price"]
    .dropna()
    .sample(
        20,
        random_state=42
    )
    .tolist()
)


# ------------------------------------------------------------
# 2.7 Create Working Modeling DataFrame
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.7 CREATE WORKING DATAFRAME")
print("=" * 70)

drop_cols = [
    "total_price",
    "unit_price",
    "estate_rel_url_y",
    "currency_y",
    "estate_details_id_y",
    "datetime_scrape_y",
    "id_x",
    "id_y",
    "estate_id",
    "estate_details_id_x",
    "rel_url",
    "img_url"
]

df_model = df.drop(
    columns=drop_cols,
    errors="ignore"
).copy()

print(
    "Shape after removing leakage/redundant identifier columns:",
    df_model.shape
)

print("\nRemaining columns:")
print(df_model.columns.tolist())


# ------------------------------------------------------------
# 2.8 Missing Value Analysis
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.8 MISSING VALUE ANALYSIS")
print("=" * 70)

missing_percent = (
    df_model.isnull().mean() * 100
).sort_values(ascending=False)

print("Missing values (%):")
display(missing_percent)


# ------------------------------------------------------------
# 2.9 Remove Features with >80% Missing Values
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.9 HIGH MISSINGNESS FEATURES")
print("=" * 70)

high_missing_cols = (
    missing_percent[
        missing_percent > 80
    ]
    .index
    .tolist()
)

print(
    "Features with more than 80% missing values:"
)
print(high_missing_cols)

df_model = df_model.drop(
    columns=high_missing_cols
)

print(
    "\nShape after removing highly incomplete features:",
    df_model.shape
)


# ------------------------------------------------------------
# 2.10 Checking Duplicate Categorical Features
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.10 DUPLICATE CATEGORICAL FEATURES")
print("=" * 70)

# repair vs Təmir
repair_comparison = pd.DataFrame({
    "repair": df_model["repair"].fillna(
        "__MISSING__"
    ),
    "Təmir": df_model["Təmir"].fillna(
        "__MISSING__"
    )
})

print(
    "repair vs Təmir:",
    (
        repair_comparison["repair"]
        == repair_comparison["Təmir"]
    ).mean()
)

print("\nrepair vs Təmir crosstab:")
display(
    pd.crosstab(
        df_model["repair"].fillna("__MISSING__"),
        df_model["Təmir"].fillna("__MISSING__"),
        dropna=False
    )
)

# mortgage vs İpoteka
mortgage_comparison = pd.DataFrame({
    "mortgage": df_model["mortgage"].fillna(
        "__MISSING__"
    ),
    "İpoteka": df_model["İpoteka"].fillna(
        "__MISSING__"
    )
})

print(
    "\nmortgage vs İpoteka:",
    (
        mortgage_comparison["mortgage"]
        == mortgage_comparison["İpoteka"]
    ).mean()
)

print("\nmortgage vs İpoteka crosstab:")
display(
    pd.crosstab(
        df_model["mortgage"].fillna("__MISSING__"),
        df_model["İpoteka"].fillna("__MISSING__"),
        dropna=False
    )
)

# bill_of_sale vs Çıxarış
bill_comparison = pd.DataFrame({
    "bill_of_sale": df_model["bill_of_sale"].fillna(
        "__MISSING__"
    ),
    "Çıxarış": df_model["Çıxarış"].fillna(
        "__MISSING__"
    )
})

print(
    "\nbill_of_sale vs Çıxarış:",
    (
        bill_comparison["bill_of_sale"]
        == bill_comparison["Çıxarış"]
    ).mean()
)

print("\nbill_of_sale vs Çıxarış crosstab:")
display(
    pd.crosstab(
        df_model["bill_of_sale"].fillna("__MISSING__"),
        df_model["Çıxarış"].fillna("__MISSING__"),
        dropna=False
    )
)

duplicate_categorical_cols = [
    "repair",
    "mortgage",
    "bill_of_sale"
]

df_model = df_model.drop(
    columns=duplicate_categorical_cols
)

print(
    "\nShape after removing redundant categorical columns:",
    df_model.shape
)


# ------------------------------------------------------------
# 2.11 Re-check Missing Values
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.11 REMAINING MISSING VALUES")
print("=" * 70)

missing_pct = (
    df_model.isnull().mean() * 100
).sort_values(ascending=False)

display(
    missing_pct[
        missing_pct > 0
    ]
)


# ------------------------------------------------------------
# 2.12 Inspect Remaining Missing Values
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.12 INSPECT REMAINING MISSING VALUES")
print("=" * 70)

missing_cols = df_model.columns[
    df_model.isnull().any()
]

for col in missing_cols:
    print(f"\n===== {col} =====")
    display(
        df_model[col]
        .value_counts(
            dropna=False
        )
        .head(10)
    )


# ------------------------------------------------------------
# 2.13 Area Unit Analysis
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.13 AREA UNIT ANALYSIS")
print("=" * 70)

df_model["area_unit"] = (
    df_model["Sahə"]
    .str.extract(
        r"(m²|m2|sot)",
        expand=False
    )
)

print(
    df_model["area_unit"]
    .value_counts(
        dropna=False
    )
)


# ------------------------------------------------------------
# 2.14 Investigating Missing Room Counts
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.14 MISSING ROOM COUNTS")
print("=" * 70)

print(
    "Room counts:"
)

display(
    df_model["Otaq sayı"]
    .value_counts(
        dropna=False
    )
    .sort_index()
)

missing_rooms_by_unit = (
    df_model
    .groupby("area_unit")["Otaq sayı"]
    .apply(
        lambda x: x.isna().sum()
    )
)

print(
    "\nMissing room counts by area unit:"
)

display(
    missing_rooms_by_unit
)

print(
    "\nMissing room count for m² listings:"
)

display(
    df_model[
        df_model["Otaq sayı"].isna()
        &
        (df_model["area_unit"] == "m²")
    ][
        [
            "price",
            "Sahə",
            "location",
            "Təmir",
            "İpoteka"
        ]
    ].head(30)
)


# ------------------------------------------------------------
# 2.15 Convert Area to Numerical Features
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.15 AREA NUMERICAL FEATURES")
print("=" * 70)

df_model["area_value"] = (
    df_model["Sahə"]
    .str.extract(
        r"([\d.]+)",
        expand=False
    )
    .astype(float)
)

df_model["area_m2"] = (
    df_model["area_value"]
)

df_model.loc[
    df_model["area_unit"] == "sot",
    "area_m2"
] = (
    df_model.loc[
        df_model["area_unit"] == "sot",
        "area_value"
    ] * 100
)

display(
    df_model[
        [
            "Sahə",
            "area_unit",
            "area_value",
            "area_m2"
        ]
    ].head(20)
)


# ------------------------------------------------------------
# 2.16 Missing Categorical Value Analysis
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.16 MISSING CATEGORICAL VALUES")
print("=" * 70)

cols_to_check = [
    "İpoteka",
    "Təmir",
    "Otaq sayı",
    "products_label"
]

for col in cols_to_check:
    print(f"\n===== {col} =====")

    print(
        "Missing:",
        df_model[col].isna().sum()
    )

    print(
        "Missing %:",
        round(
            df_model[col].isna().mean() * 100,
            2
        )
    )


# ------------------------------------------------------------
# 2.17 Target Distribution by Missingness
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.17 TARGET DISTRIBUTION BY MISSINGNESS")
print("=" * 70)

for col in cols_to_check:

    print(f"\n===== {col} =====")

    print(
        "Price when value is missing:"
    )

    display(
        df_model.loc[
            df_model[col].isna(),
            "price"
        ].describe()
    )

    print(
        "Price when value is not missing:"
    )

    display(
        df_model.loc[
            df_model[col].notna(),
            "price"
        ].describe()
    )


# ------------------------------------------------------------
# 2.18 Investigating Mortgage
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.18 MORTGAGE ANALYSIS")
print("=" * 70)

print(
    df_model["İpoteka"]
    .value_counts(
        dropna=False
    )
)

print("\nMortgage = var:")
display(
    df_model[
        df_model["İpoteka"] == "var"
    ][
        [
            "price",
            "Sahə",
            "location",
            "Otaq sayı",
            "Təmir"
        ]
    ].head(20)
)

print("\nMortgage = missing:")
display(
    df_model[
        df_model["İpoteka"].isna()
    ][
        [
            "price",
            "Sahə",
            "location",
            "Otaq sayı",
            "Təmir"
        ]
    ].head(20)
)


# ------------------------------------------------------------
# 2.19 Investigating products_label
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.19 PRODUCTS_LABEL ANALYSIS")
print("=" * 70)

print(
    df_model["products_label"]
    .value_counts(
        dropna=False
    )
)

print("\nProducts_label = missing:")
display(
    df_model[
        df_model["products_label"].isna()
    ][
        [
            "price",
            "Sahə",
            "location",
            "Otaq sayı",
            "Təmir",
            "İpoteka"
        ]
    ].head(20)
)

print("\nProducts_label = available:")
display(
    df_model[
        df_model["products_label"].notna()
    ][
        [
            "price",
            "Sahə",
            "location",
            "Otaq sayı",
            "Təmir",
            "İpoteka"
        ]
    ].head(20)
)

print(
    "\nPrice when products_label is missing:"
)

display(
    df_model.loc[
        df_model["products_label"].isna(),
        "price"
    ].describe()
)

print(
    "\nPrice when products_label is not missing:"
)

display(
    df_model.loc[
        df_model["products_label"].notna(),
        "price"
    ].describe()
)

print(
    "\nPrice distribution by products_label:"
)

display(
    df_model.groupby(
        df_model["products_label"]
        .fillna("Missing")
    )["price"].describe()
)

for col in [
    "location",
    "Təmir",
    "İpoteka"
]:

    print(
        f"\n===== {col} vs products_label ====="
    )

    display(
        pd.crosstab(
            df_model[col],
            df_model["products_label"],
            normalize="index"
        ).round(3)
    )


# ------------------------------------------------------------
# 2.20 Fill Categorical Missing Values
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.20 CATEGORICAL MISSING VALUE HANDLING")
print("=" * 70)

for col in [
    "İpoteka",
    "Təmir",
    "Çıxarış",
    "products_label"
]:

    df_model[col] = (
        df_model[col]
        .fillna("Missing")
    )

print("\nİpoteka:")
print(
    df_model["İpoteka"]
    .value_counts()
)

print("\nTəmir:")
print(
    df_model["Təmir"]
    .value_counts()
)

print("\nÇıxarış:")
print(
    df_model["Çıxarış"]
    .value_counts()
)

print("\nproducts_label:")
print(
    df_model["products_label"]
    .value_counts()
)


# ------------------------------------------------------------
# 2.21 Seller / Agency Features
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.21 SELLER / AGENCY FEATURES")
print("=" * 70)

print(
    df_model[
        [
            "owner_name",
            "owner_title",
            "shop_name",
            "shop_title"
        ]
    ].isnull().sum()
)

seller_cols = [
    "owner_name",
    "shop_name",
    "shop_title"
]

df_model = df_model.drop(
    columns=seller_cols
)

print(
    "Shape after removing seller/agency identifier-like columns:",
    df_model.shape
)


# ------------------------------------------------------------
# 2.22 Floor Features
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.22 FLOOR FEATURES")
print("=" * 70)

print(
    "Unique Mərtəbə values:",
    df_model["Mərtəbə"].nunique()
)

display(
    df_model["Mərtəbə"]
    .dropna()
    .head(20)
)

floor_parts = (
    df_model["Mərtəbə"]
    .str.split(
        "/",
        expand=True
    )
)

df_model["floor"] = pd.to_numeric(
    floor_parts[0],
    errors="coerce"
)

df_model["total_floors"] = pd.to_numeric(
    floor_parts[1],
    errors="coerce"
)

display(
    df_model[
        [
            "Mərtəbə",
            "floor",
            "total_floors"
        ]
    ].head(20)
)


# ------------------------------------------------------------
# 2.23 Price per m² — Exploratory Analysis Only
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.23 PRICE PER M²")
print("=" * 70)

df_model["price_per_m2"] = np.where(
    df_model["area_m2"] > 0,
    df_model["price"] /
    df_model["area_m2"],
    np.nan
)

display(
    df_model[
        [
            "price",
            "Sahə",
            "area_m2",
            "price_per_m2"
        ]
    ].head(20)
)

display(
    df_model["price_per_m2"].describe(
        percentiles=[
            0.01,
            0.05,
            0.25,
            0.50,
            0.75,
            0.95,
            0.99
        ]
    )
)


# ------------------------------------------------------------
# 2.24 Extreme Price per m² Values
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.24 EXTREME PRICE PER M² VALUES")
print("=" * 70)

print("Highest price/m² observations:")

display(
    df_model.nlargest(
        20,
        "price_per_m2"
    )[
        [
            "price",
            "Sahə",
            "area_unit",
            "area_m2",
            "price_per_m2",
            "location"
        ]
    ]
)

print("Lowest price/m² observations:")

display(
    df_model.nsmallest(
        20,
        "price_per_m2"
    )[
        [
            "price",
            "Sahə",
            "area_unit",
            "area_m2",
            "price_per_m2",
            "location"
        ]
    ]
)


# ------------------------------------------------------------
# 2.25 Flag Potentially Unusual Price per m²
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.25 PRICE PER M² FLAGS")
print("=" * 70)

df_model["price_per_m2_flag"] = (
    (df_model["price_per_m2"] < 100)
    |
    (df_model["price_per_m2"] > 10000)
)

print(
    "Potentially unusual price/m² observations:",
    df_model["price_per_m2_flag"].sum()
)

display(
    df_model[
        df_model["price_per_m2_flag"]
    ][
        [
            "price",
            "Sahə",
            "area_unit",
            "area_value",
            "area_m2",
            "price_per_m2",
            "location"
        ]
    ]
    .sort_values(
        "price_per_m2"
    )
    .head(20)
)


# ------------------------------------------------------------
# 2.26 Extremely Large Areas
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.26 EXTREMELY LARGE AREAS")
print("=" * 70)

display(
    df_model["area_m2"].describe(
        percentiles=[
            0.01,
            0.05,
            0.25,
            0.50,
            0.75,
            0.95,
            0.99
        ]
    )
)

large_area_mask = (
    df_model["area_m2"] > 10000
)

print(
    "Properties with area > 10,000 m²:",
    large_area_mask.sum()
)

display(
    df_model[
        large_area_mask
    ][
        [
            "price",
            "Sahə",
            "area_unit",
            "area_value",
            "area_m2",
            "location"
        ]
    ]
    .sort_values(
        "area_m2",
        ascending=False
    )
    .head(30)
)


# ------------------------------------------------------------
# 2.27 Remove Temporary EDA Variables
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.27 REMOVE TEMPORARY EDA VARIABLES")
print("=" * 70)

df_model = df_model.drop(
    columns=[
        "price_per_m2",
        "price_per_m2_flag"
    ],
    errors="ignore"
)


# ------------------------------------------------------------
# 2.28 Remove Original Text Area / Floor Columns
# ------------------------------------------------------------

df_model = df_model.drop(
    columns=[
        "Sahə",
        "Mərtəbə"
    ],
    errors="ignore"
)


# ------------------------------------------------------------
# 2.29 Final Feature Cleanup
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.29 FINAL FEATURE CLEANUP")
print("=" * 70)

# Constant currency feature
if (
    "currency_x" in df_model.columns
    and df_model["currency_x"].nunique(dropna=False) == 1
):
    df_model = df_model.drop(
        columns=["currency_x"]
    )

# Remove redundant URL copy if it is identical
if (
    "estate_rel_url_x" in df_model.columns
    and "estate_rel_url" in df_model.columns
):
    url_same = (
        df_model["estate_rel_url_x"].fillna("__MISSING__")
        ==
        df_model["estate_rel_url"].fillna("__MISSING__")
    ).mean()

    print(
        "estate_rel_url_x vs estate_rel_url:",
        f"{url_same:.2%}"
    )

    if url_same == 1.0:
        df_model = df_model.drop(
            columns=["estate_rel_url_x"]
        )


# ------------------------------------------------------------
# 2.30 Final Dataset Check
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.30 FINAL DATASET CHECK")
print("=" * 70)

print(
    "Final cleaned dataframe shape:",
    df_model.shape
)

print("\nFinal columns:")
print(df_model.columns.tolist())

print("\nRemaining missing values:")
display(
    df_model.isnull()
    .sum()
    .sort_values(
        ascending=False
    )
    .head(30)
)

print("\nData types:")
print(df_model.dtypes)


# ------------------------------------------------------------
# 2.31 Final Leakage / Identifier Check
# ------------------------------------------------------------

leakage_or_identifier_cols = [
    "total_price",
    "unit_price",
    "id_x",
    "id_y",
    "estate_id",
    "estate_rel_url_x",
    "estate_rel_url_y",
    "estate_details_id_x",
    "estate_details_id_y",
    "rel_url",
    "img_url",
    "price_per_m2",
    "price_per_m2_flag"
]

remaining_leakage_cols = [
    col
    for col in leakage_or_identifier_cols
    if col in df_model.columns
]

print(
    "\nRemaining leakage/identifier columns:",
    remaining_leakage_cols
)


# ------------------------------------------------------------
# 2.32 Group Identifier for Repeated Properties
# ------------------------------------------------------------

if "estate_rel_url" in df_model.columns:

    groups = (
        df_model["estate_rel_url"]
        .copy()
    )

    print(
        "\nUnique property groups:",
        groups.nunique()
    )

    print(
        "Total observations:",
        len(groups)
    )


# ------------------------------------------------------------
# 2.33 Final Target / Feature Separation
# ------------------------------------------------------------

y = df_model["price"].copy()

X = df_model.drop(
    columns=["price"]
).copy()

print(
    "\nX shape:",
    X.shape
)

print(
    "y shape:",
    y.shape
)

print(
    "\nTarget range:",
    y.min(),
    "-",
    y.max()
)


# ------------------------------------------------------------
# 2.34 Final Assertions
# ------------------------------------------------------------

assert "price" not in X.columns

assert (
    "price_per_m2" not in X.columns
)

assert (
    "price_per_m2_flag" not in X.columns
)

assert (
    "total_price" not in X.columns
)

assert (
    "unit_price" not in X.columns
)

assert y.isnull().sum() == 0

assert (y > 0).all()

print(
    "\nAll final Checkpoint 2 checks passed."
)

Shape: (100775, 51)

Currency distribution:
currency_x
AZN    100775
Name: count, dtype: int64

Raw price range (AZN): 11.0 - 600000000.0

Target column: price
Rows: 100775
Price range (AZN): 11.0 - 600000000.0
All initial target checks passed.

======================================================================
2.1 INITIAL DATASET INSPECTION
======================================================================

Shape:
(100775, 51)

Columns:
['id_x', 'rel_url', 'estate_rel_url_x', 'datetime_scrape_x', 'price', 'currency_x', 'location', 'attributes', 'city_when', 'city', 'day_x', 'hour_x', 'repair', 'vip', 'featured', 'products_label', 'bill_of_sale', 'mortgage', 'img_url', 'id_y', 'estate_id', 'estate_rel_url_y', 'datetime_scrape_y', 'description', 'unit_price', 'total_price', 'currency_y', 'owner_name', 'owner_title', 'shop_name', 'shop_title', 'address', 'lat', 'lng', 'updated', 'views', 'day_y', 'hour_y', 'estate_details_id_x', 'Binanın növü', 'Kateqoriya', 'Mərtəbə', 'Otaq sayı', 'Sahə', 'Torpaq sahəsi', 'Təmir', 'Çıxarış', 'İpoteka', 'estate_details_id_y', 'estate_rel_url', 'extra_info']

Data types:
id_x                    object
rel_url                 object
estate_rel_url_x        object
datetime_scrape_x       object
price                  float64
currency_x              object
location                object
attributes              object
city_when               object
city                    object
day_x                   object
hour_x                  object
repair                  object
vip                     object
featured                object
products_label          object
bill_of_sale            object
mortgage                object
img_url                 object
id_y                    object
estate_id               object
estate_rel_url_y        object
datetime_scrape_y       object
description             object
unit_price              object
total_price            float64
currency_y              object
owner_name              object
owner_title             object
shop_name               object
shop_title              object
address                 object
lat                    float64
lng                    float64
updated                 object
views                    int64
day_y                   object
hour_y                  object
estate_details_id_x     object
Binanın növü            object
Kateqoriya              object
Mərtəbə                 object
Otaq sayı              float64
Sahə                    object
Torpaq sahəsi           object
Təmir                   object
Çıxarış                 object
İpoteka                 object
estate_details_id_y     object
estate_rel_url          object
extra_info              object
dtype: object

Missing values:
id_x                        0
rel_url                     0
estate_rel_url_x            0
datetime_scrape_x           0
price                       0
currency_x                  0
location                    0
attributes                  0
city_when                   0
city                        0
day_x                       0
hour_x                      0
repair                  19163
vip                     92179
featured                97626
products_label          28145
bill_of_sale            21210
mortgage                67836
img_url                     0
id_y                        0
estate_id                   0
estate_rel_url_y            0
datetime_scrape_y           0
description               265
unit_price              24779
total_price                 0
currency_y                  0
owner_name                657
owner_title               657
shop_name               28757
shop_title              28757
address                     0
lat                         0
lng                         0
updated                     0
views                       0
day_y                       0
hour_y                  85144
estate_details_id_x         0
Binanın növü           100621
Kateqoriya                  0
Mərtəbə                 24779
Otaq sayı                9412
Sahə                        0
Torpaq sahəsi           85204
Təmir                    6001
Çıxarış                     0
İpoteka                 67836
estate_details_id_y         0
estate_rel_url              0
extra_info                  0
dtype: int64

Exact duplicate rows:
0

First 5 rows:

,id_x,rel_url,estate_rel_url_x,datetime_scrape_x,price,currency_x,location,attributes,city_when,city,day_x,hour_x,repair,vip,featured,products_label,bill_of_sale,mortgage,img_url,id_y,estate_id,estate_rel_url_y,datetime_scrape_y,description,unit_price,total_price,currency_y,owner_name,owner_title,shop_name,shop_title,address,lat,lng,updated,views,day_y,hour_y,estate_details_id_x,Binanın növü,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Torpaq sahəsi,Təmir,Çıxarış,İpoteka,estate_details_id_y,estate_rel_url,extra_info
0,5df36281-6dc6-4d5d-89a7-5fcfa86f7608,/alqi-satqi?page=174,/items/4521724,2024-10-05 22:07:37.60613+00,499999.0,AZN,Səbail r.,"4 otaqlı, 145 m², 7/9 mərtəbə","Bakı, dünən 23:52",bakı,05.10.2024,23:52,Təmirli,vipped,featured,NaN,Çıxarış var,NaN,https://bina.azstatic.com/uploads/f460x345/202...,92e82ea2-e1f3-4c2d-a284-151efd99281e,5df36281-6dc6-4d5d-89a7-5fcfa86f7608,/items/4521724,2024-10-05 22:14:10.089116+00,"Səbail Rayonu, İzzət Nəbiyev küçəsi, Fəxri Xiy...",3 450 AZN/m²,499999.0,AZN,Kamran,mülkiyyətçi,NaN,NaN,İzzət Nəbiyev küç.,40.358817,49.824092,yeniləndi: dünən 23:52,1155,05.10.2024,23:52,92e82ea2-e1f3-4c2d-a284-151efd99281e,NaN,Köhnə tikili,7 / 9,4.0,145 m²,NaN,var,var,NaN,92e82ea2-e1f3-4c2d-a284-151efd99281e,/items/4521724,Şəhidlər xiyabanı * Dağüstü parkı * Səbail r.
1,883e20f0-8872-49a5-8b4b-63b8301b5f8f,/alqi-satqi?page=250,/items/4669294,2024-10-05 22:07:37.60613+00,77000.0,AZN,Biləcəri q.,"4 otaqlı, 90 m²","Bakı, dünən 23:56",bakı,05.10.2024,23:56,Təmirli,NaN,NaN,NaN,NaN,NaN,https://bina.azstatic.com/uploads/f460x345/202...,505eaf81-6bc8-4094-9b00-aa82066548ee,883e20f0-8872-49a5-8b4b-63b8301b5f8f,/items/4669294,2024-10-05 22:14:10.089116+00,"Biləcəridə Abidəyə yaxin 91,92,202 saylı marşr...",NaN,77000.0,AZN,Dasinmaz Emlak,vasitəçi (agent),NaN,NaN,Biləcəri qəs.,40.420897,49.807035,yeniləndi: 04 oktyabr 2024,218,04.10.2024,NaN,505eaf81-6bc8-4094-9b00-aa82066548ee,NaN,Həyət evi/Bağ evi,NaN,4.0,90 m²,1.3 sot,var,yoxdur,NaN,505eaf81-6bc8-4094-9b00-aa82066548ee,/items/4669294,Binəqədi r.* Biləcəri q.
2,55c36fb1-a3af-476e-ba17-a81f6795be8d,/alqi-satqi?page=250,/items/4669293,2024-10-05 22:07:37.60613+00,92000.0,AZN,İnşaatçılar m.,"3 otaqlı, 60 m²","Bakı, dünən 23:55",bakı,05.10.2024,23:55,Təmirli,NaN,NaN,NaN,Çıxarış var,NaN,https://bina.azstatic.com/uploads/f460x345/202...,fa63b201-999d-43b5-a61a-778d9d79a6c6,55c36fb1-a3af-476e-ba17-a81f6795be8d,/items/4669293,2024-10-05 22:14:10.089116+00,Salam əleykum. \nİnşaatçılar metrosuna yaxın m...,NaN,92000.0,AZN,Məhəmməd,vasitəçi (agent),NaN,NaN,Mirzə Cabbar Məmmədzadə küç.,40.390293,49.802656,yeniləndi: 04 oktyabr 2024,190,04.10.2024,NaN,fa63b201-999d-43b5-a61a-778d9d79a6c6,NaN,Həyət evi/Bağ evi,NaN,3.0,60 m²,0.1 sot,var,var,NaN,fa63b201-999d-43b5-a61a-778d9d79a6c6,/items/4669293,İnşaatçılar m.* Yasamal r.
3,acf1aa8d-a46a-40f5-b6f2-f7a449569337,/alqi-satqi?page=250,/items/4647811,2024-10-05 22:07:37.60613+00,95000.0,AZN,Qaraçuxur q.,130 m²,"Bakı, dünən 23:55",bakı,05.10.2024,23:55,Təmirli,vipped,featured,NaN,Çıxarış var,İpoteka var,https://bina.azstatic.com/uploads/f460x345/202...,5db56980-05cc-4925-b55b-f58fb3f4d2b6,acf1aa8d-a46a-40f5-b6f2-f7a449569337,/items/4647811,2024-10-05 22:14:10.089116+00,Barter maraqlidir üstünlük maşina verilir\nHər...,NaN,95000.0,AZN,Elçin,mülkiyyətçi,NaN,NaN,Qaraçuxur qəs.,40.393614,49.981553,yeniləndi: 04 oktyabr 2024,1314,04.10.2024,NaN,5db56980-05cc-4925-b55b-f58fb3f4d2b6,NaN,Obyekt,NaN,NaN,130 m²,NaN,var,var,var,5db56980-05cc-4925-b55b-f58fb3f4d2b6,/items/4647811,Suraxanı r.* Qaraçuxur q.
4,22d840df-9283-4112-bc71-7432511fc776,/alqi-satqi?page=250,/items/4638863,2024-10-05 22:07:37.60613+00,220000.0,AZN,Əhmədli m.,"3 otaqlı, 100 m², 15/16 mərtəbə","Bakı, dünən 23:52",bakı,05.10.2024,23:52,Təmirli,NaN,NaN,Agentlik,Çıxarış var,NaN,https://bina.azstatic.com/uploads/f460x345/202...,d71cf9a9-86dd-4162-b540-6252a8659a09,22d840df-9283-4112-bc71-7432511fc776,/items/4638863,2024-10-05 22:14:10.089116+00,Əhmədli qəs. Qaçaq Nəbi küçəsi 3 otaga duzelm...,2 200 AZN/m²,220000.0,AZN,Dürdanə,vasitəçi (agent),Elite Ofis,Daşınmaz əmlak agentliyi,Qaçaq Nəbi küç.,40.390550,49.957675,yeniləndi: 04 oktyabr 2024,240,04.10.2024,NaN,d71cf9a9-86dd-4162-b540-6252a8659a09,NaN,Yeni tikili,15 / 16,3.0,100 m²,NaN,var,var,NaN,d71cf9a9-86dd-4162-b540-6252a8659a09,/items/4638863,Əhmədli m.* Xalqlar Dostluğu m.* Xətai r.* Əhm...

Numerical summary:

,price,total_price,lat,lng,views,Otaq sayı
count,1.007750e+05,1.007750e+05,100775.000000,100775.000000,100775.000000,91363.000000
mean,3.423557e+05,3.423553e+05,40.410846,49.886371,700.065185,3.133468
std,2.042627e+06,2.042627e+06,0.083193,0.265008,1680.672574,1.372981
min,1.100000e+01,1.100000e+01,32.689217,12.591688,23.000000,1.000000
25%,1.450000e+05,1.450000e+05,40.381900,49.816470,99.000000,2.000000
50%,2.180000e+05,2.180000e+05,40.397219,49.852867,254.000000,3.000000
75%,3.380000e+05,3.380000e+05,40.420578,49.948995,680.000000,4.000000
max,6.000000e+08,6.000000e+08,41.774687,50.341059,113458.000000,20.000000

======================================================================
2.2 PRICE VS TOTAL_PRICE
======================================================================
Percentage of rows where price == total_price: 0.9998709997519226

Difference between price and total_price:

count    100775.000000
mean          0.470355
std          71.974174
min       -1600.000000
25%           0.000000
50%           0.000000
75%           0.000000
max       20000.000000
dtype: float64

======================================================================
2.3 _X / _Y COLUMN CHECK
======================================================================
id_x vs id_y: 0.00% identical
estate_rel_url_x vs estate_rel_url_y: 100.00% identical
datetime_scrape_x vs datetime_scrape_y: 0.00% identical
currency_x vs currency_y: 100.00% identical
estate_details_id_x vs estate_details_id_y: 100.00% identical
estate_rel_url_x vs estate_rel_url: 100.00% identical

======================================================================
2.4 EXTREME PRICE VALUES
======================================================================
Prices below 1,000 AZN:

,price,location,attributes,Sahə,Otaq sayı
8321,800.0,Zirə q.,2500 sot,2500 sot,NaN
11322,400.0,Saray q.,"2 otaqlı, 86 m², 7/14 mərtəbə",86 m²,2.0
12256,999.0,Memar Əcəmi m.,"3 otaqlı, 133 m², 9/16 mərtəbə",133 m²,3.0
15608,400.0,Saray q.,"2 otaqlı, 86 m², 7/14 mərtəbə",86 m²,2.0
16148,999.0,Memar Əcəmi m.,"3 otaqlı, 133 m², 9/16 mərtəbə",133 m²,3.0
21745,250.0,Əhmədli m.,"2 otaqlı, 30 m²",30 m²,2.0
22304,73.0,Məmmədli q.,"3 otaqlı, 90 m², 1/1 mərtəbə",90 m²,3.0
38666,11.0,Ağ şəhər q.,89 m²,89 m²,NaN
39396,700.0,Nərimanov r.,"2 otaqlı, 65 m², 2/5 mərtəbə",65 m²,2.0
39775,127.0,Sahil q.,"5 otaqlı, 150 m²",150 m²,5.0

Prices above 10 million AZN:

,price,location,attributes,Sahə,Otaq sayı
2704,20000000.0,Həzi Aslanov m.,4300 m²,4300 m²,NaN
2855,13500000.0,Nəriman Nərimanov m.,600 sot,600 sot,NaN
2922,15000000.0,Ulduz m.,160 sot,160 sot,NaN
2942,15000000.0,Nəriman Nərimanov m.,450 sot,450 sot,NaN
6151,25000000.0,Ağ şəhər q.,200 sot,200 sot,NaN
6605,600000000.0,Nəriman Nərimanov m.,"6 otaqlı, 200 m², 7/9 mərtəbə",200 m²,6.0
6942,60000000.0,5-ci mikrorayon q.,"7 otaqlı, 50 m², 6/9 mərtəbə",50 m²,7.0
7639,11000000.0,Gənclik m.,3800 m²,3800 m²,NaN
8065,36000000.0,Ağ şəhər q.,3000 m²,3000 m²,NaN
9096,18500000.0,Sahil m.,116 m²,116 m²,NaN
13410,13000000.0,Ulduz m.,130 sot,130 sot,NaN
14281,18500000.0,Sahil m.,116 m²,116 m²,NaN
16879,13000000.0,Ulduz m.,130 sot,130 sot,NaN
23563,25000000.0,Ağ şəhər q.,200 sot,200 sot,NaN
24188,13500000.0,Nəriman Nərimanov m.,600 sot,600 sot,NaN
27940,13500000.0,Nəriman Nərimanov m.,600 sot,600 sot,NaN
28984,17000000.0,8 Noyabr m.,100 sot,100 sot,NaN
28995,19000000.0,Binəqədi r.,60000 sot,60000 sot,NaN
30193,17500000.0,8 Noyabr m.,3500 m²,3500 m²,NaN
30194,17500000.0,8 Noyabr m.,65 sot,65 sot,NaN

Below 1,000 AZN: 10
Above 10 million AZN: 101

======================================================================
2.5 REPEATED PROPERTY LISTINGS
======================================================================
Duplicate estate IDs: 0
Duplicate property URLs: 36321

Most repeated property URL:
/items/4582627

,estate_rel_url,estate_id,price,Sahə,Otaq sayı,location
267,/items/4582627,33bd12e6-cb08-4c6e-8542-ef95bba99f79,148000.0,70 m²,3.0,20 Yanvar m.
6852,/items/4582627,ee281c6f-9b0f-4969-85c9-2ec1d43e9e86,148000.0,70 m²,3.0,20 Yanvar m.
10284,/items/4582627,7f6a797b-8717-4deb-b05a-1e0e27de3b18,148000.0,70 m²,3.0,20 Yanvar m.
14933,/items/4582627,c3b239f8-5cb7-4a09-971d-00135a5b8cfd,148000.0,70 m²,3.0,20 Yanvar m.
21054,/items/4582627,1f798d94-8a03-42c9-a4b9-19fbc5c897d9,148000.0,70 m²,3.0,20 Yanvar m.
29189,/items/4582627,d9e3e646-88a4-4b9c-8082-618c6171988f,148000.0,70 m²,3.0,20 Yanvar m.
41446,/items/4582627,460737ba-22e1-410a-97b4-13258224e3d3,148000.0,70 m²,3.0,20 Yanvar m.
47869,/items/4582627,6feef4cd-bd86-44de-9a82-7cb48d6ca021,148000.0,70 m²,3.0,20 Yanvar m.
55741,/items/4582627,1d1bfad0-4310-4016-b713-e221015ab9df,148000.0,70 m²,3.0,20 Yanvar m.
56791,/items/4582627,6a941b52-42f5-4ad9-8d74-98018f08a81b,145000.0,70 m²,3.0,20 Yanvar m.
61241,/items/4582627,403db140-9a19-4bbe-87ad-ac31443b020d,145000.0,70 m²,3.0,20 Yanvar m.
74404,/items/4582627,b8c4b372-9fee-4a38-a85b-f4db86350df6,145000.0,70 m²,3.0,20 Yanvar m.
79562,/items/4582627,497468e3-23f2-44ad-8169-230605a4685e,145000.0,70 m²,3.0,20 Yanvar m.
87504,/items/4582627,74b7a44d-8459-420f-86ff-a7a48a52f8df,145000.0,70 m²,3.0,20 Yanvar m.
90710,/items/4582627,3821cb9c-7265-46a6-a4f6-4a3570525449,145000.0,70 m²,3.0,20 Yanvar m.
94318,/items/4582627,27498a67-6f7d-4d5b-99b3-6fc6002510f0,145000.0,70 m²,3.0,20 Yanvar m.
96414,/items/4582627,fb93c483-f866-42ce-b362-d4dc70512791,145000.0,70 m²,3.0,20 Yanvar m.

Scraping dates for repeated property:

,estate_rel_url,estate_id,price,datetime_scrape_x,datetime_scrape_y
267,/items/4582627,33bd12e6-cb08-4c6e-8542-ef95bba99f79,148000.0,2024-10-05 22:07:37.60613+00,2024-10-05 22:14:10.089116+00
6852,/items/4582627,ee281c6f-9b0f-4969-85c9-2ec1d43e9e86,148000.0,2024-10-08 07:32:19.961753+00,2024-10-08 07:35:53.717949+00
10284,/items/4582627,7f6a797b-8717-4deb-b05a-1e0e27de3b18,148000.0,2024-10-09 04:58:40.151251+00,2024-10-09 05:02:29.349209+00
14933,/items/4582627,c3b239f8-5cb7-4a09-971d-00135a5b8cfd,148000.0,2024-10-09 22:00:47.854254+00,2024-10-09 22:05:18.232268+00
21054,/items/4582627,1f798d94-8a03-42c9-a4b9-19fbc5c897d9,148000.0,2024-10-12 05:50:17.512957+00,2024-10-12 05:53:49.164398+00
29189,/items/4582627,d9e3e646-88a4-4b9c-8082-618c6171988f,148000.0,2024-10-13 20:58:00.666852+00,2024-10-13 21:02:02.025003+00
41446,/items/4582627,460737ba-22e1-410a-97b4-13258224e3d3,148000.0,2024-10-17 23:53:36.973072+00,2024-10-17 23:58:16.367958+00
47869,/items/4582627,6feef4cd-bd86-44de-9a82-7cb48d6ca021,148000.0,2024-10-19 22:03:55.353416+00,2024-10-19 22:07:51.907099+00
55741,/items/4582627,1d1bfad0-4310-4016-b713-e221015ab9df,148000.0,2024-10-21 20:44:09.129440,2024-10-21 20:49:37.939165
56791,/items/4582627,6a941b52-42f5-4ad9-8d74-98018f08a81b,145000.0,2024-10-29 20:44:40.173239,2024-10-29 21:02:34.033173
61241,/items/4582627,403db140-9a19-4bbe-87ad-ac31443b020d,145000.0,2024-10-31 20:46:56.927922,2024-10-31 20:51:38.871497
74404,/items/4582627,b8c4b372-9fee-4a38-a85b-f4db86350df6,145000.0,2024-11-04 20:51:51.095865,2024-11-04 20:56:46.962654
79562,/items/4582627,497468e3-23f2-44ad-8169-230605a4685e,145000.0,2024-11-06 20:44:37.839806,2024-11-06 20:48:54.299689
87504,/items/4582627,74b7a44d-8459-420f-86ff-a7a48a52f8df,145000.0,2024-11-09 20:45:46.632914,2024-11-09 20:50:03.404512
90710,/items/4582627,3821cb9c-7265-46a6-a4f6-4a3570525449,145000.0,2024-11-12 20:43:10.396293,2024-11-12 20:46:36.658788
94318,/items/4582627,27498a67-6f7d-4d5b-99b3-6fc6002510f0,145000.0,2024-11-14 20:44:11.397519,2024-11-14 20:48:13.495427
96414,/items/4582627,fb93c483-f866-42ce-b362-d4dc70512791,145000.0,2024-11-17 20:45:02.902614,2024-11-17 20:48:07.997506

Properties appearing more than once: 20506
Maximum appearances of one property: 17

Properties with different prices: 3356
Properties with the same price: 61098

Rows belonging to repeated properties: 56827
Unique properties: 64454
Rows if one row per property were kept: 64454

======================================================================
2.6 UNIT_PRICE
======================================================================
['3 450 AZN/m²', '2 200 AZN/m²', '5 000 AZN/m²', '3 700 AZN/m²', '1 820 AZN/m²', '2 520 AZN/m²', '1 800 AZN/m²', '2 060 AZN/m²', '3 480 AZN/m²', '2 140 AZN/m²', '1 070 AZN/m²', '2 020 AZN/m²', '3 340 AZN/m²', '1 250 AZN/m²', '1 210 AZN/m²', '1 740 AZN/m²', '2 290 AZN/m²', '2 620 AZN/m²', '1 900 AZN/m²', '2 030 AZN/m²']

Random examples:
['2 450 AZN/m²', '1 930 AZN/m²', '4 800 AZN/m²', '3 120 AZN/m²', '2 450 AZN/m²', '2 320 AZN/m²', '2 040 AZN/m²', '2 650 AZN/m²', '3 040 AZN/m²', '1 670 AZN/m²', '2 460 AZN/m²', '2 150 AZN/m²', '2 460 AZN/m²', '1 930 AZN/m²', '1 850 AZN/m²', '2 500 AZN/m²', '3 000 AZN/m²', '2 420 AZN/m²', '3 200 AZN/m²', '3 520 AZN/m²']

======================================================================
2.7 CREATE WORKING DATAFRAME
======================================================================
Shape after removing leakage/redundant identifier columns: (100775, 39)

Remaining columns:
['estate_rel_url_x', 'datetime_scrape_x', 'price', 'currency_x', 'location', 'attributes', 'city_when', 'city', 'day_x', 'hour_x', 'repair', 'vip', 'featured', 'products_label', 'bill_of_sale', 'mortgage', 'description', 'owner_name', 'owner_title', 'shop_name', 'shop_title', 'address', 'lat', 'lng', 'updated', 'views', 'day_y', 'hour_y', 'Binanın növü', 'Kateqoriya', 'Mərtəbə', 'Otaq sayı', 'Sahə', 'Torpaq sahəsi', 'Təmir', 'Çıxarış', 'İpoteka', 'estate_rel_url', 'extra_info']

======================================================================
2.8 MISSING VALUE ANALYSIS
======================================================================
Missing values (%):

Binanın növü         99.847184
featured             96.875217
vip                  91.470107
Torpaq sahəsi        84.548747
hour_y               84.489209
İpoteka              67.314314
mortgage             67.314314
shop_title           28.535847
shop_name            28.535847
products_label       27.928554
Mərtəbə              24.588440
bill_of_sale         21.046887
repair               19.015629
Otaq sayı             9.339618
Təmir                 5.954850
owner_name            0.651947
owner_title           0.651947
description           0.262962
location              0.000000
price                 0.000000
datetime_scrape_x     0.000000
estate_rel_url_x      0.000000
currency_x            0.000000
city_when             0.000000
attributes            0.000000
lat                   0.000000
day_x                 0.000000
hour_x                0.000000
address               0.000000
city                  0.000000
lng                   0.000000
Kateqoriya            0.000000
updated               0.000000
views                 0.000000
day_y                 0.000000
Sahə                  0.000000
Çıxarış               0.000000
estate_rel_url        0.000000
extra_info            0.000000
dtype: float64

======================================================================
2.9 HIGH MISSINGNESS FEATURES
======================================================================
Features with more than 80% missing values:
['Binanın növü', 'featured', 'vip', 'Torpaq sahəsi', 'hour_y']

Shape after removing highly incomplete features: (100775, 34)

======================================================================
2.10 DUPLICATE CATEGORICAL FEATURES
======================================================================
repair vs Təmir: 0.0595484991317291

repair vs Təmir crosstab:

Təmir        __MISSING__    var  yoxdur
repair
Təmirli                0  81612       0
__MISSING__         6001      0   13162

mortgage vs İpoteka: 0.6731431406598859

mortgage vs İpoteka crosstab:

İpoteka      __MISSING__    var
mortgage
__MISSING__        67836      0
İpoteka var            0  32939

bill_of_sale vs Çıxarış: 0.0

bill_of_sale vs Çıxarış crosstab:

Çıxarış         var  yoxdur
bill_of_sale
__MISSING__       0   21210
Çıxarış var   79565       0

Shape after removing redundant categorical columns: (100775, 31)

======================================================================
2.11 REMAINING MISSING VALUES
======================================================================

İpoteka           67.314314
shop_title        28.535847
shop_name         28.535847
products_label    27.928554
Mərtəbə           24.588440
Otaq sayı          9.339618
Təmir              5.954850
owner_title        0.651947
owner_name         0.651947
description        0.262962
dtype: float64

======================================================================
2.12 INSPECT REMAINING MISSING VALUES
======================================================================

===== products_label =====

products_label
Agentlik    71981
NaN         28145
Kompleks      649
Name: count, dtype: int64

===== description =====

description
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               265
"Knightsbridge Residence" premium yaşayış kompleksində limitli sayda olan tam təmirli mənzillərin satışına start verildi!\n74-146 kv.m aralığında sahəyə malik 2, 3 və 4 otaqlı tam təmirli mənzilləri 25% ilkin ödəniş və 60 ayadək daxili kredit şərtləri ilə, həmçinin 20 ilədək ipoteka ilə əldə etmək mümkündür.Tam təmirli mənzil dedikdə nəyi nəzərdə tuturuq?\n* Neoklassik üslubda yüksək keyfiyyətli materialların istifadəsi ilə tam təmir edilmiş\n* Yaşayış üçün tam hazır\n* Mətbəx də daxil olmaqla, hər bir otağı mebel, aksesuar, dekor əşyaları ilə təmin edilmiş\n* Böyük məişət texnikası quraşdırılmış\n* Bütün zəruri elektrik, telefon, internet və televiziya xətləri ilə təchiz olunmuşOtaqların hamısı dünyaca tanınmış brendlərin yüksək keyfiyyətli mebelləri və qabyuyandan tutmuş, paltaryuyan, soyuducu və saç feninədək ən keyfiyyətli məişət texnikası ilə təmin edilmişdir ki, ilk gündən “Knightsbridge” həyat tərzini və keyfiyyət standartını hiss edəsiniz.Burada xalçalar, pərdələr, şamlar, hətta şkafınızdakı taxta asılqanlaradək hər bir detal diqqətlə seçilmişdir və sizə yalnız yeni evinizdən zövq almaq qalır.Ətraflı məlumat və mənzillərə baxış üçün *2023 və ya *2024 nömrəmizə zəng edə və ya Ağ Şəhərdə, 8 Noyabr prospekti, 151 ünvanında yerləşən “Knightsbridge Residence” satış ofisimizə (Nizami Parkı ilə üzbəüz) yaxınlaşa bilərsiniz.\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               56
"Grand Plaza" Koroğlu və Zorge parkları ilə əhatə olunan yaşıllıq ərazidə yerləşən,otel üslublu,premium yaşayış kompleksidir.Kompleks Dədə Qorqud parkı və ADA Universitetindən 3 dəqiqəlik, Nəsimi Rayon İcra Hakimiyyəti və Heydər Əliyev adına Müasir Təhsil Kompleksindən isə 2 dəqiqəlik piyada yol məsafəsində inşa edilir.\n \nÜstünlüklərimiz:•​3,6 metr hündürlüyündə tavan\n•​Sərbəst layihələndirmə\n•​ABŞ istehsalı,sürətli “OTİS”liftləri\n•​“TEXNONİKOL” şirkətinə məxsus izolyasiya sistemləri\n•​B30 markalı beton\n•​A500C markalı armatur​\n•​Keramoqranit ilə işlənmiş fasad\n•​Alman istehsalı “SCHÜCO” pəncərə sistemləri\n•​Türkiyə istehsalı lyüks seyf qapılar\n•​Odadavamlı işıq kabelləri\n•​9+ ballıq seysmik davamlılıq\n•​Qranit pilləkənlər\n•​Mərkəzləşdirilmiş su filtrasiya sistemi\n•​Mərkəzləşdirilmiş yanğın əleyhinə sistem\n•​Şəhərə açılan gözəl mənzərə \n•​Ehtiyat generator sistemi\n•​Yaşıl parklar ərazisində yerləşmə\n•​Ekoloji cəhətdən təmiz ərazi\n•​Uşaqlar üçün oyun meydançası\n•​Qonaqların qarşılanması üçün lobbi\n•​Sakinlər üçün 2 mərtəbəli parkinq\n•​Qonaqlar üçün xüsusi parkinq\n•​4600 m2 sahəli həyət\n•​Avtoyuma xidməti \n•​Şəhərin əsas yollarına birbaşa çıxış\n•​Yüksək sürətli internet və kabel televiziyası\n•​7/24 mühafizə xidməti və video nəzarət\n•​Konsyerj xidmətiÖdəniş şərtlərinə görə qiymətlər:• Faizsiz daxili kreditlə: ilkin ödəniş 50 % / 3 ay daxili kredit.\n• 20 illik ipoteka krediti / ilkin ödəniş 20 % (illik 6-11%)Tam nağd ödəniş zamanı əlavə endirim tətbiq olunur.Mənzillərimiz təmirsizdir.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    39
“Baku City Residence Khatai” dünyaca məşhur “ Bakı Ağ Şəhər”də yerləşən müasir yönümlü, möhtəşəm dəniz mənzərəsi və rahat infrastruktur təqdim edən yaşayış kompleksidir.Daxili infrastruktur:\n• LANDAU Preschool\n• World Class fitness mərkəz\n• Qapalı Olimpiya hovuzu\n• World Class SPA\n• Rossman\n• Dünya brend restoran və “coffee shop”-lar\n• Ağıllı Yaşayış Kompleksi\n• Konsyerj\n• 24/7 canlı mühafizə və video-müşahidə\n• Gastronom7300 kvadrat metrlik Qapalı Həyət:\n• Uşaq meydançası\n• Velosiped zolağı\n• Futbol meydançası\n• Ağıllı kompleks sistemi( Üz tanıma sistemi; QR code)894 yerlik, 3 mərtəbəli yeraltı Avtodayanacaq:\n• Elektromobillər üçün dolum məntəqələri\n• Avto yuma• Liftlər: 3 “KONE” markalı 2 ədəd sərnişin və 1 ədəd yük lifti\n• Fasad: ventilyasiya olunan keramoqranit üzlüklü fasad, 3 qat şüşəli izosistemli alüminium vitraj pəncərələr, məsaməli hörgü blokları və hazır qəlib sistemi• Mənzil nağd, hissəli ödəniş və ya ipoteka şərtləri ilə təklif edilir.\nHissəli ödəniş və ipoteka:OFİSİN XİDMƏT HAQQİ 1%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              32
YENİ HAYAT - PARK AZURE Residence yaşayış kompleksində əla təmirli gözəl mənzil satılır. —————————————-Kompleksdə xidmətə daxildir:\nYaşıl park , trenajorlar və uşaq əyləncə yeri\nFutbol meydançası\nLiftlər\nResepşn\nMuhafizə 7/24 \nElektrik.   \nSantexnik\nXadimə\nZibillərin mərtəbədən daşınması\n————————————-\nƏlavə ödənişli xidmətlər ;\nVip restoranlar \n(Kfc, Friday, Məclis, Nəlbəki, Nani, Lavaş)\nUşaq baxçası\nBravo Market\nFitness\nBaseyn\nGözəllik salonu\nAtelye\nAptek\nParking\nAvtoyuma\nQuru Təmizləmə\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              31
Nizami City Yaşayış Kompleksinin qeyri-yaşayış sahələrinin satışı və icarəsi mümkündür. Kompleks Nizami mts.-nın yaxınlığı, 3cü və 5ci paralellər arasında yerləşir. Qiymətlər obyektlərin yerləşmə mərtəbəsi və baxış küçəsinə görə dəyişir. Ölçülər istənilən qədər artırıla bilər. Ətraflı məlumat üçün satış ofisinə yaxınlaşmağınız kifayətdir.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               24
"Nizami City" –nin 1ci ABC mərhələsi hazırdır, 2ci mərhələsi- EFG binalarında satışı davam edir. 9 binadan ibarət kompleks Nizami mt.s-nın yaxınlığındadır. 9 yaşayış mərtəbəsi, qapalı həyət və keramoqranit fasada malik kompleksdə sakinlərin rahatçılığı üçün hər bir detal düşünülmüşdür. Siz də kompleksdən mənzil əldə etmək istəyirsinizsə satış ofisinə yaxınlaşmağınız kifayətdir.Qiymətlər yeni mərhələdə 1kvm üçün 2500-3200AZN arasında dəyişir, 24 ayadək daxili kredit imkanları var.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               21
"Nizami City" –nin 1ci ABC mərhələsi hazırdır, 2ci mərhələsi- EFG binalarında satışı davam edir. 9 binadan ibarət kompleks Nizami mt.s-nın yaxınlığındadır. 9 yaşayış mərtəbəsi, qapalı həyət və keramoqranit fasada malik kompleksdə sakinlərin rahatçılığı üçün hər bir detal düşünülmüşdür. Siz də kompleksdən mənzil əldə etmək istəyirsinizsə satış ofisinə yaxınlaşmağınız kifayətdir.Qiymətlər yeni mərhələdə 1kvm üçün 2400-2800 AZN arasında dəyişir, 36 ayadək daxili kredit imkanları var.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              20
Daxili kredit ilə satış var - ilkin ödəniş 50%, 36 ay müddətinə təklif edilir.Şəhərin mərkəzinə yaxınlıq və səs-küyündən uzaqlıq. Pəncərədən Xəzər dənizinin görüntüsü. 12 sot daşma hovuzlu, qonşu mənzildən görüntüyə qapalı, yaşıl və geniş həyət. Təmiz hava. Müasir dizayna malik eksteryer və interyer. Hündür tavanlar.\nVillanın yaşayış sahəsi 350, terrası 150 kv.m-dir. Ödənişə daxil edilməyən yaşıllıq sahəsinin ərazisi isə 550 kv.m-dir. 5 otaq, 3 sanqovşağı var.\nVilla yaşayış üçün hər cür şəraitlə təmin edilib: qapalı həyət, supermarket, mərkəzi elektrik təchizatı, mərkəzləşdirilmiş yanğın əleyhinə sistem, ehtiyat generatorlar sistemi, uşaq meydançaları, IP domofon sistemi, 7/24 su təchizatı, açıq havada idman meydançası, kafe və restoranlar, 7/24 mühafizə və videomüşahidə, yüksəksürətli internet, kabel TV.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 20

===== owner_name =====

owner_name
Elan sahibi                1618
Rauf                       1136
Samir                      1050
Real Əmlak                  895
Murad                       890
Penthouse Estate Agency     781
NaN                         657
Elçin                       637
İlkin                       544
Anar                        538
Name: count, dtype: int64

===== owner_title =====

owner_title
vasitəçi (agent)    89733
mülkiyyətçi         10385
NaN                   657
Name: count, dtype: int64

===== shop_name =====

shop_name
NaN                               28757
Real Əmlak Yeni Yasamal            2482
EVA Group "Röyal Əmlak"            1936
Real Əmlak Nərimanov               1514
My Dom                             1470
EVA Group "Platin Real Estate"     1376
Real Əmlak Bakı                    1326
Bakı Əmlak Qarayev                 1082
VİP House Xətai                    1071
Global House                       1011
Name: count, dtype: int64

===== shop_title =====

shop_title
Daşınmaz əmlak agentliyi    72018
NaN                         28757
Name: count, dtype: int64

===== Mərtəbə =====

Mərtəbə
NaN        24779
5 / 5       1989
3 / 5       1764
2 / 5       1761
4 / 5       1680
8 / 9       1369
7 / 9       1067
9 / 9       1032
16 / 17     1014
6 / 9       1007
Name: count, dtype: int64

===== Otaq sayı =====

Otaq sayı
3.0     36191
2.0     27435
4.0     15673
NaN      9412
5.0      4850
1.0      2618
6.0      2306
7.0       978
8.0       582
10.0      247
Name: count, dtype: int64

===== Təmir =====

Təmir
var       81612
yoxdur    13162
NaN        6001
Name: count, dtype: int64

===== İpoteka =====

İpoteka
NaN    67836
var    32939
Name: count, dtype: int64

======================================================================
2.13 AREA UNIT ANALYSIS
======================================================================
area_unit
m²     95856
sot     4919
Name: count, dtype: int64

======================================================================
2.14 MISSING ROOM COUNTS
======================================================================
Room counts:

Otaq sayı
1.0      2618
2.0     27435
3.0     36191
4.0     15673
5.0      4850
6.0      2306
7.0       978
8.0       582
9.0       241
10.0      247
11.0       43
12.0       87
13.0       10
14.0       20
15.0       35
16.0       19
18.0        4
19.0        5
20.0       19
NaN      9412
Name: count, dtype: int64

Missing room counts by area unit:

area_unit
m²     4493
sot    4919
Name: Otaq sayı, dtype: int64

Missing room count for m² listings:

         price      Sahə               location   Təmir İpoteka
3      95000.0    130 m²           Qaraçuxur q.     var     var
8    3000000.0    485 m²              Nizami m.     var     NaN
10   1050000.0    360 m²             Masazır q.     NaN     NaN
11    275000.0     45 m²        Qara Qarayev m.     var     var
18    260000.0     70 m²              28 May m.  yoxdur     NaN
28    170000.0     45 m²       Köhnə Günəşli q.     var     NaN
34     23000.0    380 m²           Nərimanov r.  yoxdur     NaN
37    580000.0    100 m²             Əhmədli m.     var     NaN
39    600000.0    250 m²       Köhnə Günəşli q.     var     NaN
120   850000.0    150 m²   Şah İsmayıl Xətai m.     var     NaN
140   580000.0    120 m²         Memar Əcəmi m.     var     NaN
143  1650000.0    400 m²        Həzi Aslanov m.     var     NaN
144  2500000.0   1450 m²           Neftçilər m.     var     NaN
145   275000.0     55 m²              Nəsimi m.     var     NaN
222   153000.0     12 m²   Nəriman Nərimanov m.     var     var
306   179000.0    108 m²    Xalqlar Dostluğu m.     var     var
328   550000.0     83 m²  Elmlər Akademiyası m.     var     NaN
329   145000.0    200 m²             Görədil q.     var     NaN
364  1600000.0   1600 m²                Qala q.     NaN     NaN
372   650000.0    110 m²            Mərdəkan q.     var     NaN
394   125000.0   19.5 m²            Ağ şəhər q.     var     NaN
395  1400000.0    600 m²            Mərdəkan q.     NaN     NaN
411   320000.0     55 m²              Nizami m.     var     NaN
414  5000000.0    435 m²               Sahil m.     var     NaN
418   970000.0    134 m²           Nərimanov r.     var     NaN
420  1500000.0  158.5 m²              Nizami m.     var     NaN
422   750000.0    361 m²            Badamdar q.     var     NaN
424  1200000.0    115 m²           Nərimanov r.     var     NaN
426   230000.0     50 m²        Həzi Aslanov m.     var     NaN
433   600000.0    100 m²              Nizami m.     var     NaN

======================================================================
2.15 AREA NUMERICAL FEATURES
======================================================================

      Sahə area_unit  area_value  area_m2
0   145 m²        m²       145.0    145.0
1    90 m²        m²        90.0     90.0
2    60 m²        m²        60.0     60.0
3   130 m²        m²       130.0    130.0
4   100 m²        m²       100.0    100.0
5   130 m²        m²       130.0    130.0
6    70 m²        m²        70.0     70.0
7   153 m²        m²       153.0    153.0
8   485 m²        m²       485.0    485.0
9   104 m²        m²       104.0    104.0
10  360 m²        m²       360.0    360.0
11   45 m²        m²        45.0     45.0
12   85 m²        m²        85.0     85.0
13  940 m²        m²       940.0    940.0
14  160 m²        m²       160.0    160.0
15   56 m²        m²        56.0     56.0
16   70 m²        m²        70.0     70.0
17   72 m²        m²        72.0     72.0
18   70 m²        m²        70.0     70.0
19  225 m²        m²       225.0    225.0

======================================================================
2.16 MISSING CATEGORICAL VALUES
======================================================================

===== İpoteka =====
Missing: 67836
Missing %: 67.31

===== Təmir =====
Missing: 6001
Missing %: 5.95

===== Otaq sayı =====
Missing: 9412
Missing %: 9.34

===== products_label =====
Missing: 28145
Missing %: 27.93

======================================================================
2.17 TARGET DISTRIBUTION BY MISSINGNESS
======================================================================

===== İpoteka =====
Price when value is missing:

count    6.783600e+04
mean     3.504351e+05
std      2.436309e+06
min      1.100000e+01
25%      1.370000e+05
50%      2.150000e+05
75%      3.400000e+05
max      6.000000e+08
Name: price, dtype: float64

Price when value is not missing:

count    3.293900e+04
mean     3.257168e+05
std      7.352607e+05
min      1.700000e+03
25%      1.550000e+05
50%      2.230000e+05
75%      3.350000e+05
max      3.600000e+07
Name: price, dtype: float64

===== Təmir =====
Price when value is missing:

count    6.001000e+03
mean     8.031405e+05
std      8.066663e+06
min      8.000000e+02
25%      5.900000e+04
50%      1.700000e+05
75%      4.200000e+05
max      6.000000e+08
Name: price, dtype: float64

Price when value is not missing:

count    9.477400e+04
mean     3.131793e+05
std      5.501124e+05
min      1.100000e+01
25%      1.470000e+05
50%      2.200000e+05
75%      3.350000e+05
max      3.600000e+07
Name: price, dtype: float64

===== Otaq sayı =====
Price when value is missing:

count    9.412000e+03
mean     9.465962e+05
std      2.236948e+06
min      1.100000e+01
25%      9.900000e+04
50%      2.950000e+05
75%      8.000000e+05
max      4.000000e+07
Name: price, dtype: float64

Price when value is not missing:

count    9.136300e+04
mean     2.801083e+05
std      2.011273e+06
min      7.300000e+01
25%      1.450000e+05
50%      2.150000e+05
75%      3.220250e+05
max      6.000000e+08
Name: price, dtype: float64

===== products_label =====
Price when value is missing:

count    2.814500e+04
mean     3.136199e+05
std      3.662944e+06
min      1.100000e+01
25%      1.050000e+05
50%      1.670000e+05
75%      2.800000e+05
max      6.000000e+08
Name: price, dtype: float64

Price when value is not missing:

count    7.263000e+04
mean     3.534912e+05
std      7.678085e+05
min      4.000000e+02
25%      1.600000e+05
50%      2.350000e+05
75%      3.500000e+05
max      3.900000e+07
Name: price, dtype: float64

======================================================================
2.18 MORTGAGE ANALYSIS
======================================================================
İpoteka
NaN    67836
var    32939
Name: count, dtype: int64

Mortgage = var:

       price    Sahə              location  Otaq sayı Təmir
3    95000.0  130 m²          Qaraçuxur q.        NaN   var
11  275000.0   45 m²       Qara Qarayev m.        NaN   var
14  330000.0  160 m²  Nəriman Nərimanov m.        3.0   var
15  195000.0   56 m²           8 Noyabr m.        2.0   var
19  455000.0  225 m²            Əhmədli m.        5.0   var
27  680000.0  260 m²              Sahil m.        4.0   var
32  135000.0  100 m²            Görədil q.        4.0   var
36  143000.0   65 m²        Memar Əcəmi m.        2.0   var
38  133000.0   52 m²             Nəsimi m.        2.0   var
40  282000.0  140 m²             Nəsimi m.        3.0   var
41  158000.0   78 m²             Nəsimi m.        2.0   var
42  161000.0   78 m²        Memar Əcəmi m.        2.0   var
43  155000.0   68 m²             Nəsimi m.        2.0   var
44  164000.0   65 m²             Nəsimi m.        3.0   var
46  170000.0   60 m²        Memar Əcəmi m.        2.0   var
47  270000.0  130 m²             Nəsimi m.        3.0   var
49  125000.0   70 m²             Nəsimi m.        2.0   var
50  142000.0   60 m²        Memar Əcəmi m.        2.0   var
52  280000.0  126 m²       Həzi Aslanov m.        3.0   var
53  270000.0   95 m²  Nəriman Nərimanov m.        3.0   var

Mortgage = missing:

        price      Sahə               location  Otaq sayı   Təmir
0    499999.0    145 m²              Səbail r.        4.0     var
1     77000.0     90 m²            Biləcəri q.        4.0     var
2     92000.0     60 m²         İnşaatçılar m.        3.0     var
4    220000.0    100 m²             Əhmədli m.        3.0     var
5    650000.0    130 m²               Sahil m.        4.0     var
6    259000.0     70 m²               Sahil m.        3.0     var
7    279000.0    153 m²               Bayıl q.        3.0  yoxdur
8   3000000.0    485 m²              Nizami m.        NaN     var
9    262000.0    104 m²         Memar Əcəmi m.        3.0     var
10  1050000.0    360 m²             Masazır q.        NaN     NaN
12   153000.0     85 m²         İnşaatçılar m.        4.0     var
13   450000.0    940 m²             Novxanı q.        9.0  yoxdur
16   150000.0     70 m²           Neftçilər m.        3.0     var
17    77000.0     72 m²             Masazır q.        3.0     var
18   260000.0     70 m²              28 May m.        NaN  yoxdur
20   770000.0  230.6 m²  Elmlər Akademiyası m.        5.0  yoxdur
21   150000.0    120 m²             Masazır q.        3.0     var
22    55000.0    12 sot                Binə q.        NaN     NaN
23    65500.0     54 m²             Masazır q.        2.0     var
24   143000.0   82.2 m²        Həzi Aslanov m.        2.0  yoxdur

======================================================================
2.19 PRODUCTS_LABEL ANALYSIS
======================================================================
products_label
Agentlik    71981
NaN         28145
Kompleks      649
Name: count, dtype: int64

Products_label = missing:

        price      Sahə               location  Otaq sayı   Təmir İpoteka
0    499999.0    145 m²              Səbail r.        4.0     var     NaN
1     77000.0     90 m²            Biləcəri q.        4.0     var     NaN
2     92000.0     60 m²         İnşaatçılar m.        3.0     var     NaN
3     95000.0    130 m²           Qaraçuxur q.        NaN     var     var
5    650000.0    130 m²               Sahil m.        4.0     var     NaN
6    259000.0     70 m²               Sahil m.        3.0     var     NaN
7    279000.0    153 m²               Bayıl q.        3.0  yoxdur     NaN
8   3000000.0    485 m²              Nizami m.        NaN     var     NaN
10  1050000.0    360 m²             Masazır q.        NaN     NaN     NaN
11   275000.0     45 m²        Qara Qarayev m.        NaN     var     var
13   450000.0    940 m²             Novxanı q.        9.0  yoxdur     NaN
16   150000.0     70 m²           Neftçilər m.        3.0     var     NaN
17    77000.0     72 m²             Masazır q.        3.0     var     NaN
18   260000.0     70 m²              28 May m.        NaN  yoxdur     NaN
19   455000.0    225 m²             Əhmədli m.        5.0     var     var
20   770000.0  230.6 m²  Elmlər Akademiyası m.        5.0  yoxdur     NaN
21   150000.0    120 m²             Masazır q.        3.0     var     NaN
22    55000.0    12 sot                Binə q.        NaN     NaN     NaN
23    65500.0     54 m²             Masazır q.        2.0     var     NaN
24   143000.0   82.2 m²        Həzi Aslanov m.        2.0  yoxdur     NaN

Products_label = available:

       price    Sahə              location  Otaq sayı   Təmir İpoteka
4   220000.0  100 m²            Əhmədli m.        3.0     var     NaN
9   262000.0  104 m²        Memar Əcəmi m.        3.0     var     NaN
12  153000.0   85 m²        İnşaatçılar m.        4.0     var     NaN
14  330000.0  160 m²  Nəriman Nərimanov m.        3.0     var     var
15  195000.0   56 m²           8 Noyabr m.        2.0     var     var
27  680000.0  260 m²              Sahil m.        4.0     var     var
28  170000.0   45 m²      Köhnə Günəşli q.        NaN     var     NaN
29   95000.0   50 m²          Neftçilər m.        2.0     var     NaN
34   23000.0  380 m²          Nərimanov r.        NaN  yoxdur     NaN
36  143000.0   65 m²        Memar Əcəmi m.        2.0     var     var
37  580000.0  100 m²            Əhmədli m.        NaN     var     NaN
38  133000.0   52 m²             Nəsimi m.        2.0     var     var
39  600000.0  250 m²      Köhnə Günəşli q.        NaN     var     NaN
40  282000.0  140 m²             Nəsimi m.        3.0     var     var
41  158000.0   78 m²             Nəsimi m.        2.0     var     var
42  161000.0   78 m²        Memar Əcəmi m.        2.0     var     var
43  155000.0   68 m²             Nəsimi m.        2.0     var     var
44  164000.0   65 m²             Nəsimi m.        3.0     var     var
46  170000.0   60 m²        Memar Əcəmi m.        2.0     var     var
47  270000.0  130 m²             Nəsimi m.        3.0     var     var

Price when products_label is missing:

count    2.814500e+04
mean     3.136199e+05
std      3.662944e+06
min      1.100000e+01
25%      1.050000e+05
50%      1.670000e+05
75%      2.800000e+05
max      6.000000e+08
Name: price, dtype: float64

Price when products_label is not missing:

count    7.263000e+04
mean     3.534912e+05
std      7.678085e+05
min      4.000000e+02
25%      1.600000e+05
50%      2.350000e+05
75%      3.500000e+05
max      3.900000e+07
Name: price, dtype: float64

Price distribution by products_label:

,count,mean,std,min,25%,50%,75%,max
products_label,,,,,,,,
Agentlik,71981.0,351587.072589,7.681455e+05,400.0,160000.0,235000.0,350000.0,39000000.0
Kompleks,649.0,564681.952234,6.984724e+05,65410.0,281248.0,396090.0,624132.0,6800000.0
Missing,28145.0,313619.889039,3.662944e+06,11.0,105000.0,167000.0,280000.0,600000000.0

===== location vs products_label =====

products_label      Agentlik  Kompleks
location
2-ci Alatava q.        1.000     0.000
2-ci mikrorayon q.     1.000     0.000
20 Yanvar m.           0.977     0.023
20-ci sahə q.          1.000     0.000
28 May m.              0.992     0.008
...                      ...       ...
Şərq q.                1.000     0.000
Əhmədli m.             1.000     0.000
Əhmədli q.             1.000     0.000
Ələt q.                1.000     0.000
Əmircan q.             1.000     0.000

[134 rows x 2 columns]

===== Təmir vs products_label =====

products_label  Agentlik  Kompleks
Təmir
var                0.996     0.004
yoxdur             0.958     0.042

===== İpoteka vs products_label =====

products_label  Agentlik  Kompleks
İpoteka
var                0.986     0.014

======================================================================
2.20 CATEGORICAL MISSING VALUE HANDLING
======================================================================

İpoteka:
İpoteka
Missing    67836
var        32939
Name: count, dtype: int64

Təmir:
Təmir
var        81612
yoxdur     13162
Missing     6001
Name: count, dtype: int64

Çıxarış:
Çıxarış
var       79565
yoxdur    21210
Name: count, dtype: int64

products_label:
products_label
Agentlik    71981
Missing     28145
Kompleks      649
Name: count, dtype: int64

======================================================================
2.21 SELLER / AGENCY FEATURES
======================================================================
owner_name       657
owner_title      657
shop_name      28757
shop_title     28757
dtype: int64
Shape after removing seller/agency identifier-like columns: (100775, 31)

======================================================================
2.22 FLOOR FEATURES
======================================================================
Unique Mərtəbə values: 392

0       7 / 9
4     15 / 16
5       3 / 4
6       2 / 5
7      3 / 18
9     11 / 13
12    19 / 20
14     3 / 16
15    10 / 16
16      4 / 5
17      5 / 6
19    12 / 16
20    16 / 18
21      3 / 6
23      5 / 6
24     9 / 16
25      8 / 9
27    13 / 17
29      5 / 5
31     4 / 17
Name: Mərtəbə, dtype: object

    Mərtəbə  floor  total_floors
0     7 / 9    7.0           9.0
1       NaN    NaN           NaN
2       NaN    NaN           NaN
3       NaN    NaN           NaN
4   15 / 16   15.0          16.0
5     3 / 4    3.0           4.0
6     2 / 5    2.0           5.0
7    3 / 18    3.0          18.0
8       NaN    NaN           NaN
9   11 / 13   11.0          13.0
10      NaN    NaN           NaN
11      NaN    NaN           NaN
12  19 / 20   19.0          20.0
13      NaN    NaN           NaN
14   3 / 16    3.0          16.0
15  10 / 16   10.0          16.0
16    4 / 5    4.0           5.0
17    5 / 6    5.0           6.0
18      NaN    NaN           NaN
19  12 / 16   12.0          16.0

======================================================================
2.23 PRICE PER M²
======================================================================

        price    Sahə  area_m2  price_per_m2
0    499999.0  145 m²    145.0   3448.268966
1     77000.0   90 m²     90.0    855.555556
2     92000.0   60 m²     60.0   1533.333333
3     95000.0  130 m²    130.0    730.769231
4    220000.0  100 m²    100.0   2200.000000
5    650000.0  130 m²    130.0   5000.000000
6    259000.0   70 m²     70.0   3700.000000
7    279000.0  153 m²    153.0   1823.529412
8   3000000.0  485 m²    485.0   6185.567010
9    262000.0  104 m²    104.0   2519.230769
10  1050000.0  360 m²    360.0   2916.666667
11   275000.0   45 m²     45.0   6111.111111
12   153000.0   85 m²     85.0   1800.000000
13   450000.0  940 m²    940.0    478.723404
14   330000.0  160 m²    160.0   2062.500000
15   195000.0   56 m²     56.0   3482.142857
16   150000.0   70 m²     70.0   2142.857143
17    77000.0   72 m²     72.0   1069.444444
18   260000.0   70 m²     70.0   3714.285714
19   455000.0  225 m²    225.0   2022.222222

count    1.007750e+05
mean     2.321759e+03
std      1.042945e+04
min      2.500000e-04
1%       4.900000e+01
5%       4.500000e+02
25%      1.675000e+03
50%      2.214286e+03
75%      2.730496e+03
95%      3.827777e+03
99%      6.666667e+03
max      3.000000e+06
Name: price_per_m2, dtype: float64

======================================================================
2.24 EXTREME PRICE PER M² VALUES
======================================================================
Highest price/m² observations:

,price,Sahə,area_unit,area_m2,price_per_m2,location
6605,600000000.0,200 m²,m²,200.0,3.000000e+06,Nəriman Nərimanov m.
6942,60000000.0,50 m²,m²,50.0,1.200000e+06,5-ci mikrorayon q.
12285,380000.0,1 m²,m²,1.0,3.800000e+05,Şüvəlan q.
16168,380000.0,1 m²,m²,1.0,3.800000e+05,Şüvəlan q.
9096,18500000.0,116 m²,m²,116.0,1.594828e+05,Sahil m.
14281,18500000.0,116 m²,m²,116.0,1.594828e+05,Sahil m.
11364,650000.0,9 m²,m²,9.0,7.222222e+04,Azadlıq Prospekti m.
15638,650000.0,9 m²,m²,9.0,7.222222e+04,Azadlıq Prospekti m.
34426,5000000.0,98 m²,m²,98.0,5.102041e+04,Sahil m.
98699,5000000.0,98 m²,m²,98.0,5.102041e+04,Sahil m.
75798,5100000.0,100 m²,m²,100.0,5.100000e+04,Sahil m.
98693,4900000.0,99 m²,m²,99.0,4.949495e+04,Sahil m.
44225,4000000.0,99 m²,m²,99.0,4.040404e+04,Sahil m.
56846,280000.0,7 m²,m²,7.0,4.000000e+04,İçəri Şəhər m.
63000,280000.0,7 m²,m²,7.0,4.000000e+04,İçəri Şəhər m.
1743,1800000.0,48 m²,m²,48.0,3.750000e+04,Səbail r.
6340,1800000.0,48 m²,m²,48.0,3.750000e+04,Səbail r.
11476,1800000.0,48 m²,m²,48.0,3.750000e+04,Səbail r.
18924,1800000.0,48 m²,m²,48.0,3.750000e+04,Səbail r.
75832,1800000.0,48 m²,m²,48.0,3.750000e+04,Səbail r.

Lowest price/m² observations:

         price        Sahə area_unit     area_m2  price_per_m2     location
4736    2500.0  100000 sot       sot  10000000.0      0.000250   Fatmayı q.
9746    2500.0  100000 sot       sot  10000000.0      0.000250   Fatmayı q.
21517   2500.0  100000 sot       sot  10000000.0      0.000250   Fatmayı q.
75857   3000.0  100000 sot       sot  10000000.0      0.000300   Fatmayı q.
8321     800.0    2500 sot       sot    250000.0      0.003200      Zirə q.
3348    3500.0    4000 sot       sot    400000.0      0.008750   Buzovna q.
89280   1000.0     200 sot       sot     20000.0      0.050000     Şıxov q.
75936  30000.0    3500 sot       sot    350000.0      0.085714       Xaçmaz
172    80000.0    7000 sot       sot    700000.0      0.114286   Maştağa q.
38666     11.0       89 m²        m²        89.0      0.123596  Ağ şəhər q.
23304   1950.0     100 sot       sot     10000.0      0.195000    Hövsan q.
35863   1950.0     100 sot       sot     10000.0      0.195000    Hövsan q.
86013   1950.0     100 sot       sot     10000.0      0.195000    Hövsan q.
60613   8500.0     430 sot       sot     43000.0      0.197674   Masazır q.
82625   2100.0     100 sot       sot     10000.0      0.210000   Fatmayı q.
4586    2500.0     100 sot       sot     10000.0      0.250000    Hövsan q.
4155    3500.0     135 sot       sot     13500.0      0.259259  Məmmədli q.
9089    3500.0     135 sot       sot     13500.0      0.259259  Məmmədli q.
14274   3500.0     135 sot       sot     13500.0      0.259259  Məmmədli q.
54814   3000.0     100 sot       sot     10000.0      0.300000     Saray q.

======================================================================
2.25 PRICE PER M² FLAGS
======================================================================
Potentially unusual price/m² observations: 2338

,price,Sahə,area_unit,area_value,area_m2,price_per_m2,location
4736,2500.0,100000 sot,sot,100000.0,10000000.0,0.000250,Fatmayı q.
9746,2500.0,100000 sot,sot,100000.0,10000000.0,0.000250,Fatmayı q.
21517,2500.0,100000 sot,sot,100000.0,10000000.0,0.000250,Fatmayı q.
75857,3000.0,100000 sot,sot,100000.0,10000000.0,0.000300,Fatmayı q.
8321,800.0,2500 sot,sot,2500.0,250000.0,0.003200,Zirə q.
3348,3500.0,4000 sot,sot,4000.0,400000.0,0.008750,Buzovna q.
89280,1000.0,200 sot,sot,200.0,20000.0,0.050000,Şıxov q.
75936,30000.0,3500 sot,sot,3500.0,350000.0,0.085714,Xaçmaz
172,80000.0,7000 sot,sot,7000.0,700000.0,0.114286,Maştağa q.
38666,11.0,89 m²,m²,89.0,89.0,0.123596,Ağ şəhər q.
23304,1950.0,100 sot,sot,100.0,10000.0,0.195000,Hövsan q.
35863,1950.0,100 sot,sot,100.0,10000.0,0.195000,Hövsan q.
86013,1950.0,100 sot,sot,100.0,10000.0,0.195000,Hövsan q.
60613,8500.0,430 sot,sot,430.0,43000.0,0.197674,Masazır q.
82625,2100.0,100 sot,sot,100.0,10000.0,0.210000,Fatmayı q.
4586,2500.0,100 sot,sot,100.0,10000.0,0.250000,Hövsan q.
14274,3500.0,135 sot,sot,135.0,13500.0,0.259259,Məmmədli q.
9089,3500.0,135 sot,sot,135.0,13500.0,0.259259,Məmmədli q.
4155,3500.0,135 sot,sot,135.0,13500.0,0.259259,Məmmədli q.
54814,3000.0,100 sot,sot,100.0,10000.0,0.300000,Saray q.

======================================================================
2.26 EXTREMELY LARGE AREAS
======================================================================

count    1.007750e+05
mean     1.128061e+03
std      9.320227e+04
min      1.000000e+00
1%       3.500000e+01
5%       4.720000e+01
25%      7.000000e+01
50%      1.050000e+02
75%      1.600000e+02
95%      6.000000e+02
99%      2.800000e+03
max      2.000000e+07
Name: area_m2, dtype: float64

Properties with area > 10,000 m²: 389

            price        Sahə area_unit  area_value     area_m2       location
45825  40000000.0  200000 sot       sot    200000.0  20000000.0      28 May m.
75857      3000.0  100000 sot       sot    100000.0  10000000.0     Fatmayı q.
21517      2500.0  100000 sot       sot    100000.0  10000000.0     Fatmayı q.
9746       2500.0  100000 sot       sot    100000.0  10000000.0     Fatmayı q.
4736       2500.0  100000 sot       sot    100000.0  10000000.0     Fatmayı q.
69308  26000000.0   60000 sot       sot     60000.0   6000000.0    Binəqədi r.
28995  19000000.0   60000 sot       sot     60000.0   6000000.0    Binəqədi r.
172       80000.0    7000 sot       sot      7000.0    700000.0     Maştağa q.
87428   2640000.0    4400 sot       sot      4400.0    440000.0        Qobu q.
37618  16000000.0    4000 sot       sot      4000.0    400000.0    Lökbatan q.
3348       3500.0    4000 sot       sot      4000.0    400000.0     Buzovna q.
75936     30000.0    3500 sot       sot      3500.0    350000.0         Xaçmaz
99064  11000000.0    3400 sot       sot      3400.0    340000.0    Binəqədi q.
43823  10000000.0    3300 sot       sot      3300.0    330000.0        Qala q.
22235    450000.0    3000 sot       sot      3000.0    300000.0    Binəqədi q.
26794    450000.0    3000 sot       sot      3000.0    300000.0    Binəqədi q.
38408  15000000.0    3000 sot       sot      3000.0    300000.0        Qala q.
42194   5700000.0    2700 sot       sot      2700.0    270000.0        Qala q.
39989    475000.0    2700 sot       sot      2700.0    270000.0         Astara
21286   5700000.0    2700 sot       sot      2700.0    270000.0        Qala q.
8321        800.0    2500 sot       sot      2500.0    250000.0        Zirə q.
77727  22000000.0    2200 sot       sot      2200.0    220000.0    Lökbatan q.
15726    870000.0    2100 sot       sot      2100.0    210000.0  Pirəkəşkül q.
11510    870000.0    2100 sot       sot      2100.0    210000.0  Pirəkəşkül q.
13378   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
3763    4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
97820     65000.0    2000 sot       sot      2000.0    200000.0         Xaçmaz
41762   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
35716   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
16866   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.

======================================================================
2.27 REMOVE TEMPORARY EDA VARIABLES
======================================================================

======================================================================
2.29 FINAL FEATURE CLEANUP
======================================================================
estate_rel_url_x vs estate_rel_url: 100.00%

======================================================================
2.30 FINAL DATASET CHECK
======================================================================
Final cleaned dataframe shape: (100775, 29)

Final columns:
['datetime_scrape_x', 'price', 'location', 'attributes', 'city_when', 'city', 'day_x', 'hour_x', 'products_label', 'description', 'owner_title', 'address', 'lat', 'lng', 'updated', 'views', 'day_y', 'Kateqoriya', 'Otaq sayı', 'Təmir', 'Çıxarış', 'İpoteka', 'estate_rel_url', 'extra_info', 'area_unit', 'area_value', 'area_m2', 'floor', 'total_floors']

Remaining missing values:

total_floors         24779
floor                24779
Otaq sayı             9412
owner_title            657
description            265
city_when                0
attributes               0
city                     0
day_x                    0
products_label           0
location                 0
price                    0
datetime_scrape_x        0
lat                      0
address                  0
hour_x                   0
lng                      0
day_y                    0
Kateqoriya               0
views                    0
updated                  0
Çıxarış                  0
Təmir                    0
İpoteka                  0
estate_rel_url           0
area_unit                0
extra_info               0
area_m2                  0
area_value               0
dtype: int64

Data types:
datetime_scrape_x     object
price                float64
location              object
attributes            object
city_when             object
city                  object
day_x                 object
hour_x                object
products_label        object
description           object
owner_title           object
address               object
lat                  float64
lng                  float64
updated               object
views                  int64
day_y                 object
Kateqoriya            object
Otaq sayı            float64
Təmir                 object
Çıxarış               object
İpoteka               object
estate_rel_url        object
extra_info            object
area_unit             object
area_value           float64
area_m2              float64
floor                float64
total_floors         float64
dtype: object

Remaining leakage/identifier columns: []

Unique property groups: 64454
Total observations: 100775

X shape: (100775, 28)
y shape: (100775,)

Target range: 11.0 - 600000000.0

All final Checkpoint 2 checks passed.