# CHECKPOINT 1 — Problem Framing

Business Problem:

The goal of this project is to build a machine learning model that can predict real-estate property prices based on available property characteristics. This could help estimate reasonable property prices and support better decision-making.

Target Variable: 

The target variable is `price`, which represents the property's listing price in AZN.

Success Metrics:

We will use:
- MAE (Mean Absolute Error) as the main metric
- RMSE (Root Mean Squared Error)
- R² (R-squared)

MAE will be the main metric because it shows the average prediction error in AZN and is easy to interpret.

Machine Learning Task:

This is a supervised learning regression problem because we are predicting a continuous numerical value (`price`).

# CHECKPOINT 2 — Full EDA and Cleaning

In this step, we explore the dataset, identify data quality issues, remove unnecessary or duplicated information, handle missing values and outliers, and prepare the data for modeling.

In [ ]:
#2.1 Initial Dataset Inspection

# First, we load the dataset and examine its basic structure, available variables, data types, missing values, duplicate rows, and descriptive statistics. This helps us understand the dataset before performing further cleaning and analysis.

import pandas as pd

# firstly we load the dataset
df = pd.read_csv("house_sale.csv")

# the number of rows and columns
print("Shape:", df.shape)

# which variables are available?
print("\nColumns:")
print(df.columns.tolist())

# data type of all columns
print("\nData types:")
print(df.dtypes)

# missing values
print("\nMissing values:")
print(df.isnull().sum())

# duplicated rows
print("\nDuplicates:", df.duplicated().sum())

print("\nFirst 5 rows:")
display(df.head())

# to udnerstand data more clearly: create descriptive statistics 
print("\nNumerical summary:")
display(df.describe())

Shape: (100775, 51)

Columns:
['id_x', 'rel_url', 'estate_rel_url_x', 'datetime_scrape_x', 'price', 'currency_x', 'location', 'attributes', 'city_when', 'city', 'day_x', 'hour_x', 'repair', 'vip', 'featured', 'products_label', 'bill_of_sale', 'mortgage', 'img_url', 'id_y', 'estate_id', 'estate_rel_url_y', 'datetime_scrape_y', 'description', 'unit_price', 'total_price', 'currency_y', 'owner_name', 'owner_title', 'shop_name', 'shop_title', 'address', 'lat', 'lng', 'updated', 'views', 'day_y', 'hour_y', 'estate_details_id_x', 'Binanın növü', 'Kateqoriya', 'Mərtəbə', 'Otaq sayı', 'Sahə', 'Torpaq sahəsi', 'Təmir', 'Çıxarış', 'İpoteka', 'estate_details_id_y', 'estate_rel_url', 'extra_info']

Data types:
id_x                    object
rel_url                 object
estate_rel_url_x        object
datetime_scrape_x       object
price                  float64
currency_x              object
location                object
attributes              object
city_when               object
city                    object
day_x                   object
hour_x                  object
repair                  object
vip                     object
featured                object
products_label          object
bill_of_sale            object
mortgage                object
img_url                 object
id_y                    object
estate_id               object
estate_rel_url_y        object
datetime_scrape_y       object
description             object
unit_price              object
total_price            float64
currency_y              object
owner_name              object
owner_title             object
shop_name               object
shop_title              object
address                 object
lat                    float64
lng                    float64
updated                 object
views                    int64
day_y                   object
hour_y                  object
estate_details_id_x     object
Binanın növü            object
Kateqoriya              object
Mərtəbə                 object
Otaq sayı              float64
Sahə                    object
Torpaq sahəsi           object
Təmir                   object
Çıxarış                 object
İpoteka                 object
estate_details_id_y     object
estate_rel_url          object
extra_info              object
dtype: object

Missing values:
id_x                        0
rel_url                     0
estate_rel_url_x            0
datetime_scrape_x           0
price                       0
currency_x                  0
location                    0
attributes                  0
city_when                   0
city                        0
day_x                       0
hour_x                      0
repair                  19163
vip                     92179
featured                97626
products_label          28145
bill_of_sale            21210
mortgage                67836
img_url                     0
id_y                        0
estate_id                   0
estate_rel_url_y            0
datetime_scrape_y           0
description               265
unit_price              24779
total_price                 0
currency_y                  0
owner_name                657
owner_title               657
shop_name               28757
shop_title              28757
address                     0
lat                         0
lng                         0
updated                     0
views                       0
day_y                       0
hour_y                  85144
estate_details_id_x         0
Binanın növü           100621
Kateqoriya                  0
Mərtəbə                 24779
Otaq sayı                9412
Sahə                        0
Torpaq sahəsi           85204
Təmir                    6001
Çıxarış                     0
İpoteka                 67836
estate_details_id_y         0
estate_rel_url              0
extra_info                  0
dtype: int64

Duplicates: 0

First 5 rows:

,id_x,rel_url,estate_rel_url_x,datetime_scrape_x,price,currency_x,location,attributes,city_when,city,...,Mərtəbə,Otaq sayı,Sahə,Torpaq sahəsi,Təmir,Çıxarış,İpoteka,estate_details_id_y,estate_rel_url,extra_info
0,5df36281-6dc6-4d5d-89a7-5fcfa86f7608,/alqi-satqi?page=174,/items/4521724,2024-10-05 22:07:37.60613+00,499999.0,AZN,Səbail r.,"4 otaqlı, 145 m², 7/9 mərtəbə","Bakı, dünən 23:52",bakı,...,7 / 9,4.0,145 m²,NaN,var,var,NaN,92e82ea2-e1f3-4c2d-a284-151efd99281e,/items/4521724,Şəhidlər xiyabanı * Dağüstü parkı * Səbail r.
1,883e20f0-8872-49a5-8b4b-63b8301b5f8f,/alqi-satqi?page=250,/items/4669294,2024-10-05 22:07:37.60613+00,77000.0,AZN,Biləcəri q.,"4 otaqlı, 90 m²","Bakı, dünən 23:56",bakı,...,NaN,4.0,90 m²,1.3 sot,var,yoxdur,NaN,505eaf81-6bc8-4094-9b00-aa82066548ee,/items/4669294,Binəqədi r.* Biləcəri q.
2,55c36fb1-a3af-476e-ba17-a81f6795be8d,/alqi-satqi?page=250,/items/4669293,2024-10-05 22:07:37.60613+00,92000.0,AZN,İnşaatçılar m.,"3 otaqlı, 60 m²","Bakı, dünən 23:55",bakı,...,NaN,3.0,60 m²,0.1 sot,var,var,NaN,fa63b201-999d-43b5-a61a-778d9d79a6c6,/items/4669293,İnşaatçılar m.* Yasamal r.
3,acf1aa8d-a46a-40f5-b6f2-f7a449569337,/alqi-satqi?page=250,/items/4647811,2024-10-05 22:07:37.60613+00,95000.0,AZN,Qaraçuxur q.,130 m²,"Bakı, dünən 23:55",bakı,...,NaN,NaN,130 m²,NaN,var,var,var,5db56980-05cc-4925-b55b-f58fb3f4d2b6,/items/4647811,Suraxanı r.* Qaraçuxur q.
4,22d840df-9283-4112-bc71-7432511fc776,/alqi-satqi?page=250,/items/4638863,2024-10-05 22:07:37.60613+00,220000.0,AZN,Əhmədli m.,"3 otaqlı, 100 m², 15/16 mərtəbə","Bakı, dünən 23:52",bakı,...,15 / 16,3.0,100 m²,NaN,var,var,NaN,d71cf9a9-86dd-4162-b540-6252a8659a09,/items/4638863,Əhmədli m.* Xalqlar Dostluğu m.* Xətai r.* Əhm...

Numerical summary:

,price,total_price,lat,lng,views,Otaq sayı
count,1.007750e+05,1.007750e+05,100775.000000,100775.000000,100775.000000,91363.000000
mean,3.423557e+05,3.423553e+05,40.410846,49.886371,700.065185,3.133468
std,2.042627e+06,2.042627e+06,0.083193,0.265008,1680.672574,1.372981
min,1.100000e+01,1.100000e+01,32.689217,12.591688,23.000000,1.000000
25%,1.450000e+05,1.450000e+05,40.381900,49.816470,99.000000,2.000000
50%,2.180000e+05,2.180000e+05,40.397219,49.852867,254.000000,3.000000
75%,3.380000e+05,3.380000e+05,40.420578,49.948995,680.000000,4.000000
max,6.000000e+08,6.000000e+08,41.774687,50.341059,113458.000000,20.000000

In [ ]:
# 2.2 Checking `price` and `total_price`

# Based on the initial inspection, we noticed that `price` and `total_price` contain the same number of values. We therefore check whether they are actually identical. If they are, `total_price` should not be used as a feature because it duplicates our target variable `price` and would cause data leakage.

print("price == total_price:",
      (df["price"] == df["total_price"]).mean())

# the differences between the two columns
print("\nDifference between price and total_price:")
print((df["price"] - df["total_price"]).describe())

price == total_price: 0.9998709997519226

Difference between price and total_price:
count    100775.000000
mean          0.470355
std          71.974174
min       -1600.000000
25%           0.000000
50%           0.000000
75%           0.000000
max       20000.000000
dtype: float64

In [ ]:
# so, conclusion:  0.9998709997519226 is showing that the rows are identical

In [ ]:
# 2.3 Checking `_x` and `_y` Columns

# The dataset contains several pairs of `_x` and `_y` columns, which likely came from merging two datasets. We compare each pair to determine whether they contain the same information. If two columns are identical, we can remove one of them because keeping both would be redundant.
# I'll check whether they contain the same information, in order to avoid keeping duplicate features

pairs = [
    ("id_x", "id_y"),
    ("estate_rel_url_x", "estate_rel_url_y"),
    ("datetime_scrape_x", "datetime_scrape_y"),
    ("currency_x", "currency_y"),
    ("estate_details_id_x", "estate_details_id_y")
]

for col1, col2 in pairs:
    same = (df[col1] == df[col2]).mean()
    print(f"{col1} vs {col2}: {same:.2%} identical")

id_x vs id_y: 0.00% identical
estate_rel_url_x vs estate_rel_url_y: 100.00% identical
datetime_scrape_x vs datetime_scrape_y: 0.00% identical
currency_x vs currency_y: 100.00% identical
estate_details_id_x vs estate_details_id_y: 100.00% identical

In [ ]:
# _x and _y check shows that 3 pairs are duplicates, but the other 2 pairs are different

In [ ]:
# 2.4 Analyzing Extreme Price Values

# The initial analysis showed unusually low and high property prices
# to see if they they are real properties or data errors:
# To check:

print("Prices below 1,000 AZN:")
display(df[df["price"] < 1000][
    ["price", "location", "attributes", "Sahə", "Otaq sayı"]
].head(20))

print("\nPrices above 10 million AZN:")
display(df[df["price"] > 10_000_000][
    ["price", "location", "attributes", "Sahə", "Otaq sayı"]
].head(20))

# how many extreme price values are there?

print("Below 1,000 AZN:", (df["price"] < 1000).sum())
print("Above 10 million AZN:", (df["price"] > 10_000_000).sum())

# Check whether extreme prices have reasonable price per m²?

df["price_per_m2"] = df["price"] / df["Sahə"].str.extract(r"([\d.]+)")[0].astype(float)

display(
    df[["price", "Sahə", "price_per_m2"]]
    .sort_values("price_per_m2", ascending=False)
    .head(20)
)

Prices below 1,000 AZN:

,price,location,attributes,Sahə,Otaq sayı
8321,800.0,Zirə q.,2500 sot,2500 sot,NaN
11322,400.0,Saray q.,"2 otaqlı, 86 m², 7/14 mərtəbə",86 m²,2.0
12256,999.0,Memar Əcəmi m.,"3 otaqlı, 133 m², 9/16 mərtəbə",133 m²,3.0
15608,400.0,Saray q.,"2 otaqlı, 86 m², 7/14 mərtəbə",86 m²,2.0
16148,999.0,Memar Əcəmi m.,"3 otaqlı, 133 m², 9/16 mərtəbə",133 m²,3.0
21745,250.0,Əhmədli m.,"2 otaqlı, 30 m²",30 m²,2.0
22304,73.0,Məmmədli q.,"3 otaqlı, 90 m², 1/1 mərtəbə",90 m²,3.0
38666,11.0,Ağ şəhər q.,89 m²,89 m²,NaN
39396,700.0,Nərimanov r.,"2 otaqlı, 65 m², 2/5 mərtəbə",65 m²,2.0
39775,127.0,Sahil q.,"5 otaqlı, 150 m²",150 m²,5.0

Prices above 10 million AZN:

,price,location,attributes,Sahə,Otaq sayı
2704,20000000.0,Həzi Aslanov m.,4300 m²,4300 m²,NaN
2855,13500000.0,Nəriman Nərimanov m.,600 sot,600 sot,NaN
2922,15000000.0,Ulduz m.,160 sot,160 sot,NaN
2942,15000000.0,Nəriman Nərimanov m.,450 sot,450 sot,NaN
6151,25000000.0,Ağ şəhər q.,200 sot,200 sot,NaN
6605,600000000.0,Nəriman Nərimanov m.,"6 otaqlı, 200 m², 7/9 mərtəbə",200 m²,6.0
6942,60000000.0,5-ci mikrorayon q.,"7 otaqlı, 50 m², 6/9 mərtəbə",50 m²,7.0
7639,11000000.0,Gənclik m.,3800 m²,3800 m²,NaN
8065,36000000.0,Ağ şəhər q.,3000 m²,3000 m²,NaN
9096,18500000.0,Sahil m.,116 m²,116 m²,NaN
13410,13000000.0,Ulduz m.,130 sot,130 sot,NaN
14281,18500000.0,Sahil m.,116 m²,116 m²,NaN
16879,13000000.0,Ulduz m.,130 sot,130 sot,NaN
23563,25000000.0,Ağ şəhər q.,200 sot,200 sot,NaN
24188,13500000.0,Nəriman Nərimanov m.,600 sot,600 sot,NaN
27940,13500000.0,Nəriman Nərimanov m.,600 sot,600 sot,NaN
28984,17000000.0,8 Noyabr m.,100 sot,100 sot,NaN
28995,19000000.0,Binəqədi r.,60000 sot,60000 sot,NaN
30193,17500000.0,8 Noyabr m.,3500 m²,3500 m²,NaN
30194,17500000.0,8 Noyabr m.,65 sot,65 sot,NaN

In [ ]:
# 2.5 Checking for Repeated Property Listings

# The dataset may contain the same property multiple times because listings can be in different scrapings. We check the property ID and URL to find repeated listing

# Check for repeated property listings

print("Duplicate estate IDs:", df["estate_id"].duplicated().sum())

print("Duplicate URLs:", df["estate_rel_url"].duplicated().sum())

Duplicate estate IDs: 0
Duplicate URLs: 36321

In [ ]:
# 2.5.1 Checking Repeated Listings

# based on this output we see that, the same URL appears many times, so some listings are repeated
# or can the same URL contain different information?


url = df["estate_rel_url"].value_counts().idxmax()

display(
    df[df["estate_rel_url"] == url][
        ["estate_rel_url", "estate_id", "price", "Sahə", "Otaq sayı", "location"]
    ]
)

,estate_rel_url,estate_id,price,Sahə,Otaq sayı,location
267,/items/4582627,33bd12e6-cb08-4c6e-8542-ef95bba99f79,148000.0,70 m²,3.0,20 Yanvar m.
6852,/items/4582627,ee281c6f-9b0f-4969-85c9-2ec1d43e9e86,148000.0,70 m²,3.0,20 Yanvar m.
10284,/items/4582627,7f6a797b-8717-4deb-b05a-1e0e27de3b18,148000.0,70 m²,3.0,20 Yanvar m.
14933,/items/4582627,c3b239f8-5cb7-4a09-971d-00135a5b8cfd,148000.0,70 m²,3.0,20 Yanvar m.
21054,/items/4582627,1f798d94-8a03-42c9-a4b9-19fbc5c897d9,148000.0,70 m²,3.0,20 Yanvar m.
29189,/items/4582627,d9e3e646-88a4-4b9c-8082-618c6171988f,148000.0,70 m²,3.0,20 Yanvar m.
41446,/items/4582627,460737ba-22e1-410a-97b4-13258224e3d3,148000.0,70 m²,3.0,20 Yanvar m.
47869,/items/4582627,6feef4cd-bd86-44de-9a82-7cb48d6ca021,148000.0,70 m²,3.0,20 Yanvar m.
55741,/items/4582627,1d1bfad0-4310-4016-b713-e221015ab9df,148000.0,70 m²,3.0,20 Yanvar m.
56791,/items/4582627,6a941b52-42f5-4ad9-8d74-98018f08a81b,145000.0,70 m²,3.0,20 Yanvar m.
61241,/items/4582627,403db140-9a19-4bbe-87ad-ac31443b020d,145000.0,70 m²,3.0,20 Yanvar m.
74404,/items/4582627,b8c4b372-9fee-4a38-a85b-f4db86350df6,145000.0,70 m²,3.0,20 Yanvar m.
79562,/items/4582627,497468e3-23f2-44ad-8169-230605a4685e,145000.0,70 m²,3.0,20 Yanvar m.
87504,/items/4582627,74b7a44d-8459-420f-86ff-a7a48a52f8df,145000.0,70 m²,3.0,20 Yanvar m.
90710,/items/4582627,3821cb9c-7265-46a6-a4f6-4a3570525449,145000.0,70 m²,3.0,20 Yanvar m.
94318,/items/4582627,27498a67-6f7d-4d5b-99b3-6fc6002510f0,145000.0,70 m²,3.0,20 Yanvar m.
96414,/items/4582627,fb93c483-f866-42ce-b362-d4dc70512791,145000.0,70 m²,3.0,20 Yanvar m.

In [ ]:
# 2.5.2 Checking Scraping Dates
# maybe it was scraped at different times?

In [9]:
# Check whether repeated listings were scraped at different times

display(
    df[df["estate_rel_url"] == url][
        ["estate_rel_url", "estate_id", "price",
         "datetime_scrape_x", "datetime_scrape_y"]
    ]
)

,estate_rel_url,estate_id,price,datetime_scrape_x,datetime_scrape_y
267,/items/4582627,33bd12e6-cb08-4c6e-8542-ef95bba99f79,148000.0,2024-10-05 22:07:37.60613+00,2024-10-05 22:14:10.089116+00
6852,/items/4582627,ee281c6f-9b0f-4969-85c9-2ec1d43e9e86,148000.0,2024-10-08 07:32:19.961753+00,2024-10-08 07:35:53.717949+00
10284,/items/4582627,7f6a797b-8717-4deb-b05a-1e0e27de3b18,148000.0,2024-10-09 04:58:40.151251+00,2024-10-09 05:02:29.349209+00
14933,/items/4582627,c3b239f8-5cb7-4a09-971d-00135a5b8cfd,148000.0,2024-10-09 22:00:47.854254+00,2024-10-09 22:05:18.232268+00
21054,/items/4582627,1f798d94-8a03-42c9-a4b9-19fbc5c897d9,148000.0,2024-10-12 05:50:17.512957+00,2024-10-12 05:53:49.164398+00
29189,/items/4582627,d9e3e646-88a4-4b9c-8082-618c6171988f,148000.0,2024-10-13 20:58:00.666852+00,2024-10-13 21:02:02.025003+00
41446,/items/4582627,460737ba-22e1-410a-97b4-13258224e3d3,148000.0,2024-10-17 23:53:36.973072+00,2024-10-17 23:58:16.367958+00
47869,/items/4582627,6feef4cd-bd86-44de-9a82-7cb48d6ca021,148000.0,2024-10-19 22:03:55.353416+00,2024-10-19 22:07:51.907099+00
55741,/items/4582627,1d1bfad0-4310-4016-b713-e221015ab9df,148000.0,2024-10-21 20:44:09.129440,2024-10-21 20:49:37.939165
56791,/items/4582627,6a941b52-42f5-4ad9-8d74-98018f08a81b,145000.0,2024-10-29 20:44:40.173239,2024-10-29 21:02:34.033173
61241,/items/4582627,403db140-9a19-4bbe-87ad-ac31443b020d,145000.0,2024-10-31 20:46:56.927922,2024-10-31 20:51:38.871497
74404,/items/4582627,b8c4b372-9fee-4a38-a85b-f4db86350df6,145000.0,2024-11-04 20:51:51.095865,2024-11-04 20:56:46.962654
79562,/items/4582627,497468e3-23f2-44ad-8169-230605a4685e,145000.0,2024-11-06 20:44:37.839806,2024-11-06 20:48:54.299689
87504,/items/4582627,74b7a44d-8459-420f-86ff-a7a48a52f8df,145000.0,2024-11-09 20:45:46.632914,2024-11-09 20:50:03.404512
90710,/items/4582627,3821cb9c-7265-46a6-a4f6-4a3570525449,145000.0,2024-11-12 20:43:10.396293,2024-11-12 20:46:36.658788
94318,/items/4582627,27498a67-6f7d-4d5b-99b3-6fc6002510f0,145000.0,2024-11-14 20:44:11.397519,2024-11-14 20:48:13.495427
96414,/items/4582627,fb93c483-f866-42ce-b362-d4dc70512791,145000.0,2024-11-17 20:45:02.902614,2024-11-17 20:48:07.997506

In [ ]:
# 2.5.3 Frequency of Repeated Properties
# based on this output we can see that estate_rel_url appears multiple times because it was scraped repeatedly on different dates, 
# not because the rows are exact duplicates
# so now, should we keep multiple snapshots of the same property, or should we keep only one?

In [ ]:
# how many times each property appears?
url_counts = df["estate_rel_url"].value_counts()

print("Properties appearing more than once:",
      (url_counts > 1).sum())

print("\nMaximum appearances of one property:",
      url_counts.max())

Properties appearing more than once: 20506

Maximum appearances of one property: 17

In [ ]:
# 2.5.4 Checking Price Changes in Repeated Listings
# Are these repeated listings mostly identical, or do their prices/details change over time?

In [ ]:
# do repeated listings have different prices?
price_changes = df.groupby("estate_rel_url")["price"].nunique()

print("Properties with different prices:",
      (price_changes > 1).sum())

print("Properties with the same price:",
      (price_changes == 1).sum())

Properties with different prices: 3356
Properties with the same price: 61098

In [ ]:
#2.5.5 Counting Rows Belonging to Repeated Properties
# How many total rows are actually repeated properties?

In [12]:
# Count rows belonging to properties that appear more than once
repeated_rows = df["estate_rel_url"].duplicated(keep=False).sum()

print("Rows belonging to repeated properties:", repeated_rows)

Rows belonging to repeated properties: 56827

In [ ]:
# 2.5.6 Checking the Number of Unique Properties
# as a result we can see that: some properties have price changes, meaning the repeated rows actually contain useful time information
# now, we need to know how much of the dataset would remain if we kept only one row per property

In [13]:
# Number of unique properties
print("Unique properties:", df["estate_rel_url"].nunique())

# Rows after keeping only one row per property
print("Rows if we keep one row per property:",
      df.drop_duplicates("estate_rel_url").shape[0])

Unique properties: 64454
Rows if we keep one row per property: 64454

In [ ]:
# 2.6 Analyzing `unit_price`
# based on these outputs, it seems that many properties appear more than once, but some changed price over time
# and we won't delete them yet, these repeated properties need to be handled properly when we split data

In [14]:
# next, in our first analyse, in the datatypes we saw: unit_price
# now we check unit_price because it may be calculated from price and property area, which could cause target leakage if we use it as a feature
print(df["unit_price"].dropna().head(20).tolist())

print("\nExamples:")
print(df["unit_price"].dropna().sample(20, random_state=42).tolist())

['3 450 AZN/m²', '2 200 AZN/m²', '5 000 AZN/m²', '3 700 AZN/m²', '1 820 AZN/m²', '2 520 AZN/m²', '1 800 AZN/m²', '2 060 AZN/m²', '3 480 AZN/m²', '2 140 AZN/m²', '1 070 AZN/m²', '2 020 AZN/m²', '3 340 AZN/m²', '1 250 AZN/m²', '1 210 AZN/m²', '1 740 AZN/m²', '2 290 AZN/m²', '2 620 AZN/m²', '1 900 AZN/m²', '2 030 AZN/m²']

Examples:
['2 450 AZN/m²', '1 930 AZN/m²', '4 800 AZN/m²', '3 120 AZN/m²', '2 450 AZN/m²', '2 320 AZN/m²', '2 040 AZN/m²', '2 650 AZN/m²', '3 040 AZN/m²', '1 670 AZN/m²', '2 460 AZN/m²', '2 150 AZN/m²', '2 460 AZN/m²', '1 930 AZN/m²', '1 850 AZN/m²', '2 500 AZN/m²', '3 000 AZN/m²', '2 420 AZN/m²', '3 200 AZN/m²', '3 520 AZN/m²']

In [15]:
# based on this outpur we see that: unit_price is price per m², so it is derived from the property's price and area
# so the decision is drop unit_price because it can cause target leakage

df = df.drop(columns=["unit_price"])

In [ ]:
# 2.7 Removing Leakage and Non-Predictive Columns

# Now we go back to the previous analysis  where we checked the duplicated and suspicious columns first
# We found that total_price is essentially identical to our target price 
# so keeping it would cause data leakage. then we also found that the _x/_y and ID/URL columns are identifiers or duplicated information 
# rather than useful property features
# Therefore, we decided to remove these columns before modeling.

In [16]:
drop_cols = [
    "total_price",          # same information as price -> leakage
    "estate_rel_url",       # URL/identifier
    "estate_rel_url_x",     # URL/identifier
    "estate_rel_url_y",     # URL/identifier
    "id_x",                 # identifier
    "id_y",                 # identifier
    "estate_id",            # identifier
    "estate_details_id_x",  # identifier
    "estate_details_id_y",  # identifier
    "rel_url",              # scraping URL
    "img_url"               # image URL
]

df_model = df.drop(columns=drop_cols)

print("Shape after dropping:", df_model.shape)

Shape after dropping: (100775, 40)

In [17]:
# lets check missing values after removing leakage and identifier columns
missing_percent = (df_model.isnull().mean() * 100).sort_values(ascending=False)

print("Missing values (%) in remaining columns:")
print(missing_percent)

Missing values (%) in remaining columns:
Binanın növü         99.847184
featured             96.875217
vip                  91.470107
Torpaq sahəsi        84.548747
hour_y               84.489209
İpoteka              67.314314
mortgage             67.314314
shop_title           28.535847
shop_name            28.535847
products_label       27.928554
Mərtəbə              24.588440
bill_of_sale         21.046887
repair               19.015629
Otaq sayı             9.339618
Təmir                 5.954850
owner_title           0.651947
owner_name            0.651947
description           0.262962
city_when             0.000000
attributes            0.000000
location              0.000000
currency_x            0.000000
price                 0.000000
datetime_scrape_x     0.000000
day_x                 0.000000
city                  0.000000
lat                   0.000000
datetime_scrape_y     0.000000
hour_x                0.000000
address               0.000000
currency_y            0.000000
lng                   0.000000
Kateqoriya            0.000000
updated               0.000000
views                 0.000000
day_y                 0.000000
Sahə                  0.000000
Çıxarış               0.000000
extra_info            0.000000
price_per_m2          0.000000
dtype: float64

In [18]:
# Removing Features with Excessive Missing Values
# we see that, some columns have too much missing data, it is better to remove them

drop_missing_cols = [
    "Binanın növü",
    "featured",
    "vip",
    "Torpaq sahəsi",
    "hour_y"
]

df_clean = df_model.drop(columns=drop_missing_cols)

print("Shape after removing highly incomplete features:", df_clean.shape)

Shape after removing highly incomplete features: (100775, 35)

In [19]:
# Checking Duplicate Features
# then, İpoteka and mortgage both had exactly 67.31% missing data, now we need to check them to see if they are dublicates

same = (df_clean["İpoteka"] == df_clean["mortgage"]).mean()

print(f"İpoteka vs mortgage: {same:.2%} identical")

İpoteka vs mortgage: 0.00% identical

In [ ]:
# it seems that they are not duplicates, so we should keep them

In [20]:
# Now lets look at the other columns, the ones that had lower missing values
# Inspecting Remaining Missing Values

missing_cols = df_clean.columns[df_clean.isnull().any()]

for col in missing_cols:
    print(f"\n===== {col} =====")
    print(df_clean[col].value_counts(dropna=False).head(10))

===== repair =====
repair
Təmirli    81612
NaN        19163
Name: count, dtype: int64

===== products_label =====
products_label
Agentlik    71981
NaN         28145
Kompleks      649
Name: count, dtype: int64

===== bill_of_sale =====
bill_of_sale
Çıxarış var    79565
NaN            21210
Name: count, dtype: int64

===== mortgage =====
mortgage
NaN            67836
İpoteka var    32939
Name: count, dtype: int64

===== description =====
description
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               265
"Knightsbridge Residence" premium yaşayış kompleksində limitli sayda olan tam təmirli mənzillərin satışına start verildi!\n74-146 kv.m aralığında sahəyə malik 2, 3 və 4 otaqlı tam təmirli mənzilləri 25% ilkin ödəniş və 60 ayadək daxili kredit şərtləri ilə, həmçinin 20 ilədək ipoteka ilə əldə etmək mümkündür.Tam təmirli mənzil dedikdə nəyi nəzərdə tuturuq?\n* Neoklassik üslubda yüksək keyfiyyətli materialların istifadəsi ilə tam təmir edilmiş\n* Yaşayış üçün tam hazır\n* Mətbəx də daxil olmaqla, hər bir otağı mebel, aksesuar, dekor əşyaları ilə təmin edilmiş\n* Böyük məişət texnikası quraşdırılmış\n* Bütün zəruri elektrik, telefon, internet və televiziya xətləri ilə təchiz olunmuşOtaqların hamısı dünyaca tanınmış brendlərin yüksək keyfiyyətli mebelləri və qabyuyandan tutmuş, paltaryuyan, soyuducu və saç feninədək ən keyfiyyətli məişət texnikası ilə təmin edilmişdir ki, ilk gündən “Knightsbridge” həyat tərzini və keyfiyyət standartını hiss edəsiniz.Burada xalçalar, pərdələr, şamlar, hətta şkafınızdakı taxta asılqanlaradək hər bir detal diqqətlə seçilmişdir və sizə yalnız yeni evinizdən zövq almaq qalır.Ətraflı məlumat və mənzillərə baxış üçün *2023 və ya *2024 nömrəmizə zəng edə və ya Ağ Şəhərdə, 8 Noyabr prospekti, 151 ünvanında yerləşən “Knightsbridge Residence” satış ofisimizə (Nizami Parkı ilə üzbəüz) yaxınlaşa bilərsiniz.\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               56
"Grand Plaza" Koroğlu və Zorge parkları ilə əhatə olunan yaşıllıq ərazidə yerləşən,otel üslublu,premium yaşayış kompleksidir.Kompleks Dədə Qorqud parkı və ADA Universitetindən 3 dəqiqəlik, Nəsimi Rayon İcra Hakimiyyəti və Heydər Əliyev adına Müasir Təhsil Kompleksindən isə 2 dəqiqəlik piyada yol məsafəsində inşa edilir.\n \nÜstünlüklərimiz:•​3,6 metr hündürlüyündə tavan\n•​Sərbəst layihələndirmə\n•​ABŞ istehsalı,sürətli “OTİS”liftləri\n•​“TEXNONİKOL” şirkətinə məxsus izolyasiya sistemləri\n•​B30 markalı beton\n•​A500C markalı armatur​\n•​Keramoqranit ilə işlənmiş fasad\n•​Alman istehsalı “SCHÜCO” pəncərə sistemləri\n•​Türkiyə istehsalı lyüks seyf qapılar\n•​Odadavamlı işıq kabelləri\n•​9+ ballıq seysmik davamlılıq\n•​Qranit pilləkənlər\n•​Mərkəzləşdirilmiş su filtrasiya sistemi\n•​Mərkəzləşdirilmiş yanğın əleyhinə sistem\n•​Şəhərə açılan gözəl mənzərə \n•​Ehtiyat generator sistemi\n•​Yaşıl parklar ərazisində yerləşmə\n•​Ekoloji cəhətdən təmiz ərazi\n•​Uşaqlar üçün oyun meydançası\n•​Qonaqların qarşılanması üçün lobbi\n•​Sakinlər üçün 2 mərtəbəli parkinq\n•​Qonaqlar üçün xüsusi parkinq\n•​4600 m2 sahəli həyət\n•​Avtoyuma xidməti \n•​Şəhərin əsas yollarına birbaşa çıxış\n•​Yüksək sürətli internet və kabel televiziyası\n•​7/24 mühafizə xidməti və video nəzarət\n•​Konsyerj xidmətiÖdəniş şərtlərinə görə qiymətlər:• Faizsiz daxili kreditlə: ilkin ödəniş 50 % / 3 ay daxili kredit.\n• 20 illik ipoteka krediti / ilkin ödəniş 20 % (illik 6-11%)Tam nağd ödəniş zamanı əlavə endirim tətbiq olunur.Mənzillərimiz təmirsizdir.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    39
“Baku City Residence Khatai” dünyaca məşhur “ Bakı Ağ Şəhər”də yerləşən müasir yönümlü, möhtəşəm dəniz mənzərəsi və rahat infrastruktur təqdim edən yaşayış kompleksidir.Daxili infrastruktur:\n• LANDAU Preschool\n• World Class fitness mərkəz\n• Qapalı Olimpiya hovuzu\n• World Class SPA\n• Rossman\n• Dünya brend restoran və “coffee shop”-lar\n• Ağıllı Yaşayış Kompleksi\n• Konsyerj\n• 24/7 canlı mühafizə və video-müşahidə\n• Gastronom7300 kvadrat metrlik Qapalı Həyət:\n• Uşaq meydançası\n• Velosiped zolağı\n• Futbol meydançası\n• Ağıllı kompleks sistemi( Üz tanıma sistemi; QR code)894 yerlik, 3 mərtəbəli yeraltı Avtodayanacaq:\n• Elektromobillər üçün dolum məntəqələri\n• Avto yuma• Liftlər: 3 “KONE” markalı 2 ədəd sərnişin və 1 ədəd yük lifti\n• Fasad: ventilyasiya olunan keramoqranit üzlüklü fasad, 3 qat şüşəli izosistemli alüminium vitraj pəncərələr, məsaməli hörgü blokları və hazır qəlib sistemi• Mənzil nağd, hissəli ödəniş və ya ipoteka şərtləri ilə təklif edilir.\nHissəli ödəniş və ipoteka:OFİSİN XİDMƏT HAQQİ 1%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              32
YENİ HAYAT - PARK AZURE Residence yaşayış kompleksində əla təmirli gözəl mənzil satılır. —————————————-Kompleksdə xidmətə daxildir:\nYaşıl park , trenajorlar və uşaq əyləncə yeri\nFutbol meydançası\nLiftlər\nResepşn\nMuhafizə 7/24 \nElektrik.   \nSantexnik\nXadimə\nZibillərin mərtəbədən daşınması\n————————————-\nƏlavə ödənişli xidmətlər ;\nVip restoranlar \n(Kfc, Friday, Məclis, Nəlbəki, Nani, Lavaş)\nUşaq baxçası\nBravo Market\nFitness\nBaseyn\nGözəllik salonu\nAtelye\nAptek\nParking\nAvtoyuma\nQuru Təmizləmə\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              31
Nizami City Yaşayış Kompleksinin qeyri-yaşayış sahələrinin satışı və icarəsi mümkündür. Kompleks Nizami mts.-nın yaxınlığı, 3cü və 5ci paralellər arasında yerləşir. Qiymətlər obyektlərin yerləşmə mərtəbəsi və baxış küçəsinə görə dəyişir. Ölçülər istənilən qədər artırıla bilər. Ətraflı məlumat üçün satış ofisinə yaxınlaşmağınız kifayətdir.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               24
"Nizami City" –nin 1ci ABC mərhələsi hazırdır, 2ci mərhələsi- EFG binalarında satışı davam edir. 9 binadan ibarət kompleks Nizami mt.s-nın yaxınlığındadır. 9 yaşayış mərtəbəsi, qapalı həyət və keramoqranit fasada malik kompleksdə sakinlərin rahatçılığı üçün hər bir detal düşünülmüşdür. Siz də kompleksdən mənzil əldə etmək istəyirsinizsə satış ofisinə yaxınlaşmağınız kifayətdir.Qiymətlər yeni mərhələdə 1kvm üçün 2500-3200AZN arasında dəyişir, 24 ayadək daxili kredit imkanları var.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               21
"Nizami City" –nin 1ci ABC mərhələsi hazırdır, 2ci mərhələsi- EFG binalarında satışı davam edir. 9 binadan ibarət kompleks Nizami mt.s-nın yaxınlığındadır. 9 yaşayış mərtəbəsi, qapalı həyət və keramoqranit fasada malik kompleksdə sakinlərin rahatçılığı üçün hər bir detal düşünülmüşdür. Siz də kompleksdən mənzil əldə etmək istəyirsinizsə satış ofisinə yaxınlaşmağınız kifayətdir.Qiymətlər yeni mərhələdə 1kvm üçün 2400-2800 AZN arasında dəyişir, 36 ayadək daxili kredit imkanları var.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              20

In [21]:
# as we can see : Mərtəbə and Sahə are stored as text, we need to convert them to numbers

# Converting Property Features to Numerical Values
df_clean["area_m2"] = (
    df_clean["Sahə"]
    .str.extract(r"([\d.]+)")[0]
    .astype(float)
)

# Extract current floor from Mərtəbə
df_clean["floor"] = (
    df_clean["Mərtəbə"]
    .str.extract(r"^(\d+)")[0]
    .astype(float)
)

# Extract total number of floors
df_clean["total_floors"] = (
    df_clean["Mərtəbə"]
    .str.extract(r"/\s*(\d+)")[0]
    .astype(float)
)

print(df_clean[[
    "Sahə",
    "area_m2",
    "Mərtəbə",
    "floor",
    "total_floors"
]].head(10))

     Sahə  area_m2  Mərtəbə  floor  total_floors
0  145 m²    145.0    7 / 9    7.0           9.0
1   90 m²     90.0      NaN    NaN           NaN
2   60 m²     60.0      NaN    NaN           NaN
3  130 m²    130.0      NaN    NaN           NaN
4  100 m²    100.0  15 / 16   15.0          16.0
5  130 m²    130.0    3 / 4    3.0           4.0
6   70 m²     70.0    2 / 5    2.0           5.0
7  153 m²    153.0   3 / 18    3.0          18.0
8  485 m²    485.0      NaN    NaN           NaN
9  104 m²    104.0  11 / 13   11.0          13.0

In [22]:
# now we look at categorical variables
# checking overlapping categorical features

categorical_pairs = [
    ("repair", "Təmir"),
    ("mortgage", "İpoteka"),
    ("bill_of_sale", "Çıxarış")
]

for col1, col2 in categorical_pairs:
    print(f"\n===== {col1} vs {col2} =====")
    print(pd.crosstab(df[col1], df[col2], dropna=False))

===== repair vs Təmir =====
Təmir      var  yoxdur   NaN
repair
Təmirli  81612       0     0
NaN          0   13162  6001

===== mortgage vs İpoteka =====
İpoteka        var    NaN
mortgage
İpoteka var  32939      0
NaN              0  67836

===== bill_of_sale vs Çıxarış =====
Çıxarış         var  yoxdur
bill_of_sale
Çıxarış var   79565       0
NaN               0   21210

In [23]:
# llooking at this output we see that, these are duplicates
# Removing Duplicate Categorical Features

duplicate_categorical_cols = [
    "repair",
    "mortgage",
    "bill_of_sale"
]

df_model = df_model.drop(columns=duplicate_categorical_cols)

print("Shape after removing duplicate categorical features:", df_model.shape)

Shape after removing duplicate categorical features: (100775, 37)

In [24]:
# now looking at the missing values
# Checking missing values after removing duplicate features

missing_pct = (
    df_model.isnull().mean() * 100
).sort_values(ascending=False)

print("Missing values (%) in remaining columns:")
print(missing_pct)

Missing values (%) in remaining columns:
Binanın növü         99.847184
featured             96.875217
vip                  91.470107
Torpaq sahəsi        84.548747
hour_y               84.489209
İpoteka              67.314314
shop_name            28.535847
shop_title           28.535847
products_label       27.928554
Mərtəbə              24.588440
Otaq sayı             9.339618
Təmir                 5.954850
owner_name            0.651947
owner_title           0.651947
description           0.262962
attributes            0.000000
price                 0.000000
datetime_scrape_x     0.000000
location              0.000000
currency_x            0.000000
datetime_scrape_y     0.000000
lat                   0.000000
address               0.000000
currency_y            0.000000
city_when             0.000000
hour_x                0.000000
day_x                 0.000000
city                  0.000000
lng                   0.000000
Kateqoriya            0.000000
updated               0.000000
views                 0.000000
day_y                 0.000000
Sahə                  0.000000
Çıxarış               0.000000
extra_info            0.000000
price_per_m2          0.000000
dtype: float64

In [ ]:
# Handling Highly Missing Features
# Firstly, we remove features that are almost missing 
# Remove features with more than 80% missing values ( since its practical cleaning threshold)

high_missing_cols = [
    "Binanın növü",
    "featured",
    "vip",
    "Torpaq sahəsi",
    "hour_y"
]

df_model = df_model.drop(columns=high_missing_cols)

print("Shape after removing highly incomplete features:", df_model.shape)

Shape after removing highly incomplete features: (100775, 32)

In [26]:
# Analyzing Remaining Missing Values
# categorical missing valueas
# Check the most common values of remaining columns with missing data

missing_cols = df_model.columns[df_model.isnull().any()]

for col in missing_cols:
    print(f"\n===== {col} =====")
    print(df_model[col].value_counts(dropna=False).head(10))

===== products_label =====
products_label
Agentlik    71981
NaN         28145
Kompleks      649
Name: count, dtype: int64

===== description =====
description
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               265
"Knightsbridge Residence" premium yaşayış kompleksində limitli sayda olan tam təmirli mənzillərin satışına start verildi!\n74-146 kv.m aralığında sahəyə malik 2, 3 və 4 otaqlı tam təmirli mənzilləri 25% ilkin ödəniş və 60 ayadək daxili kredit şərtləri ilə, həmçinin 20 ilədək ipoteka ilə əldə etmək mümkündür.Tam təmirli mənzil dedikdə nəyi nəzərdə tuturuq?\n* Neoklassik üslubda yüksək keyfiyyətli materialların istifadəsi ilə tam təmir edilmiş\n* Yaşayış üçün tam hazır\n* Mətbəx də daxil olmaqla, hər bir otağı mebel, aksesuar, dekor əşyaları ilə təmin edilmiş\n* Böyük məişət texnikası quraşdırılmış\n* Bütün zəruri elektrik, telefon, internet və televiziya xətləri ilə təchiz olunmuşOtaqların hamısı dünyaca tanınmış brendlərin yüksək keyfiyyətli mebelləri və qabyuyandan tutmuş, paltaryuyan, soyuducu və saç feninədək ən keyfiyyətli məişət texnikası ilə təmin edilmişdir ki, ilk gündən “Knightsbridge” həyat tərzini və keyfiyyət standartını hiss edəsiniz.Burada xalçalar, pərdələr, şamlar, hətta şkafınızdakı taxta asılqanlaradək hər bir detal diqqətlə seçilmişdir və sizə yalnız yeni evinizdən zövq almaq qalır.Ətraflı məlumat və mənzillərə baxış üçün *2023 və ya *2024 nömrəmizə zəng edə və ya Ağ Şəhərdə, 8 Noyabr prospekti, 151 ünvanında yerləşən “Knightsbridge Residence” satış ofisimizə (Nizami Parkı ilə üzbəüz) yaxınlaşa bilərsiniz.\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               56
"Grand Plaza" Koroğlu və Zorge parkları ilə əhatə olunan yaşıllıq ərazidə yerləşən,otel üslublu,premium yaşayış kompleksidir.Kompleks Dədə Qorqud parkı və ADA Universitetindən 3 dəqiqəlik, Nəsimi Rayon İcra Hakimiyyəti və Heydər Əliyev adına Müasir Təhsil Kompleksindən isə 2 dəqiqəlik piyada yol məsafəsində inşa edilir.\n \nÜstünlüklərimiz:•​3,6 metr hündürlüyündə tavan\n•​Sərbəst layihələndirmə\n•​ABŞ istehsalı,sürətli “OTİS”liftləri\n•​“TEXNONİKOL” şirkətinə məxsus izolyasiya sistemləri\n•​B30 markalı beton\n•​A500C markalı armatur​\n•​Keramoqranit ilə işlənmiş fasad\n•​Alman istehsalı “SCHÜCO” pəncərə sistemləri\n•​Türkiyə istehsalı lyüks seyf qapılar\n•​Odadavamlı işıq kabelləri\n•​9+ ballıq seysmik davamlılıq\n•​Qranit pilləkənlər\n•​Mərkəzləşdirilmiş su filtrasiya sistemi\n•​Mərkəzləşdirilmiş yanğın əleyhinə sistem\n•​Şəhərə açılan gözəl mənzərə \n•​Ehtiyat generator sistemi\n•​Yaşıl parklar ərazisində yerləşmə\n•​Ekoloji cəhətdən təmiz ərazi\n•​Uşaqlar üçün oyun meydançası\n•​Qonaqların qarşılanması üçün lobbi\n•​Sakinlər üçün 2 mərtəbəli parkinq\n•​Qonaqlar üçün xüsusi parkinq\n•​4600 m2 sahəli həyət\n•​Avtoyuma xidməti \n•​Şəhərin əsas yollarına birbaşa çıxış\n•​Yüksək sürətli internet və kabel televiziyası\n•​7/24 mühafizə xidməti və video nəzarət\n•​Konsyerj xidmətiÖdəniş şərtlərinə görə qiymətlər:• Faizsiz daxili kreditlə: ilkin ödəniş 50 % / 3 ay daxili kredit.\n• 20 illik ipoteka krediti / ilkin ödəniş 20 % (illik 6-11%)Tam nağd ödəniş zamanı əlavə endirim tətbiq olunur.Mənzillərimiz təmirsizdir.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    39
“Baku City Residence Khatai” dünyaca məşhur “ Bakı Ağ Şəhər”də yerləşən müasir yönümlü, möhtəşəm dəniz mənzərəsi və rahat infrastruktur təqdim edən yaşayış kompleksidir.Daxili infrastruktur:\n• LANDAU Preschool\n• World Class fitness mərkəz\n• Qapalı Olimpiya hovuzu\n• World Class SPA\n• Rossman\n• Dünya brend restoran və “coffee shop”-lar\n• Ağıllı Yaşayış Kompleksi\n• Konsyerj\n• 24/7 canlı mühafizə və video-müşahidə\n• Gastronom7300 kvadrat metrlik Qapalı Həyət:\n• Uşaq meydançası\n• Velosiped zolağı\n• Futbol meydançası\n• Ağıllı kompleks sistemi( Üz tanıma sistemi; QR code)894 yerlik, 3 mərtəbəli yeraltı Avtodayanacaq:\n• Elektromobillər üçün dolum məntəqələri\n• Avto yuma• Liftlər: 3 “KONE” markalı 2 ədəd sərnişin və 1 ədəd yük lifti\n• Fasad: ventilyasiya olunan keramoqranit üzlüklü fasad, 3 qat şüşəli izosistemli alüminium vitraj pəncərələr, məsaməli hörgü blokları və hazır qəlib sistemi• Mənzil nağd, hissəli ödəniş və ya ipoteka şərtləri ilə təklif edilir.\nHissəli ödəniş və ipoteka:OFİSİN XİDMƏT HAQQİ 1%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              32
YENİ HAYAT - PARK AZURE Residence yaşayış kompleksində əla təmirli gözəl mənzil satılır. —————————————-Kompleksdə xidmətə daxildir:\nYaşıl park , trenajorlar və uşaq əyləncə yeri\nFutbol meydançası\nLiftlər\nResepşn\nMuhafizə 7/24 \nElektrik.   \nSantexnik\nXadimə\nZibillərin mərtəbədən daşınması\n————————————-\nƏlavə ödənişli xidmətlər ;\nVip restoranlar \n(Kfc, Friday, Məclis, Nəlbəki, Nani, Lavaş)\nUşaq baxçası\nBravo Market\nFitness\nBaseyn\nGözəllik salonu\nAtelye\nAptek\nParking\nAvtoyuma\nQuru Təmizləmə\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              31
Nizami City Yaşayış Kompleksinin qeyri-yaşayış sahələrinin satışı və icarəsi mümkündür. Kompleks Nizami mts.-nın yaxınlığı, 3cü və 5ci paralellər arasında yerləşir. Qiymətlər obyektlərin yerləşmə mərtəbəsi və baxış küçəsinə görə dəyişir. Ölçülər istənilən qədər artırıla bilər. Ətraflı məlumat üçün satış ofisinə yaxınlaşmağınız kifayətdir.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               24
"Nizami City" –nin 1ci ABC mərhələsi hazırdır, 2ci mərhələsi- EFG binalarında satışı davam edir. 9 binadan ibarət kompleks Nizami mt.s-nın yaxınlığındadır. 9 yaşayış mərtəbəsi, qapalı həyət və keramoqranit fasada malik kompleksdə sakinlərin rahatçılığı üçün hər bir detal düşünülmüşdür. Siz də kompleksdən mənzil əldə etmək istəyirsinizsə satış ofisinə yaxınlaşmağınız kifayətdir.Qiymətlər yeni mərhələdə 1kvm üçün 2500-3200AZN arasında dəyişir, 24 ayadək daxili kredit imkanları var.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               21
"Nizami City" –nin 1ci ABC mərhələsi hazırdır, 2ci mərhələsi- EFG binalarında satışı davam edir. 9 binadan ibarət kompleks Nizami mt.s-nın yaxınlığındadır. 9 yaşayış mərtəbəsi, qapalı həyət və keramoqranit fasada malik kompleksdə sakinlərin rahatçılığı üçün hər bir detal düşünülmüşdür. Siz də kompleksdən mənzil əldə etmək istəyirsinizsə satış ofisinə yaxınlaşmağınız kifayətdir.Qiymətlər yeni mərhələdə 1kvm üçün 2400-2800 AZN arasında dəyişir, 36 ayadək daxili kredit imkanları var.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              20
Daxili kredit ilə satış var - ilkin ödəniş 50%, 36 ay müddətinə təklif edilir.Şəhərin mərkəzinə yaxınlıq və səs-küyündən uzaqlıq. Pəncərədən Xəzər dənizinin görüntüsü. 12 sot daşma hovuzlu, qonşu mənzildən görüntüyə qapalı, yaşıl və geniş həyət. Təmiz hava. Müasir dizayna malik eksteryer və interyer. Hündür tavanlar.\nVillanın yaşayış sahəsi 350, terrası 150 kv.m-dir. Ödənişə daxil edilməyən yaşıllıq sahəsinin ərazisi isə 550 kv.m-dir. 5 otaq, 3 sanqovşağı var.\nVilla yaşayış üçün hər cür şəraitlə təmin edilib: qapalı həyət, supermarket, mərkəzi elektrik təchizatı, mərkəzləşdirilmiş yanğın əleyhinə sistem, ehtiyat generatorlar sistemi, uşaq meydançaları, IP domofon sistemi, 7/24 su təchizatı, açıq havada idman meydançası, kafe və restoranlar, 7/24 mühafizə və videomüşahidə, yüksəksürətli internet, kabel TV.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 20

In [27]:
# based on this output:
# owner_name  and shop_name and shop_title - dont seem to be sueful , Mərtəbə is already converted

# Removing Low-Value and Identifier-Like Features

drop_cols = [
    "owner_name",
    "shop_name",
    "shop_title",
    "Mərtəbə"
]

df_model = df_model.drop(columns=drop_cols)

print("Shape after removing low-value features:", df_model.shape)

Shape after removing low-value features: (100775, 28)

In [28]:
# Analyzing the Meaning of Missing Categorical Values

cols_to_check = [
    "İpoteka",
    "Təmir",
    "Otaq sayı",
    "products_label"
]

for col in cols_to_check:
    print(f"\n===== {col} =====")
    print("Missing:", df_model[col].isna().sum())
    print("Missing %:", round(df_model[col].isna().mean() * 100, 2))

===== İpoteka =====
Missing: 67836
Missing %: 67.31

===== Təmir =====
Missing: 6001
Missing %: 5.95

===== Otaq sayı =====
Missing: 9412
Missing %: 9.34

===== products_label =====
Missing: 28145
Missing %: 27.93

In [29]:
# İpoteka: 67.31% missing, it needs further anakysis to see if it is not given or no mortgage

for col in ["İpoteka", "Təmir", "Otaq sayı", "products_label"]:
    print(f"\n===== {col} =====")
    
    print("Price when value is missing:")
    print(df_model.loc[df_model[col].isna(), "price"].describe())
    
    print("\nPrice when value is NOT missing:")
    print(df_model.loc[df_model[col].notna(), "price"].describe())

===== İpoteka =====
Price when value is missing:
count    6.783600e+04
mean     3.504351e+05
std      2.436309e+06
min      1.100000e+01
25%      1.370000e+05
50%      2.150000e+05
75%      3.400000e+05
max      6.000000e+08
Name: price, dtype: float64

Price when value is NOT missing:
count    3.293900e+04
mean     3.257168e+05
std      7.352607e+05
min      1.700000e+03
25%      1.550000e+05
50%      2.230000e+05
75%      3.350000e+05
max      3.600000e+07
Name: price, dtype: float64

===== Təmir =====
Price when value is missing:
count    6.001000e+03
mean     8.031405e+05
std      8.066663e+06
min      8.000000e+02
25%      5.900000e+04
50%      1.700000e+05
75%      4.200000e+05
max      6.000000e+08
Name: price, dtype: float64

Price when value is NOT missing:
count    9.477400e+04
mean     3.131793e+05
std      5.501124e+05
min      1.100000e+01
25%      1.470000e+05
50%      2.200000e+05
75%      3.350000e+05
max      3.600000e+07
Name: price, dtype: float64

===== Otaq sayı =====
Price when value is missing:
count    9.412000e+03
mean     9.465962e+05
std      2.236948e+06
min      1.100000e+01
25%      9.900000e+04
50%      2.950000e+05
75%      8.000000e+05
max      4.000000e+07
Name: price, dtype: float64

Price when value is NOT missing:
count    9.136300e+04
mean     2.801083e+05
std      2.011273e+06
min      7.300000e+01
25%      1.450000e+05
50%      2.150000e+05
75%      3.220250e+05
max      6.000000e+08
Name: price, dtype: float64

===== products_label =====
Price when value is missing:
count    2.814500e+04
mean     3.136199e+05
std      3.662944e+06
min      1.100000e+01
25%      1.050000e+05
50%      1.670000e+05
75%      2.800000e+05
max      6.000000e+08
Name: price, dtype: float64

Price when value is NOT missing:
count    7.263000e+04
mean     3.534912e+05
std      7.678085e+05
min      4.000000e+02
25%      1.600000e+05
50%      2.350000e+05
75%      3.500000e+05
max      3.900000e+07
Name: price, dtype: float64

In [ ]:
# here we see some missing values contain useful information about price, so we shouldnt fill them yet

In [ ]:
# Check whether missing values are related to other property features,  like what kind of properties have it missing
print("Room count missing:")
display(df_model[df_model["Otaq sayı"].isna()][
    ["price", "Sahə", "location", "Təmir", "İpoteka"]
].head(20))

print("\nRoom count available:")
display(df_model[df_model["Otaq sayı"].notna()][
    ["price", "Sahə", "location", "Təmir", "İpoteka"]
].head(20))

Room count missing:

         price      Sahə              location   Təmir İpoteka
3      95000.0    130 m²          Qaraçuxur q.     var     var
8    3000000.0    485 m²             Nizami m.     var     NaN
10   1050000.0    360 m²            Masazır q.     NaN     NaN
11    275000.0     45 m²       Qara Qarayev m.     var     var
18    260000.0     70 m²             28 May m.  yoxdur     NaN
22     55000.0    12 sot               Binə q.     NaN     NaN
28    170000.0     45 m²      Köhnə Günəşli q.     var     NaN
34     23000.0    380 m²          Nərimanov r.  yoxdur     NaN
35   1550000.0  50.3 sot              Ulduz m.     NaN     NaN
37    580000.0    100 m²            Əhmədli m.     var     NaN
39    600000.0    250 m²      Köhnə Günəşli q.     var     NaN
75     64000.0     6 sot            Şüvəlan q.     NaN     var
81    120000.0     5 sot            Şüvəlan q.     NaN     var
120   850000.0    150 m²  Şah İsmayıl Xətai m.     var     NaN
140   580000.0    120 m²        Memar Əcəmi m.     var     NaN
142    24000.0    16 sot           Naxçıvan MR     NaN     NaN
143  1650000.0    400 m²       Həzi Aslanov m.     var     NaN
144  2500000.0   1450 m²          Neftçilər m.     var     NaN
145   275000.0     55 m²             Nəsimi m.     var     NaN
172    80000.0  7000 sot            Maştağa q.     NaN     NaN

Room count available:

       price      Sahə               location   Təmir İpoteka
0   499999.0    145 m²              Səbail r.     var     NaN
1    77000.0     90 m²            Biləcəri q.     var     NaN
2    92000.0     60 m²         İnşaatçılar m.     var     NaN
4   220000.0    100 m²             Əhmədli m.     var     NaN
5   650000.0    130 m²               Sahil m.     var     NaN
6   259000.0     70 m²               Sahil m.     var     NaN
7   279000.0    153 m²               Bayıl q.  yoxdur     NaN
9   262000.0    104 m²         Memar Əcəmi m.     var     NaN
12  153000.0     85 m²         İnşaatçılar m.     var     NaN
13  450000.0    940 m²             Novxanı q.  yoxdur     NaN
14  330000.0    160 m²   Nəriman Nərimanov m.     var     var
15  195000.0     56 m²            8 Noyabr m.     var     var
16  150000.0     70 m²           Neftçilər m.     var     NaN
17   77000.0     72 m²             Masazır q.     var     NaN
19  455000.0    225 m²             Əhmədli m.     var     var
20  770000.0  230.6 m²  Elmlər Akademiyası m.  yoxdur     NaN
21  150000.0    120 m²             Masazır q.     var     NaN
23   65500.0     54 m²             Masazır q.     var     NaN
24  143000.0   82.2 m²        Həzi Aslanov m.  yoxdur     NaN
25  172000.0     75 m²           Bakıxanov q.     var     NaN

In [ ]:
# we see that, the missing Otaq sayı properties are not all one type  ( like not just houses/apartments,but also land/commercial )
# for now lets keep thema

In [31]:
# lets do the same for "Temir"
# Check what kind of properties have missing repair information

print("Repair information missing:")
display(df_model[df_model["Təmir"].isna()][
    ["price", "Sahə", "location", "Otaq sayı", "İpoteka"]
].head(20))

print("\nRepair information available:")
display(df_model[df_model["Təmir"].notna()][
    ["price", "Sahə", "location", "Otaq sayı", "İpoteka"]
].head(20))

Repair information missing:

         price      Sahə              location  Otaq sayı İpoteka
10   1050000.0    360 m²            Masazır q.        NaN     NaN
22     55000.0    12 sot               Binə q.        NaN     NaN
35   1550000.0  50.3 sot              Ulduz m.        NaN     NaN
45    195000.0    250 m²           Biləcəri q.        7.0     NaN
75     64000.0     6 sot            Şüvəlan q.        NaN     var
78    360000.0    128 m²  Şah İsmayıl Xətai m.        3.0     NaN
81    120000.0     5 sot            Şüvəlan q.        NaN     var
111   365000.0    160 m²           Mərdəkan q.        4.0     var
142    24000.0    16 sot           Naxçıvan MR        NaN     NaN
147   475000.0    178 m²            Yasamal r.        4.0     var
172    80000.0  7000 sot            Maştağa q.        NaN     NaN
181   165000.0    10 sot            Buzovna q.        NaN     var
264    56000.0     8 sot             Hövsan q.        NaN     NaN
290   295000.0     6 sot           Badamdar q.        NaN     NaN
340    43000.0    100 m²            Sabunçu q.        3.0     NaN
364  1600000.0   1600 m²               Qala q.        NaN     NaN
395  1400000.0    600 m²           Mərdəkan q.        NaN     NaN
444   120000.0     7 sot            Şüvəlan q.        NaN     var
457   460000.0    235 m²           Ağ şəhər q.        4.0     var
482    28800.0     6 sot           Sulutəpə q.        NaN     NaN

Repair information available:

        price      Sahə               location  Otaq sayı İpoteka
0    499999.0    145 m²              Səbail r.        4.0     NaN
1     77000.0     90 m²            Biləcəri q.        4.0     NaN
2     92000.0     60 m²         İnşaatçılar m.        3.0     NaN
3     95000.0    130 m²           Qaraçuxur q.        NaN     var
4    220000.0    100 m²             Əhmədli m.        3.0     NaN
5    650000.0    130 m²               Sahil m.        4.0     NaN
6    259000.0     70 m²               Sahil m.        3.0     NaN
7    279000.0    153 m²               Bayıl q.        3.0     NaN
8   3000000.0    485 m²              Nizami m.        NaN     NaN
9    262000.0    104 m²         Memar Əcəmi m.        3.0     NaN
11   275000.0     45 m²        Qara Qarayev m.        NaN     var
12   153000.0     85 m²         İnşaatçılar m.        4.0     NaN
13   450000.0    940 m²             Novxanı q.        9.0     NaN
14   330000.0    160 m²   Nəriman Nərimanov m.        3.0     var
15   195000.0     56 m²            8 Noyabr m.        2.0     var
16   150000.0     70 m²           Neftçilər m.        3.0     NaN
17    77000.0     72 m²             Masazır q.        3.0     NaN
18   260000.0     70 m²              28 May m.        NaN     NaN
19   455000.0    225 m²             Əhmədli m.        5.0     var
20   770000.0  230.6 m²  Elmlər Akademiyası m.        5.0     NaN

In [ ]:
# so its similar to the  Otaq sayi, missing Təmir occurs across different property types, so lets keep it

In [32]:
# Next, is time to analyse İpoteka because it has 67.31% missing values

print("Mortgage information missing:")
display(df_model[df_model["İpoteka"].isna()][
    ["price", "Sahə", "location", "Otaq sayı", "Təmir"]
].head(20))

print("\nMortgage information available:")
display(df_model[df_model["İpoteka"].notna()][
    ["price", "Sahə", "location", "Otaq sayı", "Təmir"]
].head(20))

Mortgage information missing:

        price      Sahə               location  Otaq sayı   Təmir
0    499999.0    145 m²              Səbail r.        4.0     var
1     77000.0     90 m²            Biləcəri q.        4.0     var
2     92000.0     60 m²         İnşaatçılar m.        3.0     var
4    220000.0    100 m²             Əhmədli m.        3.0     var
5    650000.0    130 m²               Sahil m.        4.0     var
6    259000.0     70 m²               Sahil m.        3.0     var
7    279000.0    153 m²               Bayıl q.        3.0  yoxdur
8   3000000.0    485 m²              Nizami m.        NaN     var
9    262000.0    104 m²         Memar Əcəmi m.        3.0     var
10  1050000.0    360 m²             Masazır q.        NaN     NaN
12   153000.0     85 m²         İnşaatçılar m.        4.0     var
13   450000.0    940 m²             Novxanı q.        9.0  yoxdur
16   150000.0     70 m²           Neftçilər m.        3.0     var
17    77000.0     72 m²             Masazır q.        3.0     var
18   260000.0     70 m²              28 May m.        NaN  yoxdur
20   770000.0  230.6 m²  Elmlər Akademiyası m.        5.0  yoxdur
21   150000.0    120 m²             Masazır q.        3.0     var
22    55000.0    12 sot                Binə q.        NaN     NaN
23    65500.0     54 m²             Masazır q.        2.0     var
24   143000.0   82.2 m²        Həzi Aslanov m.        2.0  yoxdur

Mortgage information available:

       price    Sahə              location  Otaq sayı Təmir
3    95000.0  130 m²          Qaraçuxur q.        NaN   var
11  275000.0   45 m²       Qara Qarayev m.        NaN   var
14  330000.0  160 m²  Nəriman Nərimanov m.        3.0   var
15  195000.0   56 m²           8 Noyabr m.        2.0   var
19  455000.0  225 m²            Əhmədli m.        5.0   var
27  680000.0  260 m²              Sahil m.        4.0   var
32  135000.0  100 m²            Görədil q.        4.0   var
36  143000.0   65 m²        Memar Əcəmi m.        2.0   var
38  133000.0   52 m²             Nəsimi m.        2.0   var
40  282000.0  140 m²             Nəsimi m.        3.0   var
41  158000.0   78 m²             Nəsimi m.        2.0   var
42  161000.0   78 m²        Memar Əcəmi m.        2.0   var
43  155000.0   68 m²             Nəsimi m.        2.0   var
44  164000.0   65 m²             Nəsimi m.        3.0   var
46  170000.0   60 m²        Memar Əcəmi m.        2.0   var
47  270000.0  130 m²             Nəsimi m.        3.0   var
49  125000.0   70 m²             Nəsimi m.        2.0   var
50  142000.0   60 m²        Memar Əcəmi m.        2.0   var
52  280000.0  126 m²       Həzi Aslanov m.        3.0   var
53  270000.0   95 m²  Nəriman Nərimanov m.        3.0   var

In [33]:
# Check the distribution of mortgage information
print(df_model["İpoteka"].value_counts(dropna=False))

İpoteka
NaN    67836
var    32939
Name: count, dtype: int64

In [34]:
# So there are only two states in the data: var and missing
# lets check whether var properties have any obvious pattern

print("Mortgage = var:")
display(df_model[df_model["İpoteka"] == "var"][
    ["price", "Sahə", "location", "Otaq sayı", "Təmir"]
].head(20))

print("\nMortgage = missing:")
display(df_model[df_model["İpoteka"].isna()][
    ["price", "Sahə", "location", "Otaq sayı", "Təmir"]
].head(20))

Mortgage = var:

       price    Sahə              location  Otaq sayı Təmir
3    95000.0  130 m²          Qaraçuxur q.        NaN   var
11  275000.0   45 m²       Qara Qarayev m.        NaN   var
14  330000.0  160 m²  Nəriman Nərimanov m.        3.0   var
15  195000.0   56 m²           8 Noyabr m.        2.0   var
19  455000.0  225 m²            Əhmədli m.        5.0   var
27  680000.0  260 m²              Sahil m.        4.0   var
32  135000.0  100 m²            Görədil q.        4.0   var
36  143000.0   65 m²        Memar Əcəmi m.        2.0   var
38  133000.0   52 m²             Nəsimi m.        2.0   var
40  282000.0  140 m²             Nəsimi m.        3.0   var
41  158000.0   78 m²             Nəsimi m.        2.0   var
42  161000.0   78 m²        Memar Əcəmi m.        2.0   var
43  155000.0   68 m²             Nəsimi m.        2.0   var
44  164000.0   65 m²             Nəsimi m.        3.0   var
46  170000.0   60 m²        Memar Əcəmi m.        2.0   var
47  270000.0  130 m²             Nəsimi m.        3.0   var
49  125000.0   70 m²             Nəsimi m.        2.0   var
50  142000.0   60 m²        Memar Əcəmi m.        2.0   var
52  280000.0  126 m²       Həzi Aslanov m.        3.0   var
53  270000.0   95 m²  Nəriman Nərimanov m.        3.0   var

Mortgage = missing:

        price      Sahə               location  Otaq sayı   Təmir
0    499999.0    145 m²              Səbail r.        4.0     var
1     77000.0     90 m²            Biləcəri q.        4.0     var
2     92000.0     60 m²         İnşaatçılar m.        3.0     var
4    220000.0    100 m²             Əhmədli m.        3.0     var
5    650000.0    130 m²               Sahil m.        4.0     var
6    259000.0     70 m²               Sahil m.        3.0     var
7    279000.0    153 m²               Bayıl q.        3.0  yoxdur
8   3000000.0    485 m²              Nizami m.        NaN     var
9    262000.0    104 m²         Memar Əcəmi m.        3.0     var
10  1050000.0    360 m²             Masazır q.        NaN     NaN
12   153000.0     85 m²         İnşaatçılar m.        4.0     var
13   450000.0    940 m²             Novxanı q.        9.0  yoxdur
16   150000.0     70 m²           Neftçilər m.        3.0     var
17    77000.0     72 m²             Masazır q.        3.0     var
18   260000.0     70 m²              28 May m.        NaN  yoxdur
20   770000.0  230.6 m²  Elmlər Akademiyası m.        5.0  yoxdur
21   150000.0    120 m²             Masazır q.        3.0     var
22    55000.0    12 sot                Binə q.        NaN     NaN
23    65500.0     54 m²             Masazır q.        2.0     var
24   143000.0   82.2 m²        Həzi Aslanov m.        2.0  yoxdur

In [ ]:
# Missing mortgage values appear across different property types
# locations, prices, and room counts
# so, NaN does not clearly mean "yoxdur"
# We keep these values missing for now

In [35]:
# lets move to products_label, because it has 27.93% missing values
print("Products_label missing:")
display(df_model[df_model["products_label"].isna()][
    ["price", "Sahə", "location", "Otaq sayı", "Təmir", "İpoteka"]
].head(20))

print("\nProducts_label available:")
display(df_model[df_model["products_label"].notna()][
    ["price", "Sahə", "location", "Otaq sayı", "Təmir", "İpoteka"]
].head(20))

Products_label missing:

        price      Sahə               location  Otaq sayı   Təmir İpoteka
0    499999.0    145 m²              Səbail r.        4.0     var     NaN
1     77000.0     90 m²            Biləcəri q.        4.0     var     NaN
2     92000.0     60 m²         İnşaatçılar m.        3.0     var     NaN
3     95000.0    130 m²           Qaraçuxur q.        NaN     var     var
5    650000.0    130 m²               Sahil m.        4.0     var     NaN
6    259000.0     70 m²               Sahil m.        3.0     var     NaN
7    279000.0    153 m²               Bayıl q.        3.0  yoxdur     NaN
8   3000000.0    485 m²              Nizami m.        NaN     var     NaN
10  1050000.0    360 m²             Masazır q.        NaN     NaN     NaN
11   275000.0     45 m²        Qara Qarayev m.        NaN     var     var
13   450000.0    940 m²             Novxanı q.        9.0  yoxdur     NaN
16   150000.0     70 m²           Neftçilər m.        3.0     var     NaN
17    77000.0     72 m²             Masazır q.        3.0     var     NaN
18   260000.0     70 m²              28 May m.        NaN  yoxdur     NaN
19   455000.0    225 m²             Əhmədli m.        5.0     var     var
20   770000.0  230.6 m²  Elmlər Akademiyası m.        5.0  yoxdur     NaN
21   150000.0    120 m²             Masazır q.        3.0     var     NaN
22    55000.0    12 sot                Binə q.        NaN     NaN     NaN
23    65500.0     54 m²             Masazır q.        2.0     var     NaN
24   143000.0   82.2 m²        Həzi Aslanov m.        2.0  yoxdur     NaN

Products_label available:

       price    Sahə              location  Otaq sayı   Təmir İpoteka
4   220000.0  100 m²            Əhmədli m.        3.0     var     NaN
9   262000.0  104 m²        Memar Əcəmi m.        3.0     var     NaN
12  153000.0   85 m²        İnşaatçılar m.        4.0     var     NaN
14  330000.0  160 m²  Nəriman Nərimanov m.        3.0     var     var
15  195000.0   56 m²           8 Noyabr m.        2.0     var     var
27  680000.0  260 m²              Sahil m.        4.0     var     var
28  170000.0   45 m²      Köhnə Günəşli q.        NaN     var     NaN
29   95000.0   50 m²          Neftçilər m.        2.0     var     NaN
34   23000.0  380 m²          Nərimanov r.        NaN  yoxdur     NaN
36  143000.0   65 m²        Memar Əcəmi m.        2.0     var     var
37  580000.0  100 m²            Əhmədli m.        NaN     var     NaN
38  133000.0   52 m²             Nəsimi m.        2.0     var     var
39  600000.0  250 m²      Köhnə Günəşli q.        NaN     var     NaN
40  282000.0  140 m²             Nəsimi m.        3.0     var     var
41  158000.0   78 m²             Nəsimi m.        2.0     var     var
42  161000.0   78 m²        Memar Əcəmi m.        2.0     var     var
43  155000.0   68 m²             Nəsimi m.        2.0     var     var
44  164000.0   65 m²             Nəsimi m.        3.0     var     var
46  170000.0   60 m²        Memar Əcəmi m.        2.0     var     var
47  270000.0  130 m²             Nəsimi m.        3.0     var     var

In [36]:
# Check whether missing products_label is associated with different property types

print("Products_label missing:")
display(df_model[df_model["products_label"].isna()][
    ["price", "Sahə", "location", "Otaq sayı", "Təmir", "İpoteka"]
].head(20))

print("\nProducts_label available:")
display(df_model[df_model["products_label"].notna()][
    ["price", "Sahə", "location", "Otaq sayı", "Təmir", "İpoteka"]
].head(20))

Products_label missing:

        price      Sahə               location  Otaq sayı   Təmir İpoteka
0    499999.0    145 m²              Səbail r.        4.0     var     NaN
1     77000.0     90 m²            Biləcəri q.        4.0     var     NaN
2     92000.0     60 m²         İnşaatçılar m.        3.0     var     NaN
3     95000.0    130 m²           Qaraçuxur q.        NaN     var     var
5    650000.0    130 m²               Sahil m.        4.0     var     NaN
6    259000.0     70 m²               Sahil m.        3.0     var     NaN
7    279000.0    153 m²               Bayıl q.        3.0  yoxdur     NaN
8   3000000.0    485 m²              Nizami m.        NaN     var     NaN
10  1050000.0    360 m²             Masazır q.        NaN     NaN     NaN
11   275000.0     45 m²        Qara Qarayev m.        NaN     var     var
13   450000.0    940 m²             Novxanı q.        9.0  yoxdur     NaN
16   150000.0     70 m²           Neftçilər m.        3.0     var     NaN
17    77000.0     72 m²             Masazır q.        3.0     var     NaN
18   260000.0     70 m²              28 May m.        NaN  yoxdur     NaN
19   455000.0    225 m²             Əhmədli m.        5.0     var     var
20   770000.0  230.6 m²  Elmlər Akademiyası m.        5.0  yoxdur     NaN
21   150000.0    120 m²             Masazır q.        3.0     var     NaN
22    55000.0    12 sot                Binə q.        NaN     NaN     NaN
23    65500.0     54 m²             Masazır q.        2.0     var     NaN
24   143000.0   82.2 m²        Həzi Aslanov m.        2.0  yoxdur     NaN

Products_label available:

       price    Sahə              location  Otaq sayı   Təmir İpoteka
4   220000.0  100 m²            Əhmədli m.        3.0     var     NaN
9   262000.0  104 m²        Memar Əcəmi m.        3.0     var     NaN
12  153000.0   85 m²        İnşaatçılar m.        4.0     var     NaN
14  330000.0  160 m²  Nəriman Nərimanov m.        3.0     var     var
15  195000.0   56 m²           8 Noyabr m.        2.0     var     var
27  680000.0  260 m²              Sahil m.        4.0     var     var
28  170000.0   45 m²      Köhnə Günəşli q.        NaN     var     NaN
29   95000.0   50 m²          Neftçilər m.        2.0     var     NaN
34   23000.0  380 m²          Nərimanov r.        NaN  yoxdur     NaN
36  143000.0   65 m²        Memar Əcəmi m.        2.0     var     var
37  580000.0  100 m²            Əhmədli m.        NaN     var     NaN
38  133000.0   52 m²             Nəsimi m.        2.0     var     var
39  600000.0  250 m²      Köhnə Günəşli q.        NaN     var     NaN
40  282000.0  140 m²             Nəsimi m.        3.0     var     var
41  158000.0   78 m²             Nəsimi m.        2.0     var     var
42  161000.0   78 m²        Memar Əcəmi m.        2.0     var     var
43  155000.0   68 m²             Nəsimi m.        2.0     var     var
44  164000.0   65 m²             Nəsimi m.        3.0     var     var
46  170000.0   60 m²        Memar Əcəmi m.        2.0     var     var
47  270000.0  130 m²             Nəsimi m.        3.0     var     var

In [37]:
print("===== products_label =====")

print("Price when products_label is missing:")
print(df_model.loc[df_model["products_label"].isna(), "price"].describe())

print("\nPrice when products_label is NOT missing:")
print(df_model.loc[df_model["products_label"].notna(), "price"].describe())

===== products_label =====
Price when products_label is missing:
count    2.814500e+04
mean     3.136199e+05
std      3.662944e+06
min      1.100000e+01
25%      1.050000e+05
50%      1.670000e+05
75%      2.800000e+05
max      6.000000e+08
Name: price, dtype: float64

Price when products_label is NOT missing:
count    7.263000e+04
mean     3.534912e+05
std      7.678085e+05
min      4.000000e+02
25%      1.600000e+05
50%      2.350000e+05
75%      3.500000e+05
max      3.900000e+07
Name: price, dtype: float64

In [38]:
# we should check which actual products_label categories exist
print("Products_label value counts:")
print(df_model["products_label"].value_counts(dropna=False))

Products_label value counts:
products_label
Agentlik    71981
NaN         28145
Kompleks      649
Name: count, dtype: int64

In [39]:
# we should check whether products_label actually has predictive value for price
print("Price by products_label:")
display(
    df_model.groupby(
        df_model["products_label"].fillna("Missing")
    )["price"].describe()
)

Price by products_label:

,count,mean,std,min,25%,50%,75%,max
products_label,,,,,,,,
Agentlik,71981.0,351587.072589,7.681455e+05,400.0,160000.0,235000.0,350000.0,39000000.0
Kompleks,649.0,564681.952234,6.984724e+05,65410.0,281248.0,396090.0,624132.0,6800000.0
Missing,28145.0,313619.889039,3.662944e+06,11.0,105000.0,167000.0,280000.0,600000000.0

In [40]:
# Check what kind of properties have missing products_label information

print("Products_label missing:")
display(df_model[df_model["products_label"].isna()][
    ["price", "Sahə", "location", "Otaq sayı", "Təmir", "İpoteka"]
].head(20))

print("\nProducts_label available:")
display(df_model[df_model["products_label"].notna()][
    ["price", "Sahə", "location", "Otaq sayı", "Təmir", "İpoteka"]
].head(20))

Products_label missing:

        price      Sahə               location  Otaq sayı   Təmir İpoteka
0    499999.0    145 m²              Səbail r.        4.0     var     NaN
1     77000.0     90 m²            Biləcəri q.        4.0     var     NaN
2     92000.0     60 m²         İnşaatçılar m.        3.0     var     NaN
3     95000.0    130 m²           Qaraçuxur q.        NaN     var     var
5    650000.0    130 m²               Sahil m.        4.0     var     NaN
6    259000.0     70 m²               Sahil m.        3.0     var     NaN
7    279000.0    153 m²               Bayıl q.        3.0  yoxdur     NaN
8   3000000.0    485 m²              Nizami m.        NaN     var     NaN
10  1050000.0    360 m²             Masazır q.        NaN     NaN     NaN
11   275000.0     45 m²        Qara Qarayev m.        NaN     var     var
13   450000.0    940 m²             Novxanı q.        9.0  yoxdur     NaN
16   150000.0     70 m²           Neftçilər m.        3.0     var     NaN
17    77000.0     72 m²             Masazır q.        3.0     var     NaN
18   260000.0     70 m²              28 May m.        NaN  yoxdur     NaN
19   455000.0    225 m²             Əhmədli m.        5.0     var     var
20   770000.0  230.6 m²  Elmlər Akademiyası m.        5.0  yoxdur     NaN
21   150000.0    120 m²             Masazır q.        3.0     var     NaN
22    55000.0    12 sot                Binə q.        NaN     NaN     NaN
23    65500.0     54 m²             Masazır q.        2.0     var     NaN
24   143000.0   82.2 m²        Həzi Aslanov m.        2.0  yoxdur     NaN

Products_label available:

       price    Sahə              location  Otaq sayı   Təmir İpoteka
4   220000.0  100 m²            Əhmədli m.        3.0     var     NaN
9   262000.0  104 m²        Memar Əcəmi m.        3.0     var     NaN
12  153000.0   85 m²        İnşaatçılar m.        4.0     var     NaN
14  330000.0  160 m²  Nəriman Nərimanov m.        3.0     var     var
15  195000.0   56 m²           8 Noyabr m.        2.0     var     var
27  680000.0  260 m²              Sahil m.        4.0     var     var
28  170000.0   45 m²      Köhnə Günəşli q.        NaN     var     NaN
29   95000.0   50 m²          Neftçilər m.        2.0     var     NaN
34   23000.0  380 m²          Nərimanov r.        NaN  yoxdur     NaN
36  143000.0   65 m²        Memar Əcəmi m.        2.0     var     var
37  580000.0  100 m²            Əhmədli m.        NaN     var     NaN
38  133000.0   52 m²             Nəsimi m.        2.0     var     var
39  600000.0  250 m²      Köhnə Günəşli q.        NaN     var     NaN
40  282000.0  140 m²             Nəsimi m.        3.0     var     var
41  158000.0   78 m²             Nəsimi m.        2.0     var     var
42  161000.0   78 m²        Memar Əcəmi m.        2.0     var     var
43  155000.0   68 m²             Nəsimi m.        2.0     var     var
44  164000.0   65 m²             Nəsimi m.        3.0     var     var
46  170000.0   60 m²        Memar Əcəmi m.        2.0     var     var
47  270000.0  130 m²             Nəsimi m.        3.0     var     var

In [41]:
# missing group has a very different distribution, especially the lower median, but also contains extreme values
#so lets Treat missing as an explicit category
df_model["products_label"] = df_model["products_label"].fillna("Missing")

In [42]:
# final, determine whether products_label missingness is associated with other categorical variables, especially location, Təmir, and İpoteka
for col in ["location", "Təmir", "İpoteka"]:
    print(f"\n===== {col} vs products_label =====")
    print(
        pd.crosstab(
            df_model[col],
            df_model["products_label"],
            normalize="index"
        ).round(3)
    )

===== location vs products_label =====
products_label      Agentlik  Kompleks  Missing
location
1-ci mikrorayon q.     0.000     0.000    1.000
2-ci Alatava q.        0.833     0.000    0.167
2-ci mikrorayon q.     0.222     0.000    0.778
20 Yanvar m.           0.765     0.018    0.216
20-ci sahə q.          0.380     0.000    0.620
...                      ...       ...      ...
Şərq q.                1.000     0.000    0.000
Əhmədli m.             0.653     0.000    0.347
Əhmədli q.             0.537     0.000    0.463
Ələt q.                0.579     0.000    0.421
Əmircan q.             0.264     0.000    0.736

[142 rows x 3 columns]

===== Təmir vs products_label =====
products_label  Agentlik  Kompleks  Missing
Təmir
var                0.735     0.003    0.262
yoxdur             0.706     0.031    0.263

===== İpoteka vs products_label =====
products_label  Agentlik  Kompleks  Missing
İpoteka
var                0.753     0.011    0.236

In [ ]:
# so, missing products_label does not consistently correspond to either Agentlik or `Kompleks.

In [43]:
df["İpoteka"].value_counts(dropna=False)

İpoteka
NaN    67836
var    32939
Name: count, dtype: int64

In [44]:
df["İpoteka"] = df["İpoteka"].fillna("missing")

In [45]:
df["İpoteka"].value_counts()

İpoteka
missing    67836
var        32939
Name: count, dtype: int64

In [46]:
# lets see exactly what values Təmir contains
df["Təmir"].value_counts(dropna=False)

Təmir
var       81612
yoxdur    13162
NaN        6001
Name: count, dtype: int64

In [47]:
df["Təmir"] = df["Təmir"].fillna("missing")

In [48]:
df["Təmir"].value_counts()

Təmir
var        81612
yoxdur     13162
missing     6001
Name: count, dtype: int64

In [49]:
df["Otaq sayı"].value_counts(dropna=False).sort_index()

Otaq sayı
1.0      2618
2.0     27435
3.0     36191
4.0     15673
5.0      4850
6.0      2306
7.0       978
8.0       582
9.0       241
10.0      247
11.0       43
12.0       87
13.0       10
14.0       20
15.0       35
16.0       19
18.0        4
19.0        5
20.0       19
NaN      9412
Name: count, dtype: int64

In [50]:
# We need to check which missing room numbers are actually unknown and which properties dont have rooms at all (like land)
# First, lets investigate Sahə
df["Sahə"].value_counts(dropna=False).head(30)
df["Sahə"].dtype
df[["Sahə", "Otaq sayı"]].head(20)

      Sahə  Otaq sayı
0   145 m²        4.0
1    90 m²        4.0
2    60 m²        3.0
3   130 m²        NaN
4   100 m²        3.0
5   130 m²        4.0
6    70 m²        3.0
7   153 m²        3.0
8   485 m²        NaN
9   104 m²        3.0
10  360 m²        NaN
11   45 m²        NaN
12   85 m²        4.0
13  940 m²        9.0
14  160 m²        3.0
15   56 m²        2.0
16   70 m²        3.0
17   72 m²        3.0
18   70 m²        NaN
19  225 m²        5.0

In [51]:
# so next we need to separate land (sot) from buildings (m²) before filling Otaq sayı.
df["area_unit"] = df["Sahə"].str.extract(r"(m²|sot)")
df["area_unit"].value_counts(dropna=False)

area_unit
m²     95856
sot     4919
Name: count, dtype: int64

In [52]:
# how many missing rooms are in each
df.groupby("area_unit")["Otaq sayı"].apply(lambda x: x.isna().sum())

area_unit
m²     4493
sot    4919
Name: Otaq sayı, dtype: int64

In [53]:
# room count depends on area or not
df[df["area_unit"] == "m²"].groupby("Otaq sayı")["Sahə"].count()

Otaq sayı
1.0      2618
2.0     27435
3.0     36191
4.0     15673
5.0      4850
6.0      2306
7.0       978
8.0       582
9.0       241
10.0      247
11.0       43
12.0       87
13.0       10
14.0       20
15.0       35
16.0       19
18.0        4
19.0        5
20.0       19
Name: Sahə, dtype: int64

In [54]:
# inspect their area
df[df["Otaq sayı"].isna() & (df["area_unit"] == "m²")]["Sahə"].head(30)

3        130 m²
8        485 m²
10       360 m²
11        45 m²
18        70 m²
28        45 m²
34       380 m²
37       100 m²
39       250 m²
120      150 m²
140      120 m²
143      400 m²
144     1450 m²
145       55 m²
222       12 m²
306      108 m²
328       83 m²
329      200 m²
364     1600 m²
372      110 m²
394     19.5 m²
395      600 m²
411       55 m²
414      435 m²
418      134 m²
420    158.5 m²
422      361 m²
424      115 m²
426       50 m²
433      100 m²
Name: Sahə, dtype: object

In [55]:
df[df["Otaq sayı"].isna() & (df["area_unit"] == "m²")]["Sahə"].value_counts().head(20)

Sahə
100 m²     185
60 m²      127
200 m²     117
80 m²       93
400 m²      92
300 m²      88
120 m²      85
500 m²      77
250 m²      76
50 m²       74
160 m²      74
90 m²       67
75 m²       63
150 m²      63
70 m²       61
40 m²       56
180 m²      54
450 m²      53
1000 m²     52
110 m²      52
Name: count, dtype: int64

In [ ]:
# we dont need to impute Otaq sayı

In [56]:
# Next, products_label
df["products_label"].value_counts(dropna=False)

products_label
Agentlik    71981
NaN         28145
Kompleks      649
Name: count, dtype: int64

In [57]:
df["products_label"] = df["products_label"].fillna("missing")

In [58]:
df["products_label"].value_counts()

products_label
Agentlik    71981
missing     28145
Kompleks      649
Name: count, dtype: int64

In [59]:
# now Sahə is text, we need to turn that into a numeric area feature
df["area_value"] = df["Sahə"].str.extract(r"([\d.]+)").astype(float)
df[["Sahə", "area_unit", "area_value"]].head(20)

      Sahə area_unit  area_value
0   145 m²        m²       145.0
1    90 m²        m²        90.0
2    60 m²        m²        60.0
3   130 m²        m²       130.0
4   100 m²        m²       100.0
5   130 m²        m²       130.0
6    70 m²        m²        70.0
7   153 m²        m²       153.0
8   485 m²        m²       485.0
9   104 m²        m²       104.0
10  360 m²        m²       360.0
11   45 m²        m²        45.0
12   85 m²        m²        85.0
13  940 m²        m²       940.0
14  160 m²        m²       160.0
15   56 m²        m²        56.0
16   70 m²        m²        70.0
17   72 m²        m²        72.0
18   70 m²        m²        70.0
19  225 m²        m²       225.0

In [60]:
# IN THE DATA there we have both m² and sot
# we need to convert everything to a common unit
df['area_m2'] = df['area_value']

df.loc[df['area_unit'] == 'sot', 'area_m2'] = (
    df.loc[df['area_unit'] == 'sot', 'area_value'] * 100
)

In [61]:
# Were creating price_per_m2 to detect unrealistic property prices and identify potential outliers or data-entry errors
df['area_m2'] = df['area_value']

df.loc[df['area_unit'] == 'sot', 'area_m2'] = (
    df.loc[df['area_unit'] == 'sot', 'area_value'] * 100
)

In [62]:
df[['Sahə', 'area_unit', 'area_value', 'area_m2']].head(20)

      Sahə area_unit  area_value  area_m2
0   145 m²        m²       145.0    145.0
1    90 m²        m²        90.0     90.0
2    60 m²        m²        60.0     60.0
3   130 m²        m²       130.0    130.0
4   100 m²        m²       100.0    100.0
5   130 m²        m²       130.0    130.0
6    70 m²        m²        70.0     70.0
7   153 m²        m²       153.0    153.0
8   485 m²        m²       485.0    485.0
9   104 m²        m²       104.0    104.0
10  360 m²        m²       360.0    360.0
11   45 m²        m²        45.0     45.0
12   85 m²        m²        85.0     85.0
13  940 m²        m²       940.0    940.0
14  160 m²        m²       160.0    160.0
15   56 m²        m²        56.0     56.0
16   70 m²        m²        70.0     70.0
17   72 m²        m²        72.0     72.0
18   70 m²        m²        70.0     70.0
19  225 m²        m²       225.0    225.0

In [63]:
df['price_per_m2'] = df['price'] / df['area_m2']

In [64]:
df[['price', 'Sahə', 'area_m2', 'price_per_m2']].head(20)

        price    Sahə  area_m2  price_per_m2
0    499999.0  145 m²    145.0   3448.268966
1     77000.0   90 m²     90.0    855.555556
2     92000.0   60 m²     60.0   1533.333333
3     95000.0  130 m²    130.0    730.769231
4    220000.0  100 m²    100.0   2200.000000
5    650000.0  130 m²    130.0   5000.000000
6    259000.0   70 m²     70.0   3700.000000
7    279000.0  153 m²    153.0   1823.529412
8   3000000.0  485 m²    485.0   6185.567010
9    262000.0  104 m²    104.0   2519.230769
10  1050000.0  360 m²    360.0   2916.666667
11   275000.0   45 m²     45.0   6111.111111
12   153000.0   85 m²     85.0   1800.000000
13   450000.0  940 m²    940.0    478.723404
14   330000.0  160 m²    160.0   2062.500000
15   195000.0   56 m²     56.0   3482.142857
16   150000.0   70 m²     70.0   2142.857143
17    77000.0   72 m²     72.0   1069.444444
18   260000.0   70 m²     70.0   3714.285714
19   455000.0  225 m²    225.0   2022.222222

In [65]:
df['price_per_m2'].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
)

count    1.007750e+05
mean     2.321759e+03
std      1.042945e+04
min      2.500000e-04
1%       4.900000e+01
5%       4.500000e+02
25%      1.675000e+03
50%      2.214286e+03
75%      2.730496e+03
95%      3.827777e+03
99%      6.666667e+03
max      3.000000e+06
Name: price_per_m2, dtype: float64

In [66]:
# there are extreme values
df.nlargest(20, 'price_per_m2')[[
    'price', 'Sahə', 'area_m2', 'price_per_m2', 'location'
]]
df.nsmallest(20, 'price_per_m2')[[
    'price', 'Sahə', 'area_m2', 'price_per_m2', 'location'
]]

         price        Sahə     area_m2  price_per_m2     location
4736    2500.0  100000 sot  10000000.0      0.000250   Fatmayı q.
9746    2500.0  100000 sot  10000000.0      0.000250   Fatmayı q.
21517   2500.0  100000 sot  10000000.0      0.000250   Fatmayı q.
75857   3000.0  100000 sot  10000000.0      0.000300   Fatmayı q.
8321     800.0    2500 sot    250000.0      0.003200      Zirə q.
3348    3500.0    4000 sot    400000.0      0.008750   Buzovna q.
89280   1000.0     200 sot     20000.0      0.050000     Şıxov q.
75936  30000.0    3500 sot    350000.0      0.085714       Xaçmaz
172    80000.0    7000 sot    700000.0      0.114286   Maştağa q.
38666     11.0       89 m²        89.0      0.123596  Ağ şəhər q.
23304   1950.0     100 sot     10000.0      0.195000    Hövsan q.
35863   1950.0     100 sot     10000.0      0.195000    Hövsan q.
86013   1950.0     100 sot     10000.0      0.195000    Hövsan q.
60613   8500.0     430 sot     43000.0      0.197674   Masazır q.
82625   2100.0     100 sot     10000.0      0.210000   Fatmayı q.
4586    2500.0     100 sot     10000.0      0.250000    Hövsan q.
4155    3500.0     135 sot     13500.0      0.259259  Məmmədli q.
9089    3500.0     135 sot     13500.0      0.259259  Məmmədli q.
14274   3500.0     135 sot     13500.0      0.259259  Məmmədli q.
54814   3000.0     100 sot     10000.0      0.300000     Saray q.

In [67]:
df.nlargest(20, 'price_per_m2')[[
    'price', 'Sahə', 'area_m2', 'price_per_m2', 'location'
]]

             price    Sahə  area_m2  price_per_m2              location
6605   600000000.0  200 m²    200.0  3.000000e+06  Nəriman Nərimanov m.
6942    60000000.0   50 m²     50.0  1.200000e+06    5-ci mikrorayon q.
12285     380000.0    1 m²      1.0  3.800000e+05            Şüvəlan q.
16168     380000.0    1 m²      1.0  3.800000e+05            Şüvəlan q.
9096    18500000.0  116 m²    116.0  1.594828e+05              Sahil m.
14281   18500000.0  116 m²    116.0  1.594828e+05              Sahil m.
11364     650000.0    9 m²      9.0  7.222222e+04  Azadlıq Prospekti m.
15638     650000.0    9 m²      9.0  7.222222e+04  Azadlıq Prospekti m.
34426    5000000.0   98 m²     98.0  5.102041e+04              Sahil m.
98699    5000000.0   98 m²     98.0  5.102041e+04              Sahil m.
75798    5100000.0  100 m²    100.0  5.100000e+04              Sahil m.
98693    4900000.0   99 m²     99.0  4.949495e+04              Sahil m.
44225    4000000.0   99 m²     99.0  4.040404e+04              Sahil m.
56846     280000.0    7 m²      7.0  4.000000e+04        İçəri Şəhər m.
63000     280000.0    7 m²      7.0  4.000000e+04        İçəri Şəhər m.
1743     1800000.0   48 m²     48.0  3.750000e+04             Səbail r.
6340     1800000.0   48 m²     48.0  3.750000e+04             Səbail r.
11476    1800000.0   48 m²     48.0  3.750000e+04             Səbail r.
18924    1800000.0   48 m²     48.0  3.750000e+04             Səbail r.
75832    1800000.0   48 m²     48.0  3.750000e+04             Səbail r.

In [68]:
# Flag suspicious price per m² values
df['price_per_m2_outlier'] = (
    (df['price_per_m2'] < 100) |
    (df['price_per_m2'] > 10000)
)

df[df['price_per_m2_outlier']][
    ['price', 'Sahə', 'area_m2', 'price_per_m2', 'location']
].sort_values('price_per_m2').head(20)

         price        Sahə     area_m2  price_per_m2     location
4736    2500.0  100000 sot  10000000.0      0.000250   Fatmayı q.
9746    2500.0  100000 sot  10000000.0      0.000250   Fatmayı q.
21517   2500.0  100000 sot  10000000.0      0.000250   Fatmayı q.
75857   3000.0  100000 sot  10000000.0      0.000300   Fatmayı q.
8321     800.0    2500 sot    250000.0      0.003200      Zirə q.
3348    3500.0    4000 sot    400000.0      0.008750   Buzovna q.
89280   1000.0     200 sot     20000.0      0.050000     Şıxov q.
75936  30000.0    3500 sot    350000.0      0.085714       Xaçmaz
172    80000.0    7000 sot    700000.0      0.114286   Maştağa q.
38666     11.0       89 m²        89.0      0.123596  Ağ şəhər q.
23304   1950.0     100 sot     10000.0      0.195000    Hövsan q.
35863   1950.0     100 sot     10000.0      0.195000    Hövsan q.
86013   1950.0     100 sot     10000.0      0.195000    Hövsan q.
60613   8500.0     430 sot     43000.0      0.197674   Masazır q.
82625   2100.0     100 sot     10000.0      0.210000   Fatmayı q.
4586    2500.0     100 sot     10000.0      0.250000    Hövsan q.
14274   3500.0     135 sot     13500.0      0.259259  Məmmədli q.
9089    3500.0     135 sot     13500.0      0.259259  Məmmədli q.
4155    3500.0     135 sot     13500.0      0.259259  Məmmədli q.
54814   3000.0     100 sot     10000.0      0.300000     Saray q.

In [69]:
# Count suspicious price per m² records
low_outliers = df[df['price_per_m2'] < 100]
high_outliers = df[df['price_per_m2'] > 10000]

print("Low price/m² outliers:", len(low_outliers))
print("High price/m² outliers:", len(high_outliers))

Low price/m² outliers: 1937
High price/m² outliers: 401

In [70]:
df[df['price_per_m2'] < 100][
    ['price', 'Sahə', 'area_unit', 'area_value', 'area_m2', 'price_per_m2', 'location']
].head(20)

,price,Sahə,area_unit,area_value,area_m2,price_per_m2,location
22,55000.0,12 sot,sot,12.0,1200.0,45.833333,Binə q.
34,23000.0,380 m²,m²,380.0,380.0,60.526316,Nərimanov r.
142,24000.0,16 sot,sot,16.0,1600.0,15.000000,Naxçıvan MR
172,80000.0,7000 sot,sot,7000.0,700000.0,0.114286,Maştağa q.
264,56000.0,8 sot,sot,8.0,800.0,70.000000,Hövsan q.
482,28800.0,6 sot,sot,6.0,600.0,48.000000,Sulutəpə q.
603,210000.0,24 sot,sot,24.0,2400.0,87.500000,Abşeron r.
778,150000.0,100 sot,sot,100.0,10000.0,15.000000,Qala q.
892,90000.0,12 sot,sot,12.0,1200.0,75.000000,Həzi Aslanov q.
937,180000.0,20 sot,sot,20.0,2000.0,90.000000,Novxanı q.
1077,1200000.0,200 sot,sot,200.0,20000.0,60.000000,Buzovna q.
1154,42000.0,5.5 sot,sot,5.5,550.0,76.363636,Novxanı q.
1162,70000.0,12.7 sot,sot,12.7,1270.0,55.118110,Fatmayı q.
1412,480000.0,200 sot,sot,200.0,20000.0,24.000000,Maştağa q.
1433,12000.0,2 sot,sot,2.0,200.0,60.000000,Hövsan q.
1454,10000.0,2.5 sot,sot,2.5,250.0,40.000000,Zabrat q.
1557,198000.0,20 sot,sot,20.0,2000.0,99.000000,Şüvəlan q.
1606,1400000.0,200 sot,sot,200.0,20000.0,70.000000,Xaçmaz
1610,400000.0,100 sot,sot,100.0,10000.0,40.000000,Səngəçal q.
1640,28000.0,14 sot,sot,14.0,1400.0,20.000000,Mərdəkan q.

In [71]:
df['area_m2'].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
)

count    1.007750e+05
mean     1.128061e+03
std      9.320227e+04
min      1.000000e+00
1%       3.500000e+01
5%       4.720000e+01
25%      7.000000e+01
50%      1.050000e+02
75%      1.600000e+02
95%      6.000000e+02
99%      2.800000e+03
max      2.000000e+07
Name: area_m2, dtype: float64

In [72]:
df[df['area_m2'] > 10000][
    ['price', 'Sahə', 'area_unit', 'area_value', 'area_m2', 'location']
].sort_values('area_m2', ascending=False).head(30)

            price        Sahə area_unit  area_value     area_m2       location
45825  40000000.0  200000 sot       sot    200000.0  20000000.0      28 May m.
75857      3000.0  100000 sot       sot    100000.0  10000000.0     Fatmayı q.
21517      2500.0  100000 sot       sot    100000.0  10000000.0     Fatmayı q.
9746       2500.0  100000 sot       sot    100000.0  10000000.0     Fatmayı q.
4736       2500.0  100000 sot       sot    100000.0  10000000.0     Fatmayı q.
69308  26000000.0   60000 sot       sot     60000.0   6000000.0    Binəqədi r.
28995  19000000.0   60000 sot       sot     60000.0   6000000.0    Binəqədi r.
172       80000.0    7000 sot       sot      7000.0    700000.0     Maştağa q.
87428   2640000.0    4400 sot       sot      4400.0    440000.0        Qobu q.
37618  16000000.0    4000 sot       sot      4000.0    400000.0    Lökbatan q.
3348       3500.0    4000 sot       sot      4000.0    400000.0     Buzovna q.
75936     30000.0    3500 sot       sot      3500.0    350000.0         Xaçmaz
99064  11000000.0    3400 sot       sot      3400.0    340000.0    Binəqədi q.
43823  10000000.0    3300 sot       sot      3300.0    330000.0        Qala q.
22235    450000.0    3000 sot       sot      3000.0    300000.0    Binəqədi q.
26794    450000.0    3000 sot       sot      3000.0    300000.0    Binəqədi q.
38408  15000000.0    3000 sot       sot      3000.0    300000.0        Qala q.
42194   5700000.0    2700 sot       sot      2700.0    270000.0        Qala q.
39989    475000.0    2700 sot       sot      2700.0    270000.0         Astara
21286   5700000.0    2700 sot       sot      2700.0    270000.0        Qala q.
8321        800.0    2500 sot       sot      2500.0    250000.0        Zirə q.
77727  22000000.0    2200 sot       sot      2200.0    220000.0    Lökbatan q.
15726    870000.0    2100 sot       sot      2100.0    210000.0  Pirəkəşkül q.
11510    870000.0    2100 sot       sot      2100.0    210000.0  Pirəkəşkül q.
13378   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
3763    4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
97820     65000.0    2000 sot       sot      2000.0    200000.0         Xaçmaz
41762   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
35716   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
16866   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.

In [73]:
(df['area_m2'] > 10000).sum()

df[df['area_m2'] > 10000][
    ['price', 'Sahə', 'area_unit', 'area_value', 'area_m2', 'location']
].sort_values('area_m2', ascending=False).head(50)

            price        Sahə area_unit  area_value     area_m2       location
45825  40000000.0  200000 sot       sot    200000.0  20000000.0      28 May m.
75857      3000.0  100000 sot       sot    100000.0  10000000.0     Fatmayı q.
21517      2500.0  100000 sot       sot    100000.0  10000000.0     Fatmayı q.
9746       2500.0  100000 sot       sot    100000.0  10000000.0     Fatmayı q.
4736       2500.0  100000 sot       sot    100000.0  10000000.0     Fatmayı q.
69308  26000000.0   60000 sot       sot     60000.0   6000000.0    Binəqədi r.
28995  19000000.0   60000 sot       sot     60000.0   6000000.0    Binəqədi r.
172       80000.0    7000 sot       sot      7000.0    700000.0     Maştağa q.
87428   2640000.0    4400 sot       sot      4400.0    440000.0        Qobu q.
37618  16000000.0    4000 sot       sot      4000.0    400000.0    Lökbatan q.
3348       3500.0    4000 sot       sot      4000.0    400000.0     Buzovna q.
75936     30000.0    3500 sot       sot      3500.0    350000.0         Xaçmaz
99064  11000000.0    3400 sot       sot      3400.0    340000.0    Binəqədi q.
43823  10000000.0    3300 sot       sot      3300.0    330000.0        Qala q.
22235    450000.0    3000 sot       sot      3000.0    300000.0    Binəqədi q.
26794    450000.0    3000 sot       sot      3000.0    300000.0    Binəqədi q.
38408  15000000.0    3000 sot       sot      3000.0    300000.0        Qala q.
42194   5700000.0    2700 sot       sot      2700.0    270000.0        Qala q.
39989    475000.0    2700 sot       sot      2700.0    270000.0         Astara
21286   5700000.0    2700 sot       sot      2700.0    270000.0        Qala q.
8321        800.0    2500 sot       sot      2500.0    250000.0        Zirə q.
77727  22000000.0    2200 sot       sot      2200.0    220000.0    Lökbatan q.
15726    870000.0    2100 sot       sot      2100.0    210000.0  Pirəkəşkül q.
11510    870000.0    2100 sot       sot      2100.0    210000.0  Pirəkəşkül q.
13378   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
3763    4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
97820     65000.0    2000 sot       sot      2000.0    200000.0         Xaçmaz
41762   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
35716   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
16866   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
38423  20000000.0    2000 sot       sot      2000.0    200000.0       Saray q.
60123    320000.0    2000 sot       sot      2000.0    200000.0         Xaçmaz
66175  11500000.0    2000 sot       sot      2000.0    200000.0   Kürdəxanı q.
82213   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
56565   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
93529   4000000.0    2000 sot       sot      2000.0    200000.0        Ələt q.
78601  12000000.0    1800 sot       sot      1800.0    180000.0        Zirə q.
40944  12000000.0    1800 sot       sot      1800.0    180000.0        Zirə q.
77471   2200000.0    1700 sot       sot      1700.0    170000.0         Zığ q.
18177   8000000.0    1600 sot       sot      1600.0    160000.0     Görədil q.
44103   7200000.0    1600 sot       sot      1600.0    160000.0     Görədil q.
71590   6000000.0    1500 sot       sot      1500.0    150000.0   Kürdəxanı q.
89012   6000000.0    1500 sot       sot      1500.0    150000.0   Kürdəxanı q.
99878    980000.0    1500 sot       sot      1500.0    150000.0     Buzovna q.
41029   6000000.0    1500 sot       sot      1500.0    150000.0   Kürdəxanı q.
78029   6000000.0    1500 sot       sot      1500.0    150000.0   Kürdəxanı q.
64258   6000000.0    1500 sot       sot      1500.0    150000.0   Kürdəxanı q.
84337  26000000.0    1300 sot       sot      1300.0    130000.0    Badamdar q.
89824   6500000.0    1300 sot       sot      1300.0    130000.0        Puta q.
34117   3800000.0    1300 sot       sot      1300.0    130000.0  Müşfiqabad q.

In [74]:
for limit in [1000, 2000, 5000, 10000]:
    print(
        f"Area > {limit} m²:",
        (df['area_m2'] > limit).sum()
    )

Area > 1000 m²: 2778
Area > 2000 m²: 1429
Area > 5000 m²: 633
Area > 10000 m²: 389

In [75]:
df = df[df['area_m2'] <= 1000].copy()

df['area_m2'].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
)

df.shape

(97997, 55)

In [76]:
df['area_m2'].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
)

count    97997.000000
mean       139.889424
std        130.520067
min          1.000000
1%          35.000000
5%          47.000000
25%         70.000000
50%        101.000000
75%        152.000000
95%        400.000000
99%        800.000000
max       1000.000000
Name: area_m2, dtype: float64

In [77]:
df['price_per_m2'] = df['price'] / df['area_m2']

In [78]:
df['price_per_m2'].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
)

count    9.799700e+04
mean     2.372214e+03
std      1.057032e+04
min      1.235955e-01
1%       8.500000e+01
5%       6.600000e+02
25%      1.733333e+03
50%      2.235772e+03
75%      2.750000e+03
95%      3.840885e+03
99%      6.666667e+03
max      3.000000e+06
Name: price_per_m2, dtype: float64

In [79]:
lower_bound = df['price_per_m2'].quantile(0.01)
upper_bound = df['price_per_m2'].quantile(0.99)

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

low_outliers = (df['price_per_m2'] < lower_bound).sum()
high_outliers = (df['price_per_m2'] > upper_bound).sum()

print("Low price/m² outliers:", low_outliers)
print("High price/m² outliers:", high_outliers)

Lower bound: 85.0
Upper bound: 6666.666666666667
Low price/m² outliers: 949
High price/m² outliers: 965

In [80]:
df[df['price_per_m2'] < lower_bound][
    ['price', 'Sahə', 'area_m2', 'price_per_m2', 'location']
].sort_values('price_per_m2').head(20)

df[df['price_per_m2'] > upper_bound][
    ['price', 'Sahə', 'area_m2', 'price_per_m2', 'location']
].sort_values('price_per_m2', ascending=False).head(20)

             price    Sahə  area_m2  price_per_m2              location
6605   600000000.0  200 m²    200.0  3.000000e+06  Nəriman Nərimanov m.
6942    60000000.0   50 m²     50.0  1.200000e+06    5-ci mikrorayon q.
12285     380000.0    1 m²      1.0  3.800000e+05            Şüvəlan q.
16168     380000.0    1 m²      1.0  3.800000e+05            Şüvəlan q.
14281   18500000.0  116 m²    116.0  1.594828e+05              Sahil m.
9096    18500000.0  116 m²    116.0  1.594828e+05              Sahil m.
11364     650000.0    9 m²      9.0  7.222222e+04  Azadlıq Prospekti m.
15638     650000.0    9 m²      9.0  7.222222e+04  Azadlıq Prospekti m.
34426    5000000.0   98 m²     98.0  5.102041e+04              Sahil m.
98699    5000000.0   98 m²     98.0  5.102041e+04              Sahil m.
75798    5100000.0  100 m²    100.0  5.100000e+04              Sahil m.
98693    4900000.0   99 m²     99.0  4.949495e+04              Sahil m.
44225    4000000.0   99 m²     99.0  4.040404e+04              Sahil m.
56846     280000.0    7 m²      7.0  4.000000e+04        İçəri Şəhər m.
63000     280000.0    7 m²      7.0  4.000000e+04        İçəri Şəhər m.
18924    1800000.0   48 m²     48.0  3.750000e+04             Səbail r.
11476    1800000.0   48 m²     48.0  3.750000e+04             Səbail r.
6340     1800000.0   48 m²     48.0  3.750000e+04             Səbail r.
1743     1800000.0   48 m²     48.0  3.750000e+04             Səbail r.
75832    1800000.0   48 m²     48.0  3.750000e+04             Səbail r.

In [81]:
df[df['price_per_m2'] < lower_bound][
    ['price', 'Sahə', 'area_m2', 'price_per_m2', 'location']
].sort_values('price_per_m2').head(20)

        price    Sahə  area_m2  price_per_m2         location
38666    11.0   89 m²     89.0      0.123596      Ağ şəhər q.
22304    73.0   90 m²     90.0      0.811111      Məmmədli q.
39775   127.0  150 m²    150.0      0.846667         Sahil q.
62110  1000.0  10 sot   1000.0      1.000000       Hökməli q.
32050  1700.0  10 sot   1000.0      1.700000  Aşağı Güzdək q.
9131   1300.0   6 sot    600.0      2.166667          Qala q.
14296  1300.0   6 sot    600.0      2.166667          Qala q.
13114  2500.0  10 sot   1000.0      2.500000      Nardaran q.
16694  2500.0  10 sot   1000.0      2.500000      Nardaran q.
78900  3200.0  10 sot   1000.0      3.200000          Qala q.
69951  1000.0   3 sot    300.0      3.333333           Xaçmaz
65078  1000.0   3 sot    300.0      3.333333           Xaçmaz
54134  1000.0   3 sot    300.0      3.333333           Xaçmaz
92140  1000.0   3 sot    300.0      3.333333           Xaçmaz
48912  3500.0  10 sot   1000.0      3.500000     Kürdəxanı q.
94756  3850.0  10 sot   1000.0      3.850000          Binə q.
63733  4000.0  10 sot   1000.0      4.000000       Novxanı q.
66962  1200.0   3 sot    300.0      4.000000       Maştağa q.
63189  1200.0   3 sot    300.0      4.000000       Maştağa q.
80209  2500.0   6 sot    600.0      4.166667          Binə q.

In [82]:
df = df[
    (df['price_per_m2'] >= lower_bound) &
    (df['price_per_m2'] <= upper_bound)
].copy()

print(df.shape)

df['price_per_m2'].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
)

(96083, 55)

count    96083.000000
mean      2254.512676
std        911.827544
min         85.000000
1%         240.000000
5%         733.333333
25%       1750.000000
50%       2235.714286
75%       2733.333333
95%       3678.571429
99%       5166.666667
max       6666.666667
Name: price_per_m2, dtype: float64

In [83]:
df['price'].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
)

count    9.608300e+04
mean     2.792106e+05
std      2.711152e+05
min      8.500000e+03
1%       4.500000e+04
5%       7.800000e+04
25%      1.450000e+05
50%      2.150000e+05
75%      3.290000e+05
95%      6.500000e+05
99%      1.390000e+06
max      6.300000e+06
Name: price, dtype: float64

In [84]:
df.isnull().sum().sort_values(ascending=False).head(20)

Binanın növü         95936
featured             93152
vip                  88060
hour_y               81281
Torpaq sahəsi        80634
mortgage             63990
shop_title           26327
shop_name            26327
bill_of_sale         20694
Mərtəbə              20306
repair               15588
Otaq sayı             5067
owner_name             637
owner_title            637
description            242
location                 0
currency_x               0
price                    0
datetime_scrape_x        0
estate_rel_url_x         0
dtype: int64

In [85]:
missing_pct = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

missing_pct.head(20)

Binanın növü         99.847007
featured             96.949512
vip                  91.649928
hour_y               84.594569
Torpaq sahəsi        83.921193
mortgage             66.598670
shop_title           27.400269
shop_name            27.400269
bill_of_sale         21.537629
Mərtəbə              21.133811
repair               16.223473
Otaq sayı             5.273566
owner_name            0.662968
owner_title           0.662968
description           0.251866
location              0.000000
currency_x            0.000000
price                 0.000000
datetime_scrape_x     0.000000
estate_rel_url_x      0.000000
dtype: float64

In [86]:
columns_to_drop = [
    'Binanın növü',
    'featured',
    'vip',
    'hour_y',
    'Torpaq sahəsi',
    'mortgage'
]

df = df.drop(columns=columns_to_drop)

print(df.shape)

(96083, 49)

In [87]:
df[['shop_title', 'shop_name', 'bill_of_sale', 'Mərtəbə',
    'repair', 'Otaq sayı', 'owner_name', 'owner_title',
    'description']].dtypes

shop_title       object
shop_name        object
bill_of_sale     object
Mərtəbə          object
repair           object
Otaq sayı       float64
owner_name       object
owner_title      object
description      object
dtype: object

In [88]:
df['Otaq sayı'].describe()

count    91016.000000
mean         3.121352
std          1.328455
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max         20.000000
Name: Otaq sayı, dtype: float64

In [89]:
df['Otaq sayı'] = df['Otaq sayı'].fillna(df['Otaq sayı'].median())

In [90]:
df['Otaq sayı'].isnull().sum()

np.int64(0)

In [92]:
for col in ['repair', 'bill_of_sale', 'Mərtəbə']:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(15))

--- repair ---
repair
Təmirli    80495
NaN        15588
Name: count, dtype: int64

--- bill_of_sale ---
bill_of_sale
Çıxarış var    75389
NaN            20694
Name: count, dtype: int64

--- Mərtəbə ---
Mərtəbə
NaN        20306
5 / 5       1987
3 / 5       1760
2 / 5       1755
4 / 5       1678
8 / 9       1368
7 / 9       1065
9 / 9       1032
16 / 17     1014
6 / 9       1006
7 / 16       990
15 / 17      984
1 / 5        969
2 / 9        955
8 / 16       939
Name: count, dtype: int64

In [93]:
df['repair'] = df['repair'].fillna('Məlum deyil')
df['bill_of_sale'] = df['bill_of_sale'].fillna('Məlum deyil')

print(df['repair'].isnull().sum())
print(df['bill_of_sale'].isnull().sum())

0
0

In [94]:
df['Mərtəbə'].nunique(), df['Mərtəbə'].dropna().head(20).tolist()

(358,
 ['7 / 9',
  '15 / 16',
  '3 / 4',
  '2 / 5',
  '3 / 18',
  '11 / 13',
  '19 / 20',
  '3 / 16',
  '10 / 16',
  '4 / 5',
  '5 / 6',
  '12 / 16',
  '16 / 18',
  '3 / 6',
  '5 / 6',
  '9 / 16',
  '8 / 9',
  '13 / 17',
  '5 / 5',
  '4 / 17'])

In [95]:
df[['floor', 'total_floors']] = df['Mərtəbə'].str.split('/', expand=True)

df['floor'] = pd.to_numeric(df['floor'], errors='coerce')
df['total_floors'] = pd.to_numeric(df['total_floors'], errors='coerce')

df[['Mərtəbə', 'floor', 'total_floors']].head(20)

    Mərtəbə  floor  total_floors
0     7 / 9    7.0           9.0
1       NaN    NaN           NaN
2       NaN    NaN           NaN
3       NaN    NaN           NaN
4   15 / 16   15.0          16.0
5     3 / 4    3.0           4.0
6     2 / 5    2.0           5.0
7    3 / 18    3.0          18.0
8       NaN    NaN           NaN
9   11 / 13   11.0          13.0
10      NaN    NaN           NaN
11      NaN    NaN           NaN
12  19 / 20   19.0          20.0
13      NaN    NaN           NaN
14   3 / 16    3.0          16.0
15  10 / 16   10.0          16.0
16    4 / 5    4.0           5.0
17    5 / 6    5.0           6.0
18      NaN    NaN           NaN
19  12 / 16   12.0          16.0

In [96]:
df = df.drop(columns=['Mərtəbə'])

print(df.shape)

(96083, 50)

In [97]:
df.isnull().sum().sort_values(ascending=False).head(20)

shop_title           26327
shop_name            26327
total_floors         20306
floor                20306
owner_name             637
owner_title            637
description            242
estate_rel_url_x         0
city_when                0
city                     0
day_x                    0
datetime_scrape_x        0
price                    0
currency_x               0
location                 0
attributes               0
id_x                     0
rel_url                  0
estate_id                0
id_y                     0
dtype: int64

In [98]:
df[['shop_title', 'shop_name']].head(20)

                  shop_title         shop_name
0                        NaN               NaN
1                        NaN               NaN
2                        NaN               NaN
3                        NaN               NaN
4   Daşınmaz əmlak agentliyi        Elite Ofis
5                        NaN               NaN
6                        NaN               NaN
7                        NaN               NaN
8                        NaN               NaN
9   Daşınmaz əmlak agentliyi          MS Group
10                       NaN               NaN
11                       NaN               NaN
12  Daşınmaz əmlak agentliyi  New House Nəsimi
13                       NaN               NaN
14  Daşınmaz əmlak agentliyi  VİP House Elmlər
15  Daşınmaz əmlak agentliyi  VİP House Elmlər
16                       NaN               NaN
17                       NaN               NaN
18                       NaN               NaN
19                       NaN               NaN

In [99]:
df = df.drop(columns=['shop_title'])
print(df.shape)

(96083, 49)

In [100]:
df.dtypes

id_x                     object
rel_url                  object
estate_rel_url_x         object
datetime_scrape_x        object
price                   float64
currency_x               object
location                 object
attributes               object
city_when                object
city                     object
day_x                    object
hour_x                   object
repair                   object
products_label           object
bill_of_sale             object
img_url                  object
id_y                     object
estate_id                object
estate_rel_url_y         object
datetime_scrape_y        object
description              object
total_price             float64
currency_y               object
owner_name               object
owner_title              object
shop_name                object
address                  object
lat                     float64
lng                     float64
updated                  object
views                     int64
day_y                    object
estate_details_id_x      object
Kateqoriya               object
Otaq sayı               float64
Sahə                     object
Təmir                    object
Çıxarış                  object
İpoteka                  object
estate_details_id_y      object
estate_rel_url           object
extra_info               object
price_per_m2            float64
area_unit                object
area_value              float64
area_m2                 float64
price_per_m2_outlier       bool
floor                   float64
total_floors            float64
dtype: object